local EchoCreek = {
    spawn = { x = 3573, y = 10896, z = 1 },
    purgeToxinsCoords = {
        {x = 3567, y = 10899, z = -1,},
    },
    -- generators = {
    --     { sprite = "industry_02_67", x = 3565, y = 10898, z = -1, ghost = false, },
    --     { sprite = "walls_commercial_03_17", x = 3581, y = 10904, z = 0, ghost = true, },
    -- },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 3565, y = 10898, z = -1, ghost = false, },
            chunks = {
                {445, 1362},
                {445, 1363},
                {446, 1362},
                {446, 1363},
                {446, 1361},
                {447, 1361},
                {447, 1362},
                {447, 1363},
                {446, 1364}, -- gas pumps outside
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_75", x = 3563, y = 10904, z = -1, },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_22", x = 3577, y = 10893, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_bathroom_01_4", x = 3578, y = 10893, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_32", x = 3566, y = 10899, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_17", x = 3569, y = 10897, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_bathroom_01_4", x = 3562, y = 10897, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_12", x = 3563, y = 10897, z = 0, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "appliances_laundry_01_5", x = 3562, y = 10900, z = 1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_9", x = 3567, y = 10897, z = 1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_bathroom_01_25", x = 3569, y = 10897, z = 1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_bathroom_01_2", x = 3571, y = 10897, z = 1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_3", x = 3571, y = 10899, z = 1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
        { sprite = "fixtures_sinks_01_32", x = 3567, y = 10904, z = -1, sourceType="tank", source = {x = 3563, y = 10904, z = -1} },
    },
    doorKeys = {
        name = "Echo Creek Station",
        doors = {
            { sprite = "fixtures_doors_01_45", x = 3572, y = 10906, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 3570, y = 10893, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 3563, y = 10899, z = 1, },
        },
    },
    map = {name = "DWAPStashMap2",},
    objectSpawns = {
        { sprite = "industry_02_64", x = 3562, y = 10898, z = -1, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
        { sprite = "industry_02_68", x = 3562, y = 10897, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_65", x = 3563, y = 10898, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_69", x = 3563, y = 10897, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_66", x = 3564, y = 10898, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_70", x = 3564, y = 10897, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_67", x = 3565, y = 10898, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_71", x = 3565, y = 10897, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
    },
    loot = {
        { -- house next to couch
            type = 'container',
            coords = {x=3566, y=10901,z=1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- bookcase1
            type = 'container',
            coords = {x=3562, y=10902,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- bookcase2
            type = 'container',
            coords = {x=3562, y=10901,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- end table
            type = 'container',
            coords = {x=3563, y=10901,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- tv stand
            type = 'container',
            coords = {x=3564,y=10905,z=1},
            items = {
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.VHS_Retail', chance = 1, count = {30,30} },
            },
        },
        { -- bunkbed bedroom
            type = 'container',
            coords = {x=3572,y=10903,z=1},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- twin bedroom
            type = 'container',
            coords = {x=3573,y=10905,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- twin bedroom
            type = 'container',
            coords = {x=3575,y=10905,z=1},
            dist = {"BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        { -- twin bedroom
            type = 'container',
            coords = {x=3573,y=10904,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- twin bedroom
            type = 'container',
            coords = {x=3573,y=10903,z=1},
            dist = {"GymLaundry", "GymLockers","ArmyStorageOutfit",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- twin bedroom closet
            type = 'container',
            coords = {x=3576,y=10900,z=1.5},
            dist = {"SewingStoreTools","SewingStoreFabric","CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- master bedroom closet
            type = 'container',
            coords = {x=3576,y=10899,z=1.5},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- master bedroom wardrobe
            type = 'container',
            coords = {x=3576,y=10898,z=1},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- master bedroom wardrobe
            type = 'container',
            coords = {x=3576,y=10897,z=1},
            dist = {"FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- master bedroom nightstand
            type = 'container',
            coords = {x=3575,y=10894,z=1},
            dist = {"DrugLabGuns"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- master bedroom nightstand
            type = 'container',
            coords = {x=3572,y=10894,z=1},
            dist = {"ArmyStorageGuns",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- master bedroom
            type = 'container',
            coords = {x=3571,y=10896,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- bathroom
            type = 'container',
            coords = {x=3569,y=10899,z=1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical", "MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- bathroom
            type = 'container',
            coords = {x=3571,y=10899,z=1},
            dist = {"LaundryCleaning", "JanitorCleaning", "MedicalStorageDrugs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=3566,y=10898,z=1},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3566,y=10897,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3567,y=10897,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3568,y=10897,z=1},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3568,y=10898,z=1},
            dist = {"GroceryBagGourmet","StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- mechanic's storage
        {
            type = 'container',
            coords = {x=3581,y=10894,z=0.5},
            dist = {"FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=3581,y=10891,z=0},
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=3583,y=10891,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=3583,y=10892,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=3585,y=10891,z=0},
            dist = {"CarSupplyTools", "GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3585,y=10892,z=0},
            dist = {"CarSupplyTools", "GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3584,y=10894,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=3585,y=10894,z=0},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        -- lift area
        {
            type = 'container',
            coords = {x=3581,y=10895,z=0},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3582,y=10895,z=0},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3583,y=10895,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3584,y=10895,z=0},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=3585,y=10895,z=0},
            dist = {"LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- bin
            type = 'container',
            coords = {x=3585,y=10903,z=0},
            dist = {"CrateRandomJunk", "RandomFiller", "ArmySurplusMisc" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 3,
        },
        -- servo storage area
        {
            type = 'container',
            coords = {x=3571,y=10895,z=0},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=3572,y=10895,z=0},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=3573,y=10895,z=0},
            dist = {"SafehouseTraps","CampingLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=3574,y=10895,z=0},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- box
            type = 'container',
            coords = {x=3574,y=10893,z=0},
            dist = {"CafeteriaSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- basement
        { -- by water tank
            type = 'container',
            coords = {x=3562,y=10902,z=-1},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3562,y=10901,z=-1},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- by generator
            type = 'container',
            coords = {x=3566,y=10897,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3567,y=10897,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3568,y=10897,z=-1},
            dist = {"LoggingFactoryTools", "CrateTools", "BurglarTools", "CarpenterTools", "BarnTools","CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- back corner room
        {
            type = 'container',
            coords = {x=3570,y=10891,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3571,y=10891,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3570,y=10893,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3571,y=10893,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3576,y=10896,z=-1},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=3572,y=10894,z=-1},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
        },
        {
            type = 'container',
            coords = {x=3571,y=10894,z=-1},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
        },
        -- crates
        {
            type = 'container',
            coords = {x=3572,y=10902,z=-1},
            items = {
                { name = 'Base.NailsCarton', chance = 1, count = {1,4} },
            },
        },
        {
            type = 'container',
            coords = {x=3574,y=10905,z=-1},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
        },
        {
            type = 'container',
            coords = {x=3575,y=10905,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=3576,y=10905,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=3576,y=10904,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- metal shelves by sink
            type = 'container',
            coords = {x=3567,y=10905,z=-1},
            dist = {"CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
    },
}

return EchoCreek