local wtc = {x = 12030, y = 2581, z = -1,}
local LVilleMansion = {
    spawn = { x = 12021, y = 2588, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 12049, y = 2578, z = 0, ghost = false, },
            chunks = {
                -- garage
                {1504, 322},
                {1504, 323},
                {1505, 322},
                {1505, 323},
                {1506, 322},
                {1506, 323},
                -- house
                {1502, 323},
                {1502, 324},
                {1502, 325},
                {1503, 323},
                {1503, 324},
                {1503, 325},
                -- basement
                {1503, 322},
                -- {1503, 323},
                -- {1503, 324},
                -- {1503, 325},
                -- {1504, 322},
                -- {1504, 323},
                {1504, 324},
                {1504, 325},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 12049, y = 2578, z = 0} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_17", x = 12041, y = 2580, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_5", x = 12044, y = 2577, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_10", x = 12029, y = 2588, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12024, y = 2595, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12025, y = 2595, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_0", x = 12020, y = 2593, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_5", x = 12018, y = 2593, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_0", x = 12027, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12028, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12029, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_52", x = 12026, y = 2591, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_1", x = 12023, y = 2596, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 12023, y = 2597, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 12023, y = 2598, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_52", x = 12025, y = 2598, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement
        { sprite = "fixtures_sinks_01_25", x = 12036, y = 2590, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_35", x = 12033, y = 2599, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 12033, y = 2585, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Louisville Safehouse",
        doors = {
            { sprite = "fixtures_doors_01_40", x = 12037, y = 2587, z = 0, },
            { sprite = "fixtures_doors_02_4", x = 12029, y = 2593, z = 0, },
            { sprite = "fixtures_doors_02_4", x = 12028, y = 2593, z = 0, },
            { sprite = "fixtures_doors_01_32", x = 12031, y = 2592, z = -1, },
            { sprite = "walls_garage_01_52", x = 12030, y = 2583, z = -1, },
            { sprite = "walls_garage_01_53", x = 12031, y = 2583, z = -1, },
        },
    },
    map = { name = "DWAPStashMap3", },
    objectSpawns = {
        { sprite = "fixtures_doors_frames_01_1", x = 12037, y = 2579, z = 0, replaceWall = true, },
        { sprite = "walls_interior_house_03_20", x = 12037, y = 2579, z = 0, },
        -- { sprite = "fixtures_doors_01_1", x = 12037, y = 2579, z = 0, isDoor = true, doorN = true, },
        { sprite = "walls_interior_house_03_20", x = 12038, y = 2580, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_112", x = 12038, y = 2581, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_115", x = 12038, y = 2582, z = 0, },
        { sprite = "fixtures_doors_01_1", x = 12038, y = 2580, z = 0, isDoor = true, doorN = true, },

        { sprite = "fixtures_railings_01_28", x = 12025, y = 2600, z = 0, }, -- basement railing
        { sprite = "fixtures_railings_01_28", x = 12025, y = 2599, z = 0, }, -- basement railing
        { sprite = "fixtures_railings_01_28", x = 12025, y = 2598, z = 0, }, -- basement railing
        { sprite = "fixtures_railings_01_4", x = 12025, y = 2598, z = 0, }, -- basement railing

        { barricade = "metalbar", enabled = "Barricade", target="walls_exterior_house_02_40", x = 12030, y = 2588, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_40", x = 12030, y = 2590, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_03_9", x = 12024, y = 2586, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_03_40", x = 12018, y = 2589, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_04_72", x = 12018, y = 2597, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_exterior_house_02_41", x = 12022, y = 2601, z = 0, },

        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_16", x = 12037, y = 2586, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_16", x = 12037, y = 2585, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_16", x = 12037, y = 2584, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_16", x = 12037, y = 2583, z = 0, },

    },
    loot = {
        -- garage
        {
            type = 'container',
            coords = {x = 12026, y = 2596, z = 0.5},
            dist = {"GasStoreEmergency","StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        -- office
        {
            type = 'container',
            coords = {x=12018,y=2587,z=0},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=12021,y=2587,z=0},
            dist = {"CafeteriaSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- living room
        {
            type = 'container',
            coords = {x=12023,y=2600,z=0},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2597,z=0},
            items = {
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 0.5, count = {30,30} },
            },
        },
        {
            type = 'container',
            coords = {x=12018,y=2593,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning","CrateLinens"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2593,z=0},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- front door closet
            type = 'container',
            coords = {x=12029,y=2591,z=0.5},
            dist = { "GunStoreKnives", "CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=12028,y=2590,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12027,y=2587,z=0},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12028,y=2587,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2587,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2588,z=0},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2589,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2590,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- 2nd floor
        { -- mb
            type = 'container',
            coords = {x=12018,y=2588,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- mb
            type = 'container',
            coords = {x=12018,y=2587,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- mb bath
            type = 'container',
            coords = {x=12028,y=2590,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- mb bath
            type = 'container',
            coords = {x=12029,y=2590,z=1},
            dist = {"BathroomCounter", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12024,y=2591,z=1.5},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- w bed
            type = 'container',
            coords = {x=12018,y=2597,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12018,y=2595,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2595,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2600,z=1.5},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2697,z=1},
            dist = {"SafehouseMedical_Late", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2696,z=1},
            dist = {"DerelictHouseCrime", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12026,y=2595,z=1.5},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12024,y=2599,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2591,z=1.5},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },

        -- garage
        {
            type = 'container',
            coords = {x = 12039, y = 2580, z = 0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12040, y = 2580, z = 0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12041, y = 2580, z = 0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12042, y = 2580, z = 0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12037, y = 2577, z = 0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12038, y = 2577, z = 0},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12039, y = 2577, z = 0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        {
            type = 'container',
            coords = {x = 12040, y = 2577, z = 0},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles", "CandyStoreSnacks", "CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 12041, y = 2577, z = 0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12042, y = 2577, z = 0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12047, y = 2580, z = 0},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12048, y = 2580, z = 0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12049, y = 2580, z = 0},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12050, y = 2580, z = 0},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12044, y = 2577, z = 0},
            dist = {"CrateCannedFood", "ArmySurplusTools", "CrateToiletPaper" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
    },
}

local v14loot = LVilleMansion.loot
local v14bunkerTopLeft = {x = 12022, y = 2589, z = -1}

local v14oldLoot = {
    { -- cabinet next to bunk beds (9365)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+2,z=v14bunkerTopLeft.z},
        dist = {"CrateCannedFood", "KitchenCannedFood"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+3,z=v14bunkerTopLeft.z+0.5},
        dist = {"CrateCannedFood", "KitchenCannedFood"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- lower (66)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+3,z=v14bunkerTopLeft.z},
        dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+4,z=v14bunkerTopLeft.z+0.5},
        dist = {"GroceryBagGourmet",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- lower (67)
        type = 'container',
        sprite = 'location_trailer_02_19',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+4,z=v14bunkerTopLeft.z},
        dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z+0.5},
        dist = {"CrateFishing", "FishermanTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    { -- lower (68)
        type = 'container',
        sprite = 'location_trailer_02_19',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z},
        dist = {"SewingStoreTools"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    { -- metal shelves (70)
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+7,z=v14bunkerTopLeft.z},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    { -- metal shelves (71)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+8,z=v14bunkerTopLeft.z},
        sandboxEnable = 'SeedLibrary',
        special = 'SeedLibrary',
    },
    { -- next to inner door (9372)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+9,z=v14bunkerTopLeft.z},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    { -- (73)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+10,z=v14bunkerTopLeft.z},
        dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    { -- (9374)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+11,z=v14bunkerTopLeft.z},
        dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    { -- far end next to stairs (9375)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+12,z=v14bunkerTopLeft.z},
        special = "essentials",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks1",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+6,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks2",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+7,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillmags",
    },
}
for i = 1, #v14oldLoot do
    v14loot[#v14loot + 1] = v14oldLoot[i]
end

local v15loot = {
    -- storage room south west
    {
        type = 'container',
        coords = {x=12026,y=2599,z=-1},
        dist = {"CrateTortillaChips","CrateCannedFood", "KitchenCannedFood"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2598,z=-1},
        dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2597,z=-1},
        dist = {"ButcherSpices","GigamartSpices", "GigamartDryGoods",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2596,z=-1},
        dist = {"GigamartBreakfast","GigamartCandy","Homesteading","CrateLiquor",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2595,z=-1},
        dist = {"CrateFlour", "CrateOilVegetable"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12027,y=2595,z=-1},
        dist = {"FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2595,z=-1},
        dist = {"FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2598,z=-1},
        dist = {"FridgeFarmStorage", "FridgeGeneric"},
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2597,z=-1},
        dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2595,z=-1},
        dist = {"FridgeFarmStorage", "FridgeGeneric"},
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2599,z=-1},
        dist = {"CrateFlour", "CrateOilVegetable"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2598,z=-1},
        dist = {"CrateFlour", "GigamartBakingMisc",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- workshop
    {
        type = 'container',
        coords = {x=12033,y=2595,z=-1},
        special = "essentials",
    },
    {
        type = 'container',
        coords = {x=12035,y=2599,z=-1},
        dist = {"ArtStorePottery",},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    -- armory
    {
        type = 'container',
        coords = {x=12031,y=2590,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12032,y=2590,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12033,y=2590,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12034,y=2590,z=-1},
        dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12035,y=2590,z=-1},
        dist = { "GunStoreKnives", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12032,y=2592,z=-1},
        dist = {"DrugLabGuns","PoliceStorageGuns", "PoliceStorageAmmunition"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12033,y=2592,z=-1},
        dist = {"ArmyStorageGuns","FirearmWeapons_Late"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12034,y=2592,z=-1},
        dist = {"HuntingLockers", "RangerTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12031,y=2594,z=-1},
        dist = {"ArmyStorageAmmunition", },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12032,y=2594,z=-1},
        dist = {"ArmyStorageAmmunition", },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12033,y=2594,z=-1},
        dist = {"SafehouseTraps", "ArmyStorageAmmunition"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=12034,y=2594,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {30,30} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    -- office
    {
        type = 'container',
        coords = {x=12026,y=2591,z=-1},
        dist = {"MusicStoreCDs"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2590,z=-1},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks1",
    },
    {
        type = 'container',
        coords = {x=12029,y=2590,z=-1},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks2",
    },
    {
        type = 'container',
        coords = {x=12030,y=2590,z=-1},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillmags",
    },
    {
        type = 'container',
        coords = {x=12030,y=2591,z=-1},
        dist = {"BookstoreBiography", "BookstoreArt", "BookstoreGeneralReference", "BookstoreChilds", "BookstoreHistory", },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    {
        type = 'container',
        coords = {x=12029,y=2594,z=-1},
        dist = {"CrateLiquor", "DishCabinetVIPLounge"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2594,z=-1},
        dist = {"CrateLiquor", "DishCabinetVIPLounge"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- infirmary
    {
        type = 'container',
        coords = {x=12031,y=2589,z=-1},
        dist = {"LaboratoryLockers", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=12031,y=2588,z=-1},
        dist = {"MorgueTools", "MedicalCabinet", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=12031,y=2585,z=-1},
        dist = {"ArmyStorageMedical", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=12033,y=2585,z=-1},
        dist = {"ArmyBunkerMedical" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=12035,y=2589,z=-1},
        dist = {"MedicalClinicDrugs", "SafehouseMedical" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=12034,y=2589,z=-1},
        dist = {"SafehouseFreezer_Mid" },
        distIncludeJunk = true,
        randUntilFull = true,
        frozen = true,
        level = "Loot_MedLevel",
    },
    -- north west storage room
    {
        type = 'container',
        coords = {x=12026,y=2589,z=-1},
        dist = {"SewingStoreTools"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2588,z=-1},
        dist = {"SewingStoreFabric", "CrateLeather"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2587,z=-1},
        dist = {"CrateBootsArmy"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2586,z=-1},
        dist = {"ArmyStorageOutfit", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=12026,y=2585,z=-1},
        dist = { "ArmySurplusOutfit",},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2589,z=-1},
        sandboxEnable = 'SeedLibrary',
        special = 'SeedLibrary',
    },
    {
        type = 'container',
        coords = {x=12028,y=2588,z=-1},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2587,z=-1},
        dist = {"SafehouseArmor", "SafehouseLighting"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=12028,y=2586,z=-1},
        dist = {"CrateFishing", "FishermanTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2589,z=-1},
        dist = {"CrateSheetMetal" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2588,z=-1},
        dist = {"ArmyStorageElectronics", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = {x=12030,y=2587,z=-1},
        dist = {"CrateLumber"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    -- {
    --     type = 'container',
    --     coords = {x=12030,y=2586,z=-1},
    --     dist = {"CrateFishing", "FishermanTools"},
    --     distIncludeJunk = false,
    --     randUntilFull = true,
    --     level = "Loot_FishLevel",
    -- },
    {
        type = 'container',
        coords = {x=12030,y=2585,z=-1},
        dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
}

for i = 1, #v15loot do
    LVilleMansion.loot[#LVilleMansion.loot + 1] = v15loot[i]
end

local v14wtc = {x = 12035, y = 2579, z = 0,}

-- back compat
LVilleMansion.overrides = {
    [1] = {
        version = 14,
        loot = v14loot,
        waterTanks = {
            { sprite = "industry_02_72", x = v14wtc.x, y = v14wtc.y, z = v14wtc.z, isProp = true, sourceType="generator", source = {x = 12049, y = 2578, z = 0} },
        },
        objectSpawns = {
            { sprite = "industry_02_72", x = 12035, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- tank left
            { sprite = "industry_02_73", x = 12036, y = 2579, z = 0, enabled = "EnableWaterSystem", }, --tank right
            { sprite = "industry_02_74", x = 12035, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- tank back left
            { sprite = "industry_02_75", x = 12036, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- tank back right
            { sprite = "industry_02_25", x = 12034, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- pipe
            { sprite = "industry_02_27", x = 12034, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12033, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12032, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12031, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12030, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12029, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12028, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12027, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12026, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12025, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12024, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12023, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12022, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12021, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12020, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12019, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12018, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12017, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12016, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12015, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12014, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12013, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12012, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12011, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12010, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12009, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12008, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12007, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12006, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12005, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12004, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12003, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12002, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12001, y = 2579, z = 0, enabled = "EnableWaterSystem", },
            { sprite = "industry_02_33", x = 12000, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- end pipe
            { sprite = "industry_02_52", x = 11999, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- pump

            { sprite = "fixtures_railings_01_36", x = 12025, y = 2600, z = 0, }, -- basement railing
            { sprite = "fixtures_railings_01_36", x = 12025, y = 2599, z = 0, }, -- basement railing
            { sprite = "fixtures_railings_01_36", x = 12025, y = 2598, z = 0, }, -- basement railing
        },
        waterFixtures = {
            { sprite = "fixtures_sinks_01_17", x = 12041, y = 2580, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_5", x = 12044, y = 2577, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_10", x = 12029, y = 2588, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_12", x = 12024, y = 2595, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_0", x = 12025, y = 2595, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "appliances_laundry_01_0", x = 12020, y = 2593, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_5", x = 12018, y = 2593, z = 0, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_0", x = 12027, y = 2587, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_12", x = 12028, y = 2587, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_12", x = 12029, y = 2587, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_52", x = 12026, y = 2591, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_1", x = 12023, y = 2596, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_sinks_01_1", x = 12023, y = 2597, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_1", x = 12023, y = 2598, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_52", x = 12025, y = 2598, z = 1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            -- basement
            { sprite = "fixtures_sinks_01_16", x = 12022, y = 2593, z = -1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
            { sprite = "fixtures_bathroom_01_6", x = 12024, y = 2597, z = -1, sourceType="tank", source = {x = v14wtc.x, y = v14wtc.y, z = v14wtc.z} },
        },
    },
}

return LVilleMansion