local wtc = {x = 12035, y = 2579, z = 0,}
local bunkerTopLeft = {x = 12022, y = 2589, z = -1}
local LVilleMansion = {
    spawn = { x = 12021, y = 2588, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 12049, y = 2578, z = 0, ghost = false, },
            chunks = {
                -- garage
                {1504, 322},
                {1504, 323},
                {1505, 322},
                {1505, 323},
                {1506, 322},
                {1506, 323},
                -- house
                {1502, 323},
                {1502, 324},
                {1502, 325},
                {1503, 323},
                {1503, 324},
                {1503, 325},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_72", x = wtc.x, y = wtc.y, z = wtc.z, isProp = true, sourceType="generator", source = {x = 12049, y = 2578, z = 0} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_17", x = 12041, y = 2580, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_5", x = 12044, y = 2577, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_10", x = 12029, y = 2588, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12024, y = 2595, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12025, y = 2595, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_0", x = 12020, y = 2593, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_5", x = 12018, y = 2593, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_0", x = 12027, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12028, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_12", x = 12029, y = 2587, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_52", x = 12026, y = 2591, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_1", x = 12023, y = 2596, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 12023, y = 2597, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 12023, y = 2598, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_52", x = 12025, y = 2598, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement
        { sprite = "fixtures_sinks_01_16", x = 12022, y = 2593, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_6", x = 12024, y = 2597, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Louisville Safehouse",
        doors = {
            { sprite = "fixtures_doors_01_40", x = 12037, y = 2587, z = 0, },
            { sprite = "fixtures_doors_02_4", x = 12029, y = 2593, z = 0, },
            { sprite = "fixtures_doors_02_4", x = 12028, y = 2593, z = 0, },
        },
    },
    map = { name = "DWAPStashMap3", },
    objectSpawns = {
        { sprite = "industry_02_72", x = 12035, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- tank left
        { sprite = "industry_02_73", x = 12036, y = 2579, z = 0, enabled = "EnableWaterSystem", }, --tank right
        { sprite = "industry_02_74", x = 12035, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- tank back left
        { sprite = "industry_02_75", x = 12036, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- tank back right
        { sprite = "industry_02_25", x = 12034, y = 2578, z = 0, enabled = "EnableWaterSystem", }, -- pipe
        { sprite = "industry_02_27", x = 12034, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12033, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12032, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12031, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12030, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12029, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12028, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12027, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12026, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12025, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12024, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12023, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12022, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12021, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12020, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12019, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12018, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12017, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12016, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12015, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12014, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12013, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12012, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12011, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12010, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12009, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12008, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12007, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12006, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12005, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12004, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12003, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12002, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12001, y = 2579, z = 0, enabled = "EnableWaterSystem", },
        { sprite = "industry_02_33", x = 12000, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- end pipe
        { sprite = "industry_02_52", x = 11999, y = 2579, z = 0, enabled = "EnableWaterSystem", }, -- pump

        { sprite = "fixtures_railings_01_36", x = 12025, y = 2600, z = 0, }, -- basement railing
        { sprite = "fixtures_railings_01_36", x = 12025, y = 2599, z = 0, }, -- basement railing
        { sprite = "fixtures_railings_01_36", x = 12025, y = 2598, z = 0, }, -- basement railing
    },
    loot = {
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            dist = {"GunCache1.GunBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        -- garage
        {
            type = 'container',
            coords = {x = 12026, y = 2596, z = 0.5},
            dist = {"GasStoreEmergency","StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        -- office
        {
            type = 'container',
            coords = {x=12018,y=2587,z=0},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=12021,y=2587,z=0},
            dist = {"CafeteriaSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- living room
        {
            type = 'container',
            coords = {x=12023,y=2600,z=0},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2597,z=0},
            items = {
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 0.5, count = {30,30} },
            },
        },
        {
            type = 'container',
            coords = {x=12018,y=2593,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2593,z=0},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- front door closet
            type = 'container',
            coords = {x=12029,y=2591,z=0.5},
            dist = { "GunStoreKnives", "CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=12027,y=2587,z=0},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12028,y=2587,z=0},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2587,z=0},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2588,z=0},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2589,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2590,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- 2nd floor
        { -- mb
            type = 'container',
            coords = {x=12018,y=2588,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- mb
            type = 'container',
            coords = {x=12018,y=2587,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- mb bath
            type = 'container',
            coords = {x=12028,y=2590,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- mb bath
            type = 'container',
            coords = {x=12029,y=2590,z=1},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12024,y=2591,z=1.5},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- w bed
            type = 'container',
            coords = {x=12018,y=2597,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12018,y=2595,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12019,y=2595,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2600,z=1.5},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2697,z=1},
            dist = {"SafehouseMedical_Late", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12023,y=2696,z=1},
            dist = {"DerelictHouseCrime", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12026,y=2595,z=1.5},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12024,y=2599,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12029,y=2591,z=1.5},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },

        -- garage
        {
            type = 'container',
            coords = {x = 12039, y = 2580, z = 0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12040, y = 2580, z = 0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 12041, y = 2580, z = 0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
        },
        {
            type = 'container',
            coords = {x = 12042, y = 2580, z = 0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
        },
        {
            type = 'container',
            coords = {x = 12037, y = 2577, z = 0},
            items = {
                { name = 'Base.NailsCarton', chance = 1, count = {1,4} },
            },
        },
        {
            type = 'container',
            coords = {x = 12038, y = 2577, z = 0},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
        },
        {
            type = 'container',
            coords = {x = 12039, y = 2577, z = 0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        {
            type = 'container',
            coords = {x = 12040, y = 2577, z = 0},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles", "CandyStoreSnacks", "CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 12041, y = 2577, z = 0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12042, y = 2577, z = 0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12047, y = 2580, z = 0},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12048, y = 2580, z = 0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12049, y = 2580, z = 0},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12050, y = 2580, z = 0},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 12044, y = 2577, z = 0},
            dist = {"CrateCannedFood", "ArmySurplusTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
    },
}

return LVilleMansion