local wtc = {x = 10659, y = 9562, z = -1} -- waterTankCoords
local MuldSafeHouse = {
    spawn = { x = 10660, y = 9567, z = 1 },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 10663, y = 9562, z = -1} },
    },
    waterFixtures = {
        { sprite = "appliances_laundry_01_4", x = 10661, y = 9560, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_0", x = 10662, y = 9560, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 10663, y = 9573, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = 10657, y = 9566, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 10657, y = 9567, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_21", x = 10657, y = 9566, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 10657, y = 9565, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 10657, y = 9573, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_21", x = 10657, y = 9572, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 10657, y = 9571, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 10663, y = 9573, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement fixtures
        { sprite = "fixtures_sinks_01_17", x = 10662, y = 9564, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_23", x = 10663, y = 9573, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_6", x = 10663, y = 9574, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_33", x = 10661, y = 9574, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Muldraugh Safe House",
        doors = {
            { sprite = "fixtures_doors_01_44", x = 10664, y = 9569, z = 0, }, -- front door
            { sprite = "walls_garage_01_0", x = 10664, y = 9563, z = 0, }, -- garage door
            { sprite = "fixtures_doors_01_9", x = 10657, y = 9561, z = 0, }, -- basement door
        },
    },
    map = { name = "DWAPStashMap5", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 10663, y = 9562, z = -1, },
            chunks = {
                {1332, 1195},
                {1332, 1196},
                {1332, 1194},
                {1333, 1195},
                {1333, 1196},
            },
        },
    },
    objectSpawns = {
        { sprite = "camping_01_16", x = 10658, y = 9554, z = 0, enabled = "EnableWaterSystem", },

        { sprite = "rooftop_furniture_22", x = 10663, y = 9559, z = 0, }, -- exhaust vent

        { sprite = "furniture_shelving_01_43", x = 10661, y = 9573, z = 0, isContainer = true,},
        { sprite = "furniture_shelving_01_43", x = 10660, y = 9573, z = 0, isContainer = true,},

        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_24", x = 10664, y = 9572, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_01_44", x = 10664, y = 9569, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_24", x = 10664, y = 9566, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_02_40", x = 10657, y = 9572, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_44", x = 10657, y = 9565, z = 0, },
    },
    loot = {
        -- garage
        {
            type = 'container',
            coords = {x=10658,y=9560,z=0},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10658,y=9561,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10658,y=9562,z=0},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10658,y=9563,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10658,y=9564,z=0.5},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10661,y=9566,z=0},
            dist = {"LoggingFactoryTools", "CrateTools", "GarageTools", "BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10662,y=9566,z=0},
            dist = {"LoggingFactoryTools", "CrateTools", "GarageTools", "BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=10659,y=9568,z=0},
            dist = {"FreezerRich", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10657,y=9567,z=0},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10657,y=9566,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10657,y=9565,z=0},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10658,y=9565,z=0},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10660,y=9565,z=0},
            dist = {"GigamartDryGoods",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- tv stand
        {
            type = 'container',
            coords = {x=10660,y=9571,z=0},
            items = {
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 1, count = {30,30} },
            },
        },
        {
            type = 'container',
            coords = {x=10663,y=9573,z=0.5},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- 2nd floor
        {
            type = 'container',
            coords = {x=10663,y=9568,z=1},
            dist = {"GymLaundry", "GymLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10663,y=9569,z=1},
            dist = {"SafehouseLighting", "SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10663,y=9570,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10662,y=9565,z=1},
            dist = {"SafehouseArmor", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10663,y=9565,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10657,y=9567,z=1.5},
            dist = {"BathroomCounter","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10663,y=9571,z=1},
            dist = {"CampingLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10660,y=9573,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10659,y=9573,z=1},
            dist = {"ArmyStorageOutfit", "CampingStoreBackpacks", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- entry way
        {
            type = 'container',
            coords = {x=10661,y=9568,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10661,y=9570,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10657,y=9569,z=0.5},
            dist = {"CrateFishing", "FishermanTools", "HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
    },
}

local v14loot = {}
for i = 1, #MuldSafeHouse.loot do
    v14loot[i] = MuldSafeHouse.loot[i]
    if MuldSafeHouse.loot[i].coords.x == 10661 and MuldSafeHouse.loot[i].coords.y == 9566 and MuldSafeHouse.loot[i].coords.z == 0 then
        v14loot[i] = {
            type = 'container',
            coords = {x=10661,y=9566,z=0},
            special = "essentials",
        }
    end
end

local v14bunkerTopLeft = {x = 10656, y = 9553, z = -2}
local v14oldLoot = {
    {
        type = 'container',
        coords = {x=10663,y=9568,z=-1},
        dist = {"FreezerRich", },
        distIncludeJunk = true,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    { -- cabinet next to bunk beds (9365)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+2,z=v14bunkerTopLeft.z},
        sandboxEnable = 'Loot_EnableMaps',
        special = "maps",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+3,z=v14bunkerTopLeft.z+0.5},
        dist = {"CrateCannedFood", "KitchenCannedFood"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- lower (66)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+3,z=v14bunkerTopLeft.z},
        dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+4,z=v14bunkerTopLeft.z+0.5},
        dist = {"GroceryBagGourmet",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    { -- lower (67)
        type = 'container',
        sprite = 'location_trailer_02_19',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+4,z=v14bunkerTopLeft.z},
        dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    { -- upper
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z+0.5},
        dist = {"CrateFishing", "FishermanTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    { -- lower (68)
        type = 'container',
        sprite = 'location_trailer_02_19',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z},
        dist = {"SewingStoreTools"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    { -- metal shelves (70)
        type = 'container',
        sprite = 'location_trailer_02_23',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+7,z=v14bunkerTopLeft.z},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    { -- metal shelves (71)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+8,z=v14bunkerTopLeft.z},
        sandboxEnable = 'SeedLibrary',
        special = 'SeedLibrary',
    },
    { -- next to inner door (9372)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+9,z=v14bunkerTopLeft.z},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    { -- (73)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+10,z=v14bunkerTopLeft.z},
        dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    { -- (9374)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+11,z=v14bunkerTopLeft.z},
        dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    { -- far end next to stairs (9375)
        type = 'container',
        coords = {x=v14bunkerTopLeft.x,y=v14bunkerTopLeft.y+12,z=v14bunkerTopLeft.z},
        dist = {"GunCache1.GunBox",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+5,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks1",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+6,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks2",
    },
    { -- metal wall shelves
        type = 'container',
        coords = {x=v14bunkerTopLeft.x+2,y=v14bunkerTopLeft.y+7,z=v14bunkerTopLeft.z+0.5},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillmags",
    },
    -- first basement level
    {
        type = 'container',
        coords = {x=10658,y=9567,z=-1},
        dist = {"CrateCannedFood", "ArmySurplusTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10667,y=9564,z=-1},
        dist = {"ArmyStorageElectronics", "RandomFiller" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = {x=10668,y=9564,z=-1},
        dist = {"CrateLumber", "CrateSheetMetal"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = {x=10664,y=9567,z=-1},
        dist = {"MusicStoreCDs"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    -- basement wood piles
    {
        type = 'container',
        coords = {x=10659,y=9559,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {10,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10660,y=9559,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {10,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9559,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {10,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
}
for i = 1, #v14oldLoot do
    v14loot[#v14loot + 1] = v14oldLoot[i]
end

local v15loot = {
    {
        type = 'container',
        coords = {x=10659,y=9565,z=1},
        dist = {"GasStoreToiletries"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- new spawned bookshelves
    {
        type = 'container',
        coords = {x=10661,y=9573,z=0},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks2",
    },
    {
        type = 'container',
        coords = {x=10660,y=9573,z=0},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillbooks1",
    },
    { -- south west corner
        type = 'container',
        coords = {x=10657,y=9574,z=-1},
        special = "essentials",
    },
    {
        type = 'container',
        coords = {x=10657,y=9573,z=-1},
        sandboxEnable = 'SeedLibrary',
        special = 'SeedLibrary',
    },
    {
        type = 'container',
        coords = {x=10657,y=9572,z=-1},
        sandboxEnable = 'Loot_EnableBooks',
        special = "skillmags",
    },
    {
        type = 'container',
        coords = {x=10657,y=9571,z=-1},
        dist = {"SewingStoreTools"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = {x=10657,y=9570,z=-1},
        dist = {"CrateFishing", "FishermanTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    {
        type = 'container',
        coords = {x=10657,y=9569,z=-1},
        dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10657,y=9568,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10657,y=9567,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10658,y=9565,z=-1},
        dist = {"WesternKitchenFreezer","FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10658,y=9564,z=-1},
        dist = {"StoreShelfDrinks", "CrateCannedFood", "CrateSodaBottles", "CandyStoreSnacks", "CrateTortillaChips"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10660,y=9564,z=-1},
        dist = {"FridgeFarmStorage", "FridgeGeneric"},
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10660,y=9564,z=-0.5},
        dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9564,z=-1},
        dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9564,z=-0.5},
        dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10662,y=9564,z=-1},
        dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10662,y=9564,z=-0.5},
        dist = {"BakeryKitchenFreezer", "CrateCannedFood", "CafeKitchenCoffee" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10663,y=9564,z=-0.5},
        dist = {"GigamartCrisps", "SafehouseFireplace"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9571,z=-1},
        dist = {"RangerTools", "CrateFishing", "FishermanTools"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9573,z=-0.5},
        dist = {"SafehouseMedical", "CrateLinens"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=10663,y=9573,z=-1},
        dist = {"BathroomCounter", "GasStoreToiletries",},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9570,z=-1},
        sandboxEnable = 'SeedLibrary',
        items = {
            { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9569,z=-1},
        sandboxEnable = 'SeedLibrary',
        items = {
            { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9568,z=-1},
        dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "SafehouseArmor", "DerelictHouseCrime", "CrateBootsArmy", "SafehouseLighting"},
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9567,z=-1},
        dist = {"MorgueTools", "ArmyStorageMedical", "ArmyBunkerMedical", "MedicalClinicDrugs", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = {x=10661,y=9566,z=-1},
        dist = {"CrateLiquor", "LiquorStoreWhiskey"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = {x=10663,y=9570,z=-1},
        sandboxEnable = 'Loot_EnableMaps',
        special = "maps",
    },
    {
        type = 'container',
        coords = {x=10659,y=9574,z=-1},
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10659,y=9573,z=-1},
        dist = {"ArmyStorageAmmunition", "GunStoreKnives", "DerelictHouseCrime" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10659,y=9572,z=-1},
        dist = { "PoliceStorageGuns", "PoliceStorageAmmunition", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10659,y=9571,z=-1},
        dist = {"ArmyStorageAmmunition", "GunStoreAmmunition", "RangerTools", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = {x=10659,y=9570,z=-1},
        dist = {"CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction","MusicStoreCDs"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    {
        type = 'container',
        coords = {x=10660,y=9568,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {10,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = {x=10660,y=9567,z=-1},
        items = {
            { name = 'Base.Firewood', chance = 1, count = {10,10} },
            { name = 'Base.Twigs', chance = 1, count = {10,10} },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
}
for i = 1, #v15loot do
    MuldSafeHouse.loot[#MuldSafeHouse.loot + 1] = v15loot[i]
end

local v14wtc = {x = 10665, y = 9562, z = -1}

MuldSafeHouse.overrides = {
    [1] = {
        version = 14,
        loot = v14loot,
        waterTanks = {
            { sprite = "industry_02_72", x = v14wtc.x, y = v14wtc.y, z = v14wtc.z, isProp = true, sourceType="generator", source = {x = 12049, y = 2578, z = 0} },
        },
        objectSpawns = {
            { sprite = "industry_02_64", x = 10666, y = 9562, z = -1, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
            { sprite = "industry_02_68", x = 10666, y = 9561, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_65", x = 10667, y = 9562, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_69", x = 10667, y = 9561, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_66", x = 10668, y = 9562, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_70", x = 10668, y = 9561, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_67", x = 10669, y = 9562, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
            { sprite = "industry_02_71", x = 10669, y = 9561, z = -1, enabled = "EnableGenSystem", clearExisting = true, },

            { x = 10658, y = 9565, z = -1, clearExisting = true, },
            { x = 10658, y = 9564, z = -1, clearExisting = true, },
            { x = 10658, y = 9563, z = -1, clearExisting = true, },
            { x = 10658, y = 9562, z = -1, clearExisting = true, },
            { sprite = "rooftop_furniture_22", x = 10668, y = 9550, z = 0, }, -- exhaust vent
        },
        waterFixtures = {
            { sprite = "fixtures_sinks_01_32", x = 10658, y = 9566, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
            { sprite = "fixtures_sinks_01_16", x = 10656, y = 9557, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
            { sprite = "fixtures_bathroom_01_6", x = 10658, y = 9561, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        },
    },
}

return MuldSafeHouse