local wtc = {x = 10158, y = 6620, z = -1} -- waterTankCoords
local pb1 = { x = 10149, y = 6620, z = -1 }
local WWestPointSafeHouse = {
    spawn = { x = 10162, y = 6622, z = 1 },
    waterTanks = {
        { sprite = "dwap_tiles_01_8", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 10149, y = 6620, z = -1} },
    },
    waterFixtures = {
        { sprite = "appliances_laundry_01_3", x = 10157, y = 6622, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = 10157, y = 6620, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_29", x = 10155, y = 6626, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_2", x = 10155, y = 6627, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_11", x = 10162, y = 6631, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- 2nd floor
        { sprite = "fixtures_bathroom_01_0", x = 10152, y = 6625, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 10153, y = 6625, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 10154, y = 6625, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 10152, y = 6627, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_13", x = 10160, y = 6628, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_2", x = 10163, y = 6629, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_55", x = 10163, y = 6630, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement fixtures
        { sprite = "fixtures_sinks_01_35", x = 10156, y = 6621, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_33", x = 10146, y = 6631, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = 10146, y = 6635, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_6", x = 10148, y = 6631, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "W West Point Safe House",
        doors = {
            { sprite = "fixtures_doors_02_5", x = 10157, y = 6633, z = 0, },
            { sprite = "fixtures_doors_02_5", x = 10157, y = 6632, z = 0, },
            { sprite = "fixtures_doors_fences_01_21", x = 10156, y = 6608, z = 0, },
        },
    },
    map = { name = "DWAPStashMap8", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = pb1.x-1, y = pb1.y, z = pb1.z },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = pb1.x, y = pb1.y, z = pb1.z },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10143,
                        y = 6626,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10143,
                        y = 6627,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10143,
                        y = 6628,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10143,
                        y = 6629,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10145,
                        y = 6626,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10145,
                        y = 6627,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10145,
                        y = 6628,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 10145,
                        y = 6629,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                },
            },
            fakeGenerators = {
                { x = 10153, y = 6627, z = -1, createTile = true },
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },
        { sprite = "trashcontainers_01_24", x = 10150, y = 6626, z = 0, enabled = "Loot", },

        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_5", x = 10157, y = 6633, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_9", x = 10160, y = 6632, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_9", x = 10162, y = 6632, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_25", x = 10161, y = 6620, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_73", x = 10153, y = 6620, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_72", x = 10149, y = 6623, z = 0, },
    },
    loot = {
        { -- cabinet next to bunk beds
            type = 'container',
            coords = {x=10146,y=6637,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=10146,y=6636,z=-1+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=10146,y=6636,z=-1},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=10146,y=6635,z=-1+0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=10146,y=6635,z=-1},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=10146,y=6634,z=-1+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=10146,y=6634,z=-1},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { --crates by shower
            type = 'container',
            coords = {x=10146,y=6633,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { --crates by shower
            type = 'container',
            coords = {x=10146,y=6632,z=-1},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10148,y=6632,z=-1},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10148,y=6633,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10148,y=6634,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- mil locker
            type = 'container',
            coords = {x=10148,y=6638,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- mil locker
            type = 'container',
            coords = {x=10148,y=6639,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- "bunker" entryway
        {
            type = 'container',
            coords = {x=10148,y=6627,z=-1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=10148,y=6628,z=-1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=10148,y=6629,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=10148,y=6630,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=10146,y=6629,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=10146,y=6630,z=-1},
            dist = {"SewingStoreTools", "CrateLeather", "SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },

        -- main basement
        {
            type = 'container',
            coords = {x=10158,y=6622,z=-1},
            dist = {"FreezerRich", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10156,y=6622,z=-1},
            dist = {"FridgeFarmStorage", "FridgeGeneric", "SushiKitchenFridge"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10156,y=6623,z=-1},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10156,y=6624,z=-1},
            dist = {"SpiffosKitchenFridge", "SpiffosKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10150,y=6626,z=-1},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10151,y=6626,z=-1},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10152,y=6626,z=-1},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10153,y=6626,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10156,y=6619,z=-1},
            dist = {"CrateTools", "GarageTools", "BarnTools", "WeldingWorkshopTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10157,y=6619,z=-1},
            dist = {"GigamartTools", "JanitorTools", "WeldingWorkshopTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10159,y=6622,z=-1},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

        -- first floor
        {
            type = 'container',
            coords = {x=10150,y=6626,z=0},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10151,y=6620,z=0},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10155,y=6620,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10155,y=6622,z=0},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10150,y=6625,z=0},
            items = {
                { name = 'Base.Remote', chance = 1, count = {1,1} },
                { name = 'Base.VideoGame', chance = 1, count = {1,1} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 1, count = {30,30} },
            },
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10154,y=6630,z=0.5},
            dist = {"CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10159,y=6630,z=0.5},
            dist = { "GunStoreKnives", "CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10160,y=6631,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10161,y=6631,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10162,y=6631,z=0},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10163,y=6631,z=0},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10163,y=6629,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10163,y=6628,z=0},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10163,y=6627,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        -- laundry room
        {
            type = 'container',
            coords = {x=10157,y=6621,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10157,y=6620,z=0},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        -- 2nd floor
        {
            type = 'container',
            coords = {x=10163,y=6627,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10163,y=6626,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10160,y=6629,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10160,y=6630,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10153,y=6625,z=1},
            dist = {"BathroomCounter","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10154,y=6625,z=1},
            dist = {"CrateLinens", "ArmyStorageAmmunition", "SafehouseTraps",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10153,y=6631,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10151,y=6626,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10155,y=6620,z=1},
            dist = {"CrateLeather", "SewingStoreFabric", "SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10155,y=6621,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10153,y=6620,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10150,y=6625,z=1.5},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(WWestPointSafeHouse.objectSpawns, { sprite = "industry_trucks_01_14", x = 10146, y = 6628, z = -1, removeWall = "west" })
    table.insert(WWestPointSafeHouse.objectSpawns, { sprite = "fixtures_doors_frames_01_4", x = 10146, y = 6628, z = -1, })
    table.insert(WWestPointSafeHouse.objectSpawns, { sprite = "fixtures_doors_01_56", x = 10146, y = 6628, z = -1, isDoor = true, doorN = false, })
    table.insert(WWestPointSafeHouse.objectSpawns, { x = 10143, y = 6679, z = 0, removeFloor = true, })
    -- table.insert(WWestPointSafeHouse.generators[1].chunks, { 1267, 828 })
    -- table.insert(WWestPointSafeHouse.generators[1].chunks, { 1267, 829 })
    -- table.insert(WWestPointSafeHouse.generators[1].chunks, { 1267, 830 })
    -- table.insert(WWestPointSafeHouse.generators[1].chunks, { 1267, 831 })
    -- table.insert(WWestPointSafeHouse.generators[1].chunks, { 1268, 828 })
end

return WWestPointSafeHouse