local wtc = {x = 12980, y = 1920, z = 0} -- waterTankCoords
local pb1 = { x = 12981, y = 1922, z = -1 }
local bunkerTopLeft = {x = 12981, y = 1907, z = -1}
local LowryCourt = {
    spawn = { x = 12993, y = 1914, z = 2 },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 12989, y = 1912, z = 0} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_8", x = 12989, y = 1912, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_21", x = 12996, y = 1912, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 12996, y = 1911, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12998, y = 1911, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_10", x = 12986, y = 1912, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_13", x = 12987, y = 1913, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_55", x = 12988, y = 1911, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 12987, y = 1912, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_9", x = 12976, y = 1914, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_29", x = 12978, y = 1918, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_2", x = 12978, y = 1919, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_55", x = 12978, y = 1920, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_6", x = 12983, y = 1915, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = 12981, y = 1911, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Lowry Court",
        doors = {
            { sprite = "fixtures_doors__fences_01_21", x = 12995, y = 1924, z = 0, },
            { sprite = "fixtures_doors__fences_01_21", x = 12995, y = 1923, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 12993, y = 1909, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 12992, y = 1909, z = 0, },
            { sprite = "fixtures_doors_01_57", x = 12994, y = 1911, z = 2, },
        },
    },
    map = { name = "DWAPStashMap9", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 12989, y = 1912, z = 0, },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = pb1.x, y = pb1.y, z = pb1.z, spawn = false, },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12984,
                        y = 1905,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12984,
                        y = 1904,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12984,
                        y = 1903,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12986,
                        y = 1905,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12986,
                        y = 1904,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 12986,
                        y = 1903,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                },
            },
            fakeGenerators = {
                -- { x = 12983, y = 1920, z = -1, createTile = true },
                -- { x = 12984, y = 1916, z = -1, createTile = true },
                { x = 12985, y = 1916, z = -1, createTile = false },
                -- { x = 12992, y = 1924, z = 3, createTile = false },
                { x = 12989, y = 1915, z = 3, createTile = false },
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_57", x = 12989, y = 1923, z = 2, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_57", x = 12994, y = 1924, z = 2, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_57", x = 12998, y = 1924, z = 2, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_57", x = 13002, y = 1924, z = 2, },

        { sprite = "appliances_cooking_01_16", x = 12989, y = 1915, z = 2, isFireplace = true, },
    },
    loot = {
        {
            type = 'container',
            coords = {x = 12983, y = 1919, z = 0},
            dist = {"CrateLumber", "CrateSheetMetal","ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 12984, y = 1919, z = 0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- extra spawns
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y,z=bunkerTopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+1,z=bunkerTopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 12984, y = 1920, z = 0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },

        -- 2nd floor
        {
            type = 'container',
            coords = {x=12995,y=1911,z=2.5},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools", "WeldingWorkshopTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12991,y=1911,z=2},
            dist = {"GigamartTools", "JanitorTools", "WeldingWorkshopTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12992,y=1911,z=2},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_ToolsLevel",
        },

        {
            type = 'container',
            coords = {x=12993,y=1922,z=2},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12992,y=1916,z=2},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12996,y=1923,z=2},
            items = {
                { name = 'Base.Remote', chance = 1, count = {1,1} },
                { name = 'Base.VideoGame', chance = 1, count = {1,1} },
                { name = 'Base.Headphones', chance = 1, count = {1,1} },
                { name = 'Base.CDplayer', chance = 1, count = {1,1} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 1, count = {30,30} },
            },
        },
        {
            type = 'container',
            coords = {x=12989,y=1919,z=2},
            dist = {"CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12990,y=1919,z=2},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=12989,y=1922,z=2},
            dist = { "GunStoreKnives",  "PawnShopKnives","CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12992,y=1923,z=2},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12990,y=1911,z=2},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12989,y=1911,z=2},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12989,y=1912,z=2},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12989,y=1913,z=2},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13002,y=1911,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13003,y=1911,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12996,y=1913,z=2},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=13002,y=1919,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13000,y=1920,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13000,y=1923,z=2},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12996,y=1912,z=2},
            dist = {"CrateLeather", "SewingStoreFabric", "SewingStoreTools", "BathroomCounter",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        -- {
        --     type = 'container',
        --     coords = {x=10155,y=6621,z=1},
        --     dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_LockersLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x=10153,y=6620,z=1},
        --     dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
        --     distIncludeJunk = false,
        --     randUntilFull = true,
        --     level = "Loot_MediaLevel",
        -- },
        {
            type = 'container',
            coords = {x=13003,y=1919,z=2},
            dist = {"FirearmWeapons_Late", "SafehouseTraps", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(LowryCourt.objectSpawns, { x = 12939, y = 1933, z = 0, removeFloor = true, })
    table.insert(LowryCourt.objectSpawns, { sprite = "walls_interior_house_04_16", x = 12940, y = 1933, z = 0, })

    table.insert(LowryCourt.generators[1].fakeGenerators, { x = 12951, y=1931, z = -4, createTile = false })
end

return LowryCourt