local wtc = { x = 2051, y = 5692, z = -1 } -- waterTankCoords
local pb1 = { x = 2057, y = 5690, z = -1 }
local PSDelilah = {
    group = "Brandenburg",
    baseBuildings = {
        { x = 2037, y = 5686, z = 2 }, -- riverboat
        { x = 2043, y = 5708, z = 0 }, -- ticket building/office
    },
    spawn = { x = 2037, y = 5686, z = 2 },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType = "generator", source = { x = pb1.x - 1, y = pb1.y, z = pb1.z } },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_9",     x = 2037, y = 5684, z = 2,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        { sprite = "fixtures_sinks_01_13",    x = 2035, y = 5692, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_5",  x = 2035, y = 5691, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_5",  x = 2035, y = 5685, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_13",    x = 2035, y = 5684, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        { sprite = "fixtures_sinks_01_32",    x = 2042, y = 5693, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        { sprite = "fixtures_sinks_01_34",    x = 2061, y = 5689, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_7",  x = 2036, y = 5693, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_28",    x = 2035, y = 5693, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_7",  x = 2034, y = 5693, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_28",    x = 2033, y = 5693, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_4",  x = 2036, y = 5683, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_12",    x = 2035, y = 5683, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_4",  x = 2034, y = 5683, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_12",    x = 2033, y = 5683, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        { sprite = "fixtures_sinks_01_31",    x = 2034, y = 5687, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_32", x = 2035, y = 5686, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 2036, y = 5686, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
    },
    doorKeys = {
        name = "P.S. Delilah Key",
        doors = {
            { sprite = "fixtures_doors_02_5",  x = 2048, y = 5693, z = 0, },
            { sprite = "fixtures_doors_02_5",  x = 2043, y = 5707, z = 0, },
            { sprite = "fixtures_doors_01_33", x = 2041, y = 5692, z = 2, },
        },
    },
    map = { name = "DWAPStashMap11", },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 2059, y = 5690, z = -1, },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 2061, y = 5690, z = -1, },
            fakeGenerators = {
                { x = 2046, y = 5693, z = -1, createTile = false },
            },
        },
    },
    objectSpawns = {
        { barricade = "metalbar", enabled = "Barricade", target = "walls_commercial_01_41",     x = 2040, y = 5693, z = 2, },
        { barricade = "metalbar", enabled = "Barricade", target = "walls_commercial_01_41",     x = 2036, y = 5693, z = 2, },
        -- { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_41", x = 2040, y = 5684, z = 2, },
        -- { barricade = "metalbar", enabled = "Barricade", target="walls_commercial_01_41", x = 2036, y = 5684, z = 2, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_01_41", x = 2043, y = 5711, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2043, y = 5694, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2045, y = 5694, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2050, y = 5694, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2052, y = 5694, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2053, y = 5694, z = 0, },
        { barricade = "wood",     enabled = "Barricade", target = "walls_exterior_house_03_19", x = 2055, y = 5694, z = 0, },
    },
    loot = {
        -- command deck
        { -- E1
            note = "metal_shelves @ office",
            coords = { x = 2040, y = 5684, z = 2 },
            special = "essentials",
        },
        { -- E2
            note = "crate @ office",
            coords = { x = 2035, y = 5684, z = 2 },
            dist = { "KitchenDryFood" },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E3
            note = "crate @ office",
            coords = { x = 2035, y = 5684, z = 2 },
            stack = 2,
            dist = { "KitchenDryFood" },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E4
            note = "counter @ office",
            coords = { x = 2037, y = 5684, z = 2 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E5
            note = "counter @ office",
            coords = { x = 2037, y = 5684, z = 2 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPFish",
        },
        { -- E6
            note = "militarycrate @ office",
            coords = { x = 2036, y = 5684, z = 2 },
            dist = { "FirearmWeapons_Late", },
            distIncludeJunk = false,
            tag = "DWAPGun",
        },
        { -- E7
            note = "militarycrate @ office",
            coords = { x = 2036, y = 5684, z = 2 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPGun",
        },
        { -- E8
            note = "counter @ office",
            coords = { x = 2035, y = 5687, z = 2 },
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E9
            note = "counter @ office",
            coords = { x = 2035, y = 5689, z = 2 },
            distIncludeJunk = false,
            tag = "DWAPMed",
        },
        { -- E10 change this to a firewood and starters container and put the tools elsewhere
            note = "counter @ office",
            coords = { x = 2038, y = 5684, z = 2 },
            slot = "upper",
            items = {
                { name = 'Base.Firewood', chance = 1, count = { 10, 10 } },
            },
            level = "Loot_FarmLevel",
        },
        { -- E11
            note = "counter @ office",
            coords = { x = 2035, y = 5692, z = 2 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E12
            note = "counter @ office",
            coords = { x = 2039, y = 5684, z = 2 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E13
            note = "crate @ office",
            coords = { x = 2040, y = 5687, z = 2 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        {                            -- E14
            note = "crate @ office", -- @TODO overkill, rebalance with different loot.
            coords = { x = 2040, y = 5687, z = 2 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E15
            note = "counter @ office",
            coords = { x = 2039, y = 5684, z = 2 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E16
            note = "counter @ office",
            coords = { x = 2039, y = 5685, z = 2 },
            dist = { "CampingStoreLighting" },
            distIncludeJunk = false,
            tag = "DWAPFarm",
        },
        { -- E17
            note = "metal_shelves @ office",
            coords = { x = 2040, y = 5685, z = 2 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E18
            note = "crate @ office",
            coords = { x = 2039, y = 5687, z = 2 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E19
            note = "crate @ office",
            coords = { x = 2039, y = 5687, z = 2 },
            stack = 2, -- @TODO overkill, rebalance with different loot.
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E20 @TODO change
            note = "crate @ office",
            coords = { x = 2041, y = 5687, z = 2 },
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        {                                           -- E21
            note = "crate @ office",
            coords = { x = 2041, y = 5687, z = 2 }, -- @TODO overkill, rebalance with different loot.
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        { -- E22
            note = "counter @ office",
            coords = { x = 2039, y = 5689, z = 2 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E23
            note = "counter @ office",
            coords = { x = 2040, y = 5689, z = 2 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- E24
            note = "counter @ office",
            coords = { x = 2041, y = 5689, z = 2 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E25
            note = "counter @ office",
            coords = { x = 2035, y = 5686, z = 2 },
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E26
            note = "counter @ office",
            coords = { x = 2035, y = 5685, z = 2 },
            distIncludeJunk = false,
            tag = "DWAPLockers",
        },

        -- middle deck bar area (z=1)
        { -- E27
            note = "counter @ bar",
            coords = { x = 2044, y = 5689, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        { -- E28
            note = "counter @ bar",
            coords = { x = 2044, y = 5690, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E29
            note = "counter @ bar",
            coords = { x = 2044, y = 5691, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E30
            note = "counter @ bar",
            coords = { x = 2044, y = 5693, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E31
            note = "shelves @ bar",
            coords = { x = 2042, y = 5690, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E32
            note = "shelves @ bar",
            coords = { x = 2042, y = 5691, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPBooze",
        },
        { -- E33
            note = "shelves @ bar",
            coords = { x = 2042, y = 5692, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPBooze",
        },
        { -- E34
            note = "counter @ bar",
            coords = { x = 2044, y = 5692, z = 1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },

        -- main deck (mostly kitchen) (z=0)
        { -- E35
            note = "counter @ restaurantkitchen",
            coords = { x = 2061, y = 5684, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E36
            note = "counter @ restaurantkitchen",
            coords = { x = 2061, y = 5685, z = 0 },
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E37
            note = "counter @ restaurantkitchen",
            coords = { x = 2061, y = 5686, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E38
            note = "counter @ restaurantkitchen",
            coords = { x = 2061, y = 5687, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E39
            note = "counter @ bar",
            coords = { x = 2046, y = 5692, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        -- {
        --     type = 'container',
        --     coords = {x=2046,y=5693,z=0},
        -- },

        -- ticket office
        { -- E40
            note = "desk @ office",
            coords = { x = 2043, y = 5710, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E41
            note = "counter @ office",
            coords = { x = 2044, y = 5710, z = 0 },
            dist = { "GasStoreEmergency" },
            distIncludeJunk = true,
            level = 2,
        },
        { -- E42
            note = "counter @ office",
            coords = { x = 2044, y = 5709, z = 0 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            level = "Loot_BuildMatsLevel",
        },
        { -- E43
            note = "fridge @ restaurantkitchen",
            coords = { x = 2061, y = 5690, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFridge",
        },
        { -- E44
            note = "freezer @ restaurantkitchen",
            coords = { x = 2061, y = 5690, z = 0 },
            slot = "freezer",
            distIncludeJunk = true,
            tag = "DWAPFreezer",
        },
        { -- E45
            note = "counter @ office",
            coords = { x = 2044, y = 5708, z = 0 },
            dist = { "WeldingWorkshopMetal" },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E46
            note = "counter @ office",
            coords = { x = 2044, y = 5707, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },

        -- below decks (z=-1)
        { -- E47
            note = "crate @ bedroom",
            coords = { x = 2033, y = 5686, z = -1 },
            stack = 1,
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E48
            note = "desk @ bedroom",
            coords = { x = 2031, y = 5690, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E49
            note = "metal_shelves @ janitor",
            coords = { x = 2042, y = 5692, z = -1 },
            slot = "upper",
            dist = { "SewingStoreTools" },
            distIncludeJunk = true,
            tag = "DWAPTailor",
        },
        { -- E50
            note = "metal_shelves @ janitor",
            coords = { x = 2042, y = 5684, z = -1 },
            slot = "upper",
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E51
            note = "smallbox @ restaurantkitchen",
            coords = { x = 2037, y = 5689, z = -1 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.Sheet', },
                { name = 'Base.WoodAxe', },
                { name = 'Base.Machete', },
            },
            level = "Loot_BuildMatsLevel",
        },
        { -- E52
            note = "fridge @ restaurantkitchen",
            coords = { x = 2037, y = 5691, z = -1 },
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E53
            note = "freezer @ restaurantkitchen",
            coords = { x = 2037, y = 5691, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E54
            note = "fridge @ restaurantkitchen",
            coords = { x = 2038, y = 5691, z = -1 },
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E55
            note = "freezer @ restaurantkitchen",
            coords = { x = 2038, y = 5691, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E56
            note = "fridge @ restaurantkitchen",
            coords = { x = 2039, y = 5691, z = -1 },
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E57
            note = "freezer @ restaurantkitchen",
            coords = { x = 2039, y = 5691, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E58
            note = "fridge @ restaurantkitchen",
            coords = { x = 2037, y = 5685, z = -1 },
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E59
            note = "freezer @ restaurantkitchen",
            coords = { x = 2037, y = 5685, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E60
            note = "freezer @ restaurantkitchen",
            coords = { x = 2038, y = 5685, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E61
            note = "freezer @ restaurantkitchen",
            coords = { x = 2039, y = 5685, z = -1 },
            slot = "freezer",
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFreezer",
        },
        { -- E62
            note = "fridge @ restaurantkitchen",
            coords = { x = 2038, y = 5685, z = -1 },
            dist = { "FreezerRich", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E63
            note = "fridge @ restaurantkitchen",
            coords = { x = 2039, y = 5685, z = -1 },
            dist = { "FreezerIceCream", },
            distIncludeJunk = false,
            tag = "DWAPFridge",
        },
        { -- E64
            note = "crate @ janitor",
            coords = { x = 2044, y = 5692, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E65
            note = "crate @ janitor",
            coords = { x = 2044, y = 5692, z = -1 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E66
            note = "crate @ janitor",
            coords = { x = 2043, y = 5692, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E67
            note = "crate @ janitor",
            coords = { x = 2043, y = 5692, z = -1 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        --     note = "crate @ janitor",
        --     dist = { "SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer" },
        --     distIncludeJunk = false,
        --     randUntilFull = true,
        --     level = "Loot_FoodLevel",

        --     note = "locker @ bedroom",
        --     dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy" },
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_LockersLevel",

        --     note = "crate @ bedroom",
        --     dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
        --     distIncludeJunk = false,
        --     randUntilFull = true,
        --     level = "Loot_FarmLevel",
        { -- E68
            note = "crate @ bedroom",
            coords = { x = 2034, y = 5686, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPGun",
        },
        { -- E69
            note = "crate @ bedroom",
            coords = { x = 2034, y = 5686, z = -1 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPGun",
        },
        { -- E70
            note = "militarylocker @ bedroom",
            coords = { x = 2033, y = 5690, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E71
            note = "locker @ bedroom",
            coords = { x = 2032, y = 5686, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E72
            note = "metal_shelves @ bedroom",
            coords = { x = 2034, y = 5690, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E73
            note = "metal_shelves @ bedroom",
            coords = { x = 2034, y = 5689, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E74
            note = "crate @ bedroom",
            coords = { x = 2033, y = 5686, z = -1 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E75
            note = "metal_shelves @ bedroom",
            coords = { x = 2036, y = 5690, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E76 @TODO duplicate coords with entry 41
            note = "metal_shelves @ bedroom",
            coords = { x = 2036, y = 5689, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E77 medicine cabinet
            note = "medicine @ bathroom",
            coords = { x = 2036, y = 5686, z = -1 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPMed",
        },

    },
}

return PSDelilah
