local generatorStartCoords = { x = 751, y = 9812, z = -5, }
local wtc = { x = generatorStartCoords.x+8, y = generatorStartCoords.y+4, generatorStartCoords.z, }
local EkronCC = {
    spawn = { x = 764, y = 9821, z = -5, },
    doorKeys = {
        name = "Ekron Community College",
        doors = {
            { sprite = "fixtures_doors_01_56", x = 733, y = 9818, z = -1, }, -- storage room door
            { sprite = "fixtures_doors_01_54", x = generatorStartCoords.x+3, y = generatorStartCoords.y+9, generatorStartCoords.z, },
        },
    },
    map = { name = "DWAPStashMap12", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = generatorStartCoords.x, y = generatorStartCoords.y, generatorStartCoords.z, },
            chunks = {
                {90, 1227},
                {91, 1227},
                {92, 1227},
                {93, 1227},
                {93, 1225},
                {93, 1226},
                {93, 1228},
                {93, 1229},
                {94, 1224},
                {94, 1225},
                {94, 1226},
                {94, 1227},
                {94, 1228},
                {94, 1229},
                {94, 1230},
                {95, 1225},
                {95, 1226},
                {95, 1227},
                {95, 1228},
                {95, 1229},
                {95, 1230},
                {96, 1225},
                {96, 1226},
                {96, 1227},
                {96, 1228},
                {96, 1229},
                {97, 1225},
                {97, 1226},
                {97, 1227},
                {97, 1228},
                {97, 1229},
                {98, 1226},
                {98, 1227},
                {98, 1228},
            },
        }
    },
    waterTanks = {
        { sprite = "industry_02_72", x = wtc.x, y = wtc.y, z = wtc.z, },
    },
    waterFixtures = {
        -- wash room sinks
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y-12, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y-13, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y-14, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y-15, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- wash room toilets
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y-11, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y-12, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y-13, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y-14, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y-15, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- laundry room washers
        { sprite = "appliances_laundry_01_6", x = generatorStartCoords.x+13, y = generatorStartCoords.y-15, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_6", x = generatorStartCoords.x+14, y = generatorStartCoords.y-15, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- kitchen sink
        { sprite = "fixtures_sinks_01_17", x = generatorStartCoords.x+20, y = generatorStartCoords.y-6, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- utility sink
        { sprite = "fixtures_sinks_01_34", x = generatorStartCoords.x+23, y = generatorStartCoords.y+23, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- gym fountain
        { sprite = "fixtures_sinks_01_24", x = generatorStartCoords.x+15, y = generatorStartCoords.y+20, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- laundry room washers
        { sprite = "appliances_laundry_01_6", x = generatorStartCoords.x+13, y = generatorStartCoords.y+27, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_6", x = generatorStartCoords.x+14, y = generatorStartCoords.y+27, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- wash room sinks
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y+24, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y+25, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y+26, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_6", x = generatorStartCoords.x+9, y = generatorStartCoords.y+27, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- wash room toilets
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y+27, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_5", x = generatorStartCoords.x+5, y = generatorStartCoords.y+26, generatorStartCoords.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    objectSpawns = {
        { sprite = "fixtures_railings_01_36", x = 725, y = 9819, z = -1, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 725, y = 9820, z = -1, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 725, y = 9821, z = -1, clearExisting = true, },
        { x = 725, y = 9822, z = -1, clearExisting = true, },

        -- { sprite = "constructedobjects_01_45", x = 12994, y = 1908, z = 2, clearExisting = false, isContainer = true, },
        -- { sprite = "appliances_cooking_01_16", x = 12989, y = 1915, z = 2, },
    },
    loot = {
        {
            -- filingcabinet next to spawn in operations room
            type = 'container',
            coords = {x=generatorStartCoords.x+12,y=generatorStartCoords.y+11,z=-4},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        {
            -- 2nd filingcabinet next to spawn in operations room
            type = 'container',
            coords = {x=generatorStartCoords.x+12,y=generatorStartCoords.y+12,z=-4},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+20,y=generatorStartCoords.y-6,z=-4},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y-6,z=-4},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+16,y=generatorStartCoords.y-6,z=-4},
            dist = {"CrateCannedFood",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+16,y=generatorStartCoords.y-4,z=-4},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+15,y=generatorStartCoords.y-6,z=-4},
            dist = {"CrateCannedFood",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+17,y=generatorStartCoords.y-4,z=-4},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+18,y=generatorStartCoords.y-4,z=-4},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y-4,z=-4},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- Armory
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+27,y=generatorStartCoords.y-2,z=-4},
            dist = {"GunCache1.GunBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+28,y=generatorStartCoords.y-2,z=-4},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+29,y=generatorStartCoords.y-2,z=-4},
            dist = {"GunCache1.GunBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+30,y=generatorStartCoords.y-2,z=-4},
            dist = {"FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+27,y=generatorStartCoords.y+1,z=-4},
            dist = {"FirearmWeapons_Late",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+28,y=generatorStartCoords.y+1,z=-4},
            dist = {"DrugLabGuns"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+29,y=generatorStartCoords.y+1,z=-4},
            dist = {"ArmyStorageGuns",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+30,y=generatorStartCoords.y+1,z=-4},
            dist = {"PoliceStorageGuns"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- medical
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+22,y=generatorStartCoords.y+9,z=-4+0.5},
            dist = {"MedicalCabinet"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+22,y=generatorStartCoords.y+10,z=-4},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+10,z=-4},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- book shelves
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+33,y=generatorStartCoords.y+16,z=-4},
            dist = {"BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+33,y=generatorStartCoords.y+15,z=-4},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        -- media storage
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+26,y=generatorStartCoords.y+17,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = 'skillbooks2',
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+27,y=generatorStartCoords.y+17,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = 'skillbooks2',
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+28,y=generatorStartCoords.y+17,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = 'skillmags',
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+29,y=generatorStartCoords.y+17,z=-4},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.VHS_Retail', chance = 0.5, count = {30,30} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+30,y=generatorStartCoords.y+17,z=-4},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+31,y=generatorStartCoords.y+17,z=-4},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+28,y=generatorStartCoords.y+20,z=-4},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+29,y=generatorStartCoords.y+20,z=-4},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+30,y=generatorStartCoords.y+20,z=-4},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+31,y=generatorStartCoords.y+20,z=-4},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- cleaning
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+22,y=generatorStartCoords.y+17,z=-4},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+17,z=-4},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- seed/farm library
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+15,z=-4},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+16,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+21,y=generatorStartCoords.y+15,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+21,y=generatorStartCoords.y+16,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y+15,z=-4},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y+16,z=-4},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
        },
        -- fishing
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+12,z=-4},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- hunting
            type = 'container',
            coords = {x=generatorStartCoords.x+22,y=generatorStartCoords.y+12,z=-4},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+21,y=generatorStartCoords.y+12,z=-4},
            dist = {"CrateInstruments"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+20,y=generatorStartCoords.y+12,z=-4},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y+12,z=-4},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+18,y=generatorStartCoords.y+12,z=-4},
            dist = {"DishCabinetLiquor"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- tailoring
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+22,y=generatorStartCoords.y+21,z=-4},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+21,z=-4},
            dist = {"SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+22,z=-4},
            dist = {"CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y+21,z=-4},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+19,y=generatorStartCoords.y+22,z=-4},
            items = {
                { name = 'Base.Mov_WaterDispenser', chance = 1, count = {1,2} },
                { name = 'Base.WaterDispenserBottle', chance = 1, count = {1,2} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+23,z=-4},
            dist = {"GymLaundry", "GymLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+23,y=generatorStartCoords.y+24,z=-4},
            dist = {"ArmyStorageOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        -- laundry room
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+12,y=generatorStartCoords.y+27,z=-4+0.5},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+12,y=generatorStartCoords.y-15,z=-4+0.5},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        -- lockers
        -- SafehouseArmor
        -- SafehouseLighting
        -- ArmyStorageOutfit
        -- LockerArmyBedroom, LockerArmyBedroomHome, ArmySurplusOutfit, ToolStoreOutfit
        -- womens
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y-7,z=-4},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y-6,z=-4},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y-5,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y-4,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y-3,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- mens
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+21,z=-4},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+22,z=-4},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+23,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+24,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+25,z=-4},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- entry storage 1
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+11,z=-4},
            dist = {"CampingLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+12,z=-4},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+13,z=-4},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+14,z=-4},
            dist = {"SafehouseTraps", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+15,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+3,y=generatorStartCoords.y+16,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- tools
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+14,z=-4},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+15,z=-4},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+16,z=-4},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+17,z=-4},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+18,z=-4},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+6,y=generatorStartCoords.y+19,z=-4},
            dist = {"LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- random junk
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+12,z=-4},
            dist = {"CrateRandomJunk", "RandomFiller", "ArmySurplusMisc" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 3,
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+13,z=-4},
            dist = {"CrateCannedFood", "ArmySurplusTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+14,z=-4},
            dist = {"CrateRandomJunk", "RandomFiller" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 3,
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+15,z=-4},
            dist = {"CrateCannedFood", "RandomFiller" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- mats
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+16,z=-4},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+17,z=-4},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+19,z=-4},
            dist = {"ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x= generatorStartCoords.x+9,y=generatorStartCoords.y+18,z=-4},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- entry storage 2
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+13,z=-4},
            dist = {"ToolFactoryBarStock"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-2,y=generatorStartCoords.y+13,z=-4},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-1,y=generatorStartCoords.y+13,z=-4},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x,y=generatorStartCoords.y+13,z=-4},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+1,y=generatorStartCoords.y+13,z=-4},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+2,y=generatorStartCoords.y+13,z=-4},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x,y=generatorStartCoords.y+16,z=-4},
            items = {
                { name = 'Base.NailsCarton', chance = 1, count = {1,4} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-1,y=generatorStartCoords.y+16,z=-4},
            items = {
                { name = 'Base.NailsCarton', chance = 1, count = {1,4} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-2,y=generatorStartCoords.y+16,z=-4},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+16,z=-4},
            items = {
                { name = 'Base.CigaretteCarton', chance = 1, count = {5,15} },
            },
        },
        { -- duplicate to to top off the cartons
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+16,z=-4},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+2,y=generatorStartCoords.y+19,z=-4},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x+1,y=generatorStartCoords.y+19,z=-4},
            dist = {"CafeteriaSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x,y=generatorStartCoords.y+19,z=-4},
            dist = {"CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-1,y=generatorStartCoords.y+19,z=-4},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-2,y=generatorStartCoords.y+19,z=-4},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=generatorStartCoords.x-3,y=generatorStartCoords.y+19,z=-4},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
    },
}

return EkronCC