local wtc = {x = 12327, y = 1326, z = -1} -- waterTankCoords
local pb1 = { x = 12331, y = 1326, z = -1 }
local LVPawnshop = {
    spawn = { x = 12324, y = 1325, z = 0 },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 12331, y = 1326, z = -1}},
    },
    waterFixtures = {
        -- pawnshop proper
        { sprite = "fixtures_bathroom_01_5", x = 12329, y = 1327, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_15", x = 12329, y = 1328, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement
        { sprite = "fixtures_sinks_01_8", x = 12324, y = 1333, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_8", x = 12317, y = 1334, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 12317, y = 1336, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_33", x = 12315, y = 1336, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 12315, y = 1334, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_32", x = 12310, y = 1334, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_1", x = 12310, y = 1336, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- upstairs apts
        { sprite = "fixtures_sinks_01_8", x = 12328, y = 1330, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 12328, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12329, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 12330, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_8", x = 12322, y = 1330, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 12322, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12323, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 12324, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_10", x = 12321, y = 1330, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 12321, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12320, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 12319, y = 1327, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_sinks_01_8", x = 12310, y = 1328, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 12310, y = 1325, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 12311, y = 1325, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 12312, y = 1325, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

    },
    doorKeys = {
        name = "Pawnshop",
        doors = {
            { sprite = "fixtures_doors_02_5", x = 12318, y = 1335, z = 0, },
            { sprite = "fixtures_doors_01_33", x = 12332, y = 1331, z = 0, },
            { sprite = "fixtures_doors_02_5", x = 12332, y = 1327, z = 1, },
            { sprite = "fixtures_doors_01_33", x = 12322, y = 1334, z = -1, },
        },
    },
    map = { name = "DWAPStashMap13", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = pb1.x-1, y = pb1.y, z = pb1.z },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = pb1.x, y = pb1.y, z = pb1.z },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12320,
                        y = 1334,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12321,
                        y = 1334,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12322,
                        y = 1334,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12323,
                        y = 1334,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12320,
                        y = 1332,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12321,
                        y = 1332,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12322,
                        y = 1332,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12323,
                        y = 1332,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                },
            },
            fakeGenerators = {
                { x = 12326, y = 1337, z = -1, createTile = false },
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12311, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12312, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12314, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12315, y = 1337, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_01_49", x = 12318, y = 1336, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12321, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12322, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12324, y = 1337, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_41", x = 12325, y = 1337, z = 0, },
    },
    loot = {
        -- basement
        -- kitchen/rec room
        { -- trash box by entry
            type = 'container',
            coords = {x=12330,y=1329,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=12328,y=1329,z=-1},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12327,y=1329,z=-1},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1331,z=-1},
            dist = {"Homesteading",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1331,z=-0.5},
            dist = {"GigamartCrisps", "SafehouseFireplace"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1332,z=-1},
            dist = {"CrateCannedFood", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1332,z=-0.5},
            dist = {"GigamartBakingMisc","CrateFlour", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1333,z=-1},
            dist = {"GigamartDryGoods"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1333,z=-0.5},
            dist = { "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1334,z=-1},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1334,z=-0.5},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- fridge
            type = 'container',
            coords = {x=12324,y=1336,z=-1},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- bookcases
            type = 'container',
            coords = {x=12331,y=1335,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=12331,y=1334,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=12331,y=1333,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- armory
        {
            type = 'container',
            coords = {x=12323,y=1334,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12323,y=1335,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12323,y=1336,z=-1},
            dist = {"GunStoreGuns","GunStoreMagsAmmo", "GunStoreAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- bunk room 1
        {
            type = 'container',
            coords = {x=12320,y=1336,z=-1},
            dist = { "GunStoreKnives", "CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1336,z=-1},
            dist = {"FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=12318,y=1334,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- bathroom
        {
            type = 'container',
            coords = {x=12315,y=1334,z=-1},
            dist = {"TestingLab","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12315,y=1334,z=-0.5},
            dist = {"MedicalCabinet","BathroomCounter"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- bunk room
        {
            type = 'container',
            coords = {x=12312,y=1334,z=-1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1334,z=-0.5},
            dist = {"MedicalCabinet", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1336,z=-1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- laundry room
        {
            type = 'container',
            coords = {x=12310,y=1335,z=-1},
            dist = {"SewingStoreTools", "LaundryCleaning", "GymLaundry", "GymLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        -- warehouse
        {
            type = 'container',
            coords = {x=12323,y=1328,z=-1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=12323,y=1327,z=-1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- freezer
            type = 'container',
            coords = {x=12323,y=1325,z=-1},
            dist = {"WesternKitchenFreezer", "WesternKitchenFridge", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- freezer
            type = 'container',
            coords = {x=12322,y=1325,z=-1},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- freezer
            type = 'container',
            coords = {x=12321,y=1325,z=-1},
            dist = {"ArenaKitchenFreezer", "SushiKitchenFreezer",},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12320,y=1325,z=-1},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1325,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- metal shelves
            type = 'container',
            coords = {x=12317,y=1326,z=-1},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12316,y=1326,z=-1},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1326,z=-1},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12313,y=1326,z=-1},
            dist = {"MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- wood crates
            type = 'container',
            coords = {x=12320,y=1327,z=-1},
            dist = {"CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1327,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves
            type = 'container',
            coords = {x=12317,y=1328,z=-1},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12316,y=1328,z=-1},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1328,z=-1},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12313,y=1328,z=-1},
            dist = {"CrateGravelBags", "CrateSandBags", "CrateClayBags"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- cardboardboxes
            type = 'container',
            coords = {x=12320,y=1329,z=-1},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1329,z=-1},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- cardboardboxes
            type = 'container',
            coords = {x=12320,y=1330,z=-1},
            dist = {"GigamartCrisps","GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1330,z=-1},
            dist = {"CrateToiletPaper" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- metal shelves
            type = 'container',
            coords = {x=12317,y=1330,z=-1},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12316,y=1330,z=-1},
            dist = {"CrateSheetMetal", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1330,z=-1},
            dist = {"ToolFactoryBarStock", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12313,y=1330,z=-1},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- metal shelves
            type = 'container',
            coords = {x=12320,y=1332,z=-1},
            dist = {"StoreShelfDrinks", "CrateCannedFood", "CrateSodaBottles", "CandyStoreSnacks", "CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1332,z=-1},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12317,y=1332,z=-1},
            dist = { "CrateOilOlive", "CrateOilVegetable", "BakeryKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12316,y=1332,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12314,y=1332,z=-1},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12313,y=1332,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- Pawnshop
        {
            type = 'container',
            coords = {x=12321,y=1327,z=0},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12319,y=1327,z=0},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- closet
            type = 'container',
            coords = {x=12330,y=1329,z=0.5},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- pawnshop gun room
        {
            type = 'container',
            coords = {x=12328,y=1329,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12329,y=1329,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- pawnshop proper
        {
            type = 'container',
            coords = {x=12333,y=1332,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12321,y=1331,z=0},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=12332,y=1332,z=0},
            dist = {"BathroomCounter","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=12331,y=1332,z=0},
            dist = {"ArmyStorageAmmunition", "SafehouseTraps", "GunStoreKnives",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12330,y=1332,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12310,y=1325,z=0},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12311,y=1325,z=0},
            dist = {"CrateLeather", "SewingStoreFabric", "SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=12312,y=1325,z=0},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=12313,y=1325,z=0},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=12329,y=1336,z=0},
            dist = {"FirearmWeapons_Late", "SafehouseTraps", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12316,y=1325,z=0.5},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        {
            type = 'container',
            coords = {x=12317,y=1325,z=0.5},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=12318,y=1325,z=0.5},
            dist = {"CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12315,y=1325,z=0},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- storage room
        {
            type = 'container',
            coords = {x=12322,y=1327,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12322,y=1328,z=0},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12322,y=1330,z=0},
            dist = {"WeldingWorkshopMetal", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12322,y=1331,z=0},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1327,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1328,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1330,z=0},
            dist = {"ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1331,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller", "ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

        -- apts
        {
            type = 'container',
            coords = {x=12330,y=1329,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12329,y=1332,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=12328,y=1331,z=1},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12322,y=1331,z=1},
            dist = {"FreezerRich", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=12322,y=1336,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=12324,y=1329,z=1},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(LVPawnshop.objectSpawns, { sprite = "industry_trucks_01_49", x = 12322, y = 1313, z = -1, clearExisting = true, replaceWall= true, })
    table.insert(LVPawnshop.objectSpawns, { x = 12323, y = 1313, z = -1, clearExisting = true, })
    table.insert(LVPawnshop.objectSpawns, { x = 12324, y = 1313, z = -1, clearExisting = true, })
    table.insert(LVPawnshop.objectSpawns, { removeFloor = true, x = 12321, y = 1313, z = 0, })
    table.insert(LVPawnshop.objectSpawns, { sprite = "floors_interior_tilesandwood_01_31", x = 12323, y = 1313, z = 0, })
    table.insert(LVPawnshop.objectSpawns, { sprite = "floors_interior_tilesandwood_01_31", x = 12324, y = 1313, z = 0, })
end

return LVPawnshop