local wtc = {x = 13144, y = 3019, z = 0} -- waterTankCoords
local bunkerTopLeft = {x = 13135, y = 3019, z = -1}
local LVAutoshop = {
    spawn = { x = 13139, y = 3025, z = 0 },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, isProp = true, },
    },
    waterFixtures = {
        { sprite = "fixtures_bathroom_01_4", x = 13137, y = 3018, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_14", x = 13138, y = 3018, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_6", x = 13137, y = 3027, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = 13135, y = 3023, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Autoshop",
        doors = {
            { sprite = "fixtures_doors_fences_01_64", x = 13151, y = 3034, z = 0, },
            { sprite = "fixtures_doors_fences_01_21", x = 13150, y = 3024, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 13142, y = 3030, z = 0, },
            { sprite = "fixtures_doors_01_53", x = 13136, y = 3027, z = -1, },
            { sprite = "walls_garage_02_52", x = 13146, y = 3018, z = 0, },
        },
    },
    map = { name = "DWAPStashMap14", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 13141, y = 3032, z = 0, isProp = true, },
            chunks = {
                {1642, 376},
                {1642, 377},
                {1642, 378},
                {1643, 377},
                {1643, 378},
                {1642, 379},
                {1641, 377},
                {1641, 378},
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_72", x = 13143, y = 3019, z = 0, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank left
        { sprite = "industry_02_73", x = 13144, y = 3019, z = 0, enabled = "EnableWaterSystem", clearExisting = true, }, --tank right
        { sprite = "industry_02_74", x = 13143, y = 3018, z = 0, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back left
        { sprite = "industry_02_75", x = 13144, y = 3018, z = 0, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back right

        { sprite = "industry_02_64", x = 13138, y = 3032, z = 0, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
        { sprite = "industry_02_68", x = 13138, y = 3031, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_65", x = 13139, y = 3032, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_69", x = 13139, y = 3031, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_66", x = 13140, y = 3032, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_70", x = 13140, y = 3031, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_67", x = 13141, y = 3032, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_71", x = 13141, y = 3031, z = 0, enabled = "EnableGenSystem", clearExisting = true, },

        { x = 13137, y = 3030, z = 0, clearExisting = true, },
        { x = 13137, y = 3029, z = 0, clearExisting = true, },
        { x = 13137, y = 3028, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 13138, y = 3030, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 13138, y = 3029, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 13138, y = 3028, z = 0, clearExisting = true, },
        { x = 13137, y = 3027, z = 0, clearExisting = true, },
        { x = 13138, y = 3027, z = 0, clearExisting = true, },

        { sprite = "constructedobjects_01_45", x = 13138, y = 3030, z = 0, clearExisting = false, isContainer = true, },
        { sprite = "appliances_cooking_01_16", x = 13143, y = 3021, z = 0, isFireplace = true, },
        { sprite = "constructedobjects_01_45", x = 13142, y = 3014, z = 0, clearExisting = false, isContainer = true, },
    },
    loot = {
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            dist = {"GunCache1.GunBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },

        -- auto shop
        {
            type = 'container',
            coords = {x=13150,y=3018,z=0.5},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13143,y=3024,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13143,y=3025,z=0},
            items = {
                { name = 'Base.NailsCarton', chance = 1, count = {1,4} },
            },
        },
        {
            type = 'container',
            coords = {x=13143,y=3026,z=0},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
        },
        -- offices
        {
            type = 'container',
            coords = {x=13141,y=3026,z=0},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x=13142,y=3026,z=0},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=13137,y=3026,z=0},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
                { name = 'Base.Mov_Cot', chance = 1, count = {1,2} },
            },
        },
        { -- dupe
            type = 'container',
            coords = {x=13137,y=3026,z=0},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13139,y=3020,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13140,y=3020,z=0},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- lobby
        {
            type = 'container',
            coords = {x=13138,y=3016,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13138,y=3015,z=0},
            dist = {"CrateCannedFood", "ArmySurplusTools", "BedroomDresser" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13138,y=3014,z=0},
            dist = {"CandyStoreSnacks","CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13138,y=3013,z=0},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles","CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13142, y = 3014, z = 0},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- back storage room
        {
            type = 'container',
            coords = {x=13140,y=3030,z=0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        {
            type = 'container',
            coords = {x=13139,y=3030,z=0},
            items = {
                { name = 'Base.CigaretteCarton', chance = 1, count = {5,15} },
            },
        },
        { -- dupe
            type = 'container',
            coords = {x=13139,y=3030,z=0},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13139,y=3027,z=0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13140,y=3027,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13141,y=3027,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13142,y=3027,z=0},
            dist = {"ToolFactoryHandles", "ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13138, y = 3030, z = 0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

    },
}

return LVAutoshop