local wtc = {x = 1907, y = 9944, z = -1} -- waterTankCoords
local pb1 = { x = 1913, y = 9943, z = -1 }
-- local bunkerTopLeft = {x = 1895, y = 9946, z = -2}
local bunkerTopLeft = {x = 1917, y = 9934, z = -1}
local EkronLakeHouse = {
    group = "Ekron",
    baseBuildings = {
        { x = 1902, y = 9951, z = 1 }, -- lake house
        { x = 1904, y = 9955, z = -1 }, -- main basement
        { x = 1908, y = 9946, z = -1 }, -- generator/bunker addon
        { x = 1920, y = 9910, z = 0 }, -- parking shed
    },
    spawn = { x = 1902, y = 9951, z = 1 },
    waterTanks = {
        { sprite = "industry_02_75", x = 1898, y = 9964, z = -1, },
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 1911, y = 9944, z = -1} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_4", x = 1883, y = 9973, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_4", x = 1883, y = 9977, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_9", x = 1899, y = 9960, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_2", x = 1899, y = 9957, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_26", x = 1904, y = 9957, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 1904, y = 9956, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 1905, y = 9955, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement fixtures
        { sprite = "fixtures_sinks_01_35", x = 1900, y = 9965, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = bunkerTopLeft.x, y = bunkerTopLeft.y+4, z = bunkerTopLeft.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_6", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+8, z = bunkerTopLeft.z, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "East Ekron Lake House",
        doors = {
            { sprite = "fixtures_doors_01_44", x = 1906, y = 9956, z = 0, },
            { sprite = "fixtures_doors_01_44", x = 1891, y = 9974, z = 0, },
            { sprite = "fixtures_doors_01_56", x = 1921, y = 9910, z = 0, },
            { sprite = "fixtures_doors_01_28", x = 1946, y = 9942, z = 0, },
            { sprite = "fixtures_doors_01_56", x = 1851, y = 9953, z = 0, },
            { sprite = "fixtures_doors_01_56", x = 1907, y = 9946, z = 0, },
        },
    },
    map = { name = "DWAPStashMap15", },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 1911, y = 9944, z = pb1.z },
            fuelTank = { sprite = "dwap_tiles_01_24", x= 1909, y= 9944, z= -1, },
            fakeGenerators = {
                { x = 1908, y = 9948, z = -1, createTile = false },
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },
        -- { sprite = "walls_exterior_house_02_19", x = 1906, y = 9949, z = -1, clearExisting = true, removeWall = "north", },
        -- { sprite = "floors_exterior_street_01_16", x = 1906, y = 9948, z = -1, isFloor = true, },
        -- { sprite = "walls_exterior_house_02_16", x = 1906, y = 9948, z = -1, },
        -- { sprite = "walls_exterior_house_02_16", x = 1907, y = 9948, z = -1, },

        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 1907, y = 9952, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_exterior_house_01_40", x = 1907, y = 9955, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_exterior_house_01_40", x = 1907, y = 9957, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 1907, y = 9960, z = 0, },
    },
    loot = {
        { -- E1 cabinet next to bunk beds (9365)
            note = "filingcabinet @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E2 upper
            sprite = 'location_trailer_02_23',
            note = "overhead @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            slot = "upper",
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E3 lower (66)
            note = "counter @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E4 upper
            sprite = 'location_trailer_02_23',
            note = "overhead @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            slot = "upper",
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E5 lower (67)
            sprite = 'location_trailer_02_19',
            note = "counter @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E6 upper
            sprite = 'location_trailer_02_23',
            note = "overhead @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            slot = "upper",
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E7 lower (68)
            sprite = 'location_trailer_02_19',
            note = "counter @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E8 metal shelves (70)
            sprite = 'location_trailer_02_23',
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E9 metal shelves (71)
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E10 next to inner door (9372)
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E11 (73)
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- E12 (9374)
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E13 far end next to stairs (9375)
            note = "metal_shelves @ bunker",
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            special = "essentials",
        },
        { -- E14
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E15
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            stack = 2,
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E16
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E17
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z},
            stack = 2,
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E18
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E19
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            stack = 2,
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- extra spawns
        { -- E20
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y,z=bunkerTopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E21
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y,z=bunkerTopLeft.z},
            stack = 2,
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E22
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+1,z=bunkerTopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E23
            note = "militarycrate @ bunker",
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+1,z=bunkerTopLeft.z},
            stack = 2,
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },

        -- first basement
        { -- E24
            note = "freezer @ storage",
            coords = {x=1906,y=9957,z=-1},
            dist = {"FreezerRich", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E25
            note = "toolcabinet @ storage",
            coords = {x=1906,y=9954,z=-1},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        { -- E26
            note = "crate @ storage",
            coords = {x=1906,y=9953,z=-1},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E27
            note = "crate @ storage",
            coords = {x=1906,y=9951,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E28
            note = "metal_shelves @ storage",
            coords = {x=1902,y=9952,z=-1},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E29
            note = "metal_shelves @ storage",
            coords = {x=1902,y=9953,z=-1},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E30
            note = "metal_shelves @ storage",
            coords = {x=1898,y=9949,z=-1},
            dist = {"CrateTVWide", "CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E31
            note = "locker @ storage",
            coords = {x=1897,y=9949,z=-1},
            items = {
                { name = 'Base.CigaretteCarton', chance = 1, count = {5,15} },
            },
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E32
            note = "metal_shelves @ storage",
            coords = {x=1897,y=9962,z=-1},
            dist = {"CampingStoreTools", "ArmyHangarTools", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- first floor
        { -- E33
            note = "shelves @ livingroom",
            coords = {x=1900,y=9952,z=0},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E34
            note = "counter @ lobby",
            coords = {x=1902,y=9955,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E35
            note = "wardrobe @ lobby",
            coords = {x=1897,y=9959,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E36
            note = "wardrobe @ lobby",
            coords = {x=1897,y=9958,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E37
            note = "dresser @ lobby",
            coords = {x=1897,y=9955,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- laundry room
        { -- E38
            note = "metal_shelves @ laundry",
            coords = {x=1900,y=9955,z=0},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        { -- E39
            note = "metal_shelves @ laundry",
            coords = {x=1900,y=9956,z=0},
            dist = {"SewingStoreFabric", "SewingStoreTools", "GymLaundry", "GymLockers"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        -- office
        { -- E40
            note = "desk @ office",
            coords = {x=1904,y=9958,z=0},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        { -- E41
            note = "shelves @ office",
            coords = {x=1904,y=9960,z=0},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E42
            note = "shelves @ office",
            coords = {x=1904,y=9961,z=0},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E43
            note = "sidetable @ office",
            coords = {x=1904,y=9963,z=0},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- kitchen
        { -- E44
            note = "fridge @ kitchen",
            coords = {x=1897,y=9960,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E45
            note = "fridge @ kitchen",
            coords = {x=1897,y=9960,z=0},
            slot = "freezer",
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E46
            note = "shelves @ kitchen",
            coords = {x=1897,y=9965,z=0},
            slot = "upper",
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E47
            note = "overhead @ kitchen",
            coords = {x=1897,y=9964,z=0},
            slot = "upper",
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E48
            note = "counter @ kitchen",
            coords = {x=1897,y=9964,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E49
            note = "overhead @ kitchen",
            coords = {x=1897,y=9963,z=0},
            slot = "upper",
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E50
            note = "counter @ kitchen",
            coords = {x=1897,y=9963,z=0},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E51
            note = "counter @ kitchen",
            coords = {x=1898,y=9960,z=0},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            note = "counter @ kitchen",
            coords = {x=1898,y=9960,z=0},
            slot = "upper",
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E53
            note = "counter @ kitchen",
            coords = {x=1899,y=9960,z=0},
            dist = {"CandyStoreSnacks","StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E54
            note = "counter @ kitchen",
            coords = {x=1899,y=9960,z=0},
            slot = "upper",
            dist = {"CandyStoreSnacks","StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- living room
        { -- E55
            note = "counter @ livingroom",
            coords = {x=1905,y=9949,z=0},
            dist = {"CandyStoreSnacks","StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E56
            note = "counter @ livingroom",
            coords = {x=1906,y=9949,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E57
            note = "counter @ livingroom",
            coords = {x=1906,y=9950,z=0},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E58
            note = "counter @ livingroom",
            coords = {x=1906,y=9951,z=0},
            dist = {"CrateRandomJunk", "RandomFiller", "ArmySurplusMisc" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- 2nd floor
        { -- E59
            note = "shelves @ lobby",
            coords = {x=1900,y=9953,z=1},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E60
            note = "sidetable @ bedroom",
            coords = {x=1903,y=9963,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E61
            note = "sidetable @ bedroom",
            coords = {x=1900,y=9963,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E62
            note = "dishescabinet @ lobby",
            coords = {x=1902,y=9953,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E63
            note = "dishescabinet @ lobby",
            coords = {x=1903,y=9953,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E64
            note = "dresser @ kidsbedroom",
            coords = {x=1902,y=9949,z=1},
            dist = {"SafehouseArmor","LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E65
            note = "dresser @ kidsbedroom",
            coords = {x=1903,y=9949,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "SafehouseLighting", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E66
            note = "counter @ bathroom",
            coords = {x=1904,y=9956,z=1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(EkronLakeHouse.objectSpawns, { enabled = "EnableLadders", sprite = "industry_trucks_01_7", x = 1921, y = 9947, z = -1, removeWall = "west", })

    table.insert(EkronLakeHouse.objectSpawns, { enabled = "EnableLadders", sprite = "industry_railroad_05_8", x = 1921, y = 9911, z = 0, removeFloor = true, })
end

return EkronLakeHouse