local wtc = { x = 14556, y = 3044, z = -1 } -- waterTankCoords
local pb1 = { x = 14555, y = 3040, z = -1 } -- powerbankCoords
local ELVilleFarm = {
    group = "Louisville",
    baseBuildings = {
        { x = 14584, y = 3036, z = 1 },  -- farmhouse
        { x = 14571, y = 3035, z = -1 }, -- farmhouse basement
        { x = 14558, y = 3043, z = 0 },  -- barn
        { x = 14575, y = 3068, z = 0 },  -- shed
    },
    spawn = { x = 14584, y = 3036, z = 1 },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType = "generator", source = { x = 14556, y = 3041, z = 0 } },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_17",    x = 14576, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 14577, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_17",    x = 14585, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_19",    x = 14590, y = 3039, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "appliances_laundry_01_7", x = 14592, y = 3038, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        -- 2nd floor
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3043, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3042, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_2",  x = 14583, y = 3043, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_25", x = 14583, y = 3041, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_1",  x = 14581, y = 3038, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3037, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3036, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_26", x = 14582, y = 3035, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        -- basement fixtures
        { sprite = "fixtures_sinks_01_8",     x = 14566, y = 3033, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_8",     x = 14567, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_33", x = 14561, y = 3039, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 14563, y = 3039, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "appliances_laundry_01_0", x = 14563, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_2",     x = 14561, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
    },
    doorKeys = {
        name = "E Lville Farm",
        doors = {
        },
    },
    map = { name = "DWAPStashMap16", },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 14558, y = 3038, z = -1, },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 14560, y = 3038, z = -1, },
            fakeGenerators = {
                { x = 14578, y = 3037, z = -1, },
                { x = 14561, y = 3040, z = -1, },
            },
        },
    },
    objectSpawns = {
        { barricade = "wood",         enabled = "Barricade", target = "location_shop_bargNclothes_01_32",    x = 14564, y = 3043,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14574, y = 3046,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14576, y = 3046,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "location_restaurant_pileocrepe_01_8", x = 14573, y = 3036,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_interior_house_02_57",          x = 14585, y = 3035,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14591, y = 3040,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14586, y = 3044,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14583, y = 3044,                          z = 0, },
    },
    loot = {
        { -- E1 cardboardbox in orange bunk room
            note = "cardboardbox @ bedroom",
            coords = { x = 14572, y = 3031, z = -1 },
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E2 east bluish bunk room
            note = "locker @ bedroom",
            coords = { x = 14577, y = 3039, z = -1 },
            special = "essentials",
        },
        { -- E3 center hallway crates
            note = "militarycrate @ storage",
            coords = { x = 14576, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E4
            note = "militarycrate @ storage",
            coords = { x = 14573, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E5
            note = "militarycrate @ storage",
            coords = { x = 14570, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- crates by stairs
        { -- E6
            note = "crate @ storage",
            coords = { x = 14584, y = 3034, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E7
            note = "crate @ storage",
            coords = { x = 14584, y = 3034, z = -1 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E8
            note = "crate @ storage",
            coords = { x = 14584, y = 3035, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E9
            note = "crate @ storage",
            coords = { x = 14584, y = 3035, z = -1 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E10
            note = "crate @ storage",
            coords = { x = 14584, y = 3036, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E11
            note = "crate @ storage",
            coords = { x = 14584, y = 3036, z = -1 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E12 north gray bunk room
            note = "locker @ armytent",
            coords = { x = 14575, y = 3033, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E13 north gray bunk room
            note = "locker @ armytent",
            coords = { x = 14577, y = 3031, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E14 north orange bunk room
            note = "locker @ bedroom",
            coords = { x = 14574, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E15 south gray bunk room (foot locker)
            note = "locker @ bedroom",
            coords = { x = 14572, y = 3037, z = -1 },
            dist = { "SewingStoreTools" },
            distIncludeJunk = true,
            tag = "DWAPTailor",
        },
        { -- E16 south gray bunk room (lockers)
            note = "locker @ bedroom",
            coords = { x = 14574, y = 3039, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        -- security/armory
        { -- E17
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3033, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E18
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3032, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E19
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3031, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E20
            note = "militarycrate @ security",
            coords = { x = 14571, y = 3033, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPGun",
        },
        -- infirmary
        { -- E21
            note = "metal_shelves @ medical",
            coords = { x = 14571, y = 3038, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPMed",
        },
        { -- E22
            note = "metal_shelves @ medical",
            coords = { x = 14571, y = 3039, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        { -- E23
            note = "counter @ medical",
            coords = { x = 14567, y = 3037, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        { -- E24
            note = "sidetable @ medical",
            coords = { x = 14567, y = 3039, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E25
            note = "medicine @ medical",
            coords = { x = 14569, y = 3037, z = -1 },
            slot = "upper",
            dist = { "MedicalCabinet" },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        -- shooting range
        { -- E26
            note = "desk @ gunstore",
            coords = { x = 14563, y = 3031, z = -1 },
            dist = { "SafehouseTraps", },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E27
            note = "counter @ gunstore",
            coords = { x = 14562, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        { -- E28
            note = "desk @ gunstore",
            coords = { x = 14561, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E29
            note = "counter @ gunstore",
            coords = { x = 14560, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E30
            note = "desk @ gunstore",
            coords = { x = 14559, y = 3031, z = -1 },
            dist = { "SafehouseLighting" },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E31
            note = "counter @ gunstore",
            coords = { x = 14558, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        { -- E32
            note = "desk @ gunstore",
            coords = { x = 14557, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E33
            note = "counter @ gunstore",
            coords = { x = 14556, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        -- bathroom
        { -- E34
            note = "medicine @ bathroom",
            coords = { x = 14561, y = 3037, z = -1 },
            slot = "upper",
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        { -- E35
            note = "counter @ bathroom",
            coords = { x = 14561, y = 3037, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        -- workroom/ utility room
        { -- E36
            note = "counter @ weldingworkshop",
            coords = { x = 14555, y = 3037, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPFarm",
        },
        { -- E37
            note = "counter @ weldingworkshop",
            coords = { x = 14555, y = 3038, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPFarm",
        },
        { -- E38
            note = "militarylocker @ weldingworkshop",
            coords = { x = 14560, y = 3040, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E39
            note = "counter @ weldingworkshop",
            coords = { x = 14560, y = 3042, z = -1 },
            dist = { "LoggingFactoryTools" },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E40 double crate
            note = "crate @ weldingworkshop",
            coords = { x = 14560, y = 3046, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E41 double crate
            note = "crate @ weldingworkshop",
            coords = { x = 14560, y = 3046, z = -1 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E42
            note = "crate @ weldingworkshop",
            coords = { x = 14559, y = 3046, z = -1 },
            dist = { "CrateBlacksmithing" },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E43
            note = "crate @ weldingworkshop",
            coords = { x = 14558, y = 3046, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },

        -- kitchen
        { -- E44
            note = "freezer @ kitchen",
            coords = { x = 14568, y = 3033, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPFreezer",
        },
        { -- E45
            note = "freezer @ kitchen",
            coords = { x = 14568, y = 3032, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPFreezer",
        },
        { -- E46
            note = "fridge @ kitchen",
            coords = { x = 14568, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPFridge",
        },
        { -- E47
            note = "fridge @ kitchen",
            coords = { x = 14568, y = 3031, z = -1 },
            slot = "freezer",
            distIncludeJunk = true,
            tag = "DWAPFridge",
        },
        { -- E48
            note = "counter @ kitchen",
            coords = { x = 14566, y = 3031, z = -1 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E49
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3031, z = -1 },
            slot = "upper",
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E50
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3032, z = -1 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E51
            note = "counter @ kitchen",
            coords = { x = 14566, y = 3033, z = -1 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E52
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3033, z = -1 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPBooze",
        },

        -- first floor
        { -- E53
            note = "counter @ bathroom",
            coords = { x = 14576, y = 3035, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        { -- E54
            note = "metal_shelves @ miscstorage",
            coords = { x = 14573, y = 3035, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E55
            note = "metal_shelves @ miscstorage",
            coords = { x = 14574, y = 3035, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E56
            note = "crate @ miscstorage",
            coords = { x = 14575, y = 3035, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFish",
        },
        { -- E57
            note = "crate @ miscstorage",
            coords = { x = 14575, y = 3036, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFish",
        },
        { -- E58
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3037, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E59
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3038, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E60
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3038, z = 0 },
            stack = 2,
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E61
            note = "crate @ miscstorage",
            coords = { x = 14574, y = 3038, z = 0 },
            dist = { "WeldingWorkshopMetal" },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        -- living room
        { -- E62
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3039, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E63
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3044, z = 0 },
            items = {
                { name = 'TvWideScreen',    chance = 1,   count = { 1, 1 } },
                { name = 'Base.Remote',     chance = 1,   count = { 1, 3 } },
                { name = 'Base.VideoGame',  chance = 1,   count = { 3, 3 } },
                { name = 'Base.Headphones', chance = 1,   count = { 3, 3 } },
                { name = 'Base.CDplayer',   chance = 1,   count = { 3, 3 } },
                { name = 'Base.Bullhorn',   chance = 0.5, count = { 1, 1 } },
            },
        },
        { -- E64
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3045, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        -- kitchen
        { -- E65
            note = "shelves @ kitchen",
            coords = { x = 14584, y = 3039, z = 0 },
            slot = "upper",
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E66
            note = "fridge @ kitchen",
            coords = { x = 14589, y = 3036, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFridge",
        },
        { -- E67
            note = "fridge @ kitchen",
            coords = { x = 14589, y = 3036, z = 0 },
            slot = "freezer",
            distIncludeJunk = true,
            tag = "DWAPFridge",
        },
        { -- E68
            note = "counter @ kitchen",
            coords = { x = 14584, y = 3035, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E69
            note = "counter @ kitchen",
            coords = { x = 14585, y = 3035, z = 0 },
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E70
            note = "counter @ kitchen",
            coords = { x = 14586, y = 3035, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E71
            note = "counter @ kitchen",
            coords = { x = 14587, y = 3035, z = 0 },
            dist = { "KitchenDryFood", },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E72
            note = "counter @ kitchen",
            coords = { x = 14588, y = 3039, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        { -- E73
            note = "counter @ kitchen",
            coords = { x = 14589, y = 3039, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFood",
        },
        -- 2nd floor
        { -- E74
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3043, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E75
            note = "metal_shelves @ closet",
            coords = { x = 14578, y = 3038, z = 1 },
            slot = "upper",
            dist = { "MovieRentalShelves" },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },
        { -- E76
            note = "wardrobe @ kidsbedroom",
            coords = { x = 14573, y = 3037, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPTailor",
        },
        { -- E77
            note = "wardrobe @ kidsbedroom",
            coords = { x = 14573, y = 3038, z = 1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E79
            note = "cardboardbox @ closet",
            coords = { x = 14577, y = 3039, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E80
            note = "cardboardbox @ closet",
            coords = { x = 14577, y = 3038, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPFood",
        },
        { -- E81
            note = "wardrobe @ hall",
            coords = { x = 14579, y = 3040, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E82
            note = "wardrobe @ hall",
            coords = { x = 14579, y = 3041, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E83
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3042, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPMed",
        },
        { -- E84
            note = "dresser @ bedroom",
            coords = { x = 14573, y = 3040, z = 1 },
            dist = { "CrateLeather" },
            distIncludeJunk = true,
            tag = "DWAPTailor",
        },
        { -- E85
            note = "clothingrack @ bedroom",
            coords = { x = 14575, y = 3043, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E86
            note = "clothingrack @ bedroom",
            coords = { x = 14576, y = 3043, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E87
            note = "wardrobe @ hall",
            coords = { x = 14585, y = 3038, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E88
            note = "wardrobe @ hall",
            coords = { x = 14586, y = 3038, z = 1 },
            distIncludeJunk = true,
            tag = "DWAPLockers",
        },
        { -- E89
            note = "sidetable @ hall",
            coords = { x = 14584, y = 3035, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPBooze",
        },
        { -- E90
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3036, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPFarm",
        },
        { -- E91
            note = "sidetable @ hall",
            coords = { x = 14584, y = 3041, z = 1 },
            distIncludeJunk = false,
            tag = "DWAPMedia",
        },

        -- shed
        { -- E92
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3069, z = 0 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E93
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3068, z = 0 },
            slot = "upper",
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E94
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3065, z = 0 },
            dist = { "GasStoreEmergency" },
            distIncludeJunk = true,
            level = 2,
        },
        -- barn
        { -- E95
            note = "crate @ farmstorage",
            coords = { x = 14557, y = 3040, z = 0 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            level = "Loot_BuildMatsLevel",
        },
        { -- E96
            note = "crate @ farmstorage",
            coords = { x = 14558, y = 3040, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPBuildMats",
        },
        { -- E97
            note = "metal_shelves @ farmstorage",
            coords = { x = 14563, y = 3040, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPTools",
        },
        { -- E98
            note = "metal_shelves @ farmstorage",
            coords = { x = 14563, y = 3041, z = 0 },
            distIncludeJunk = true,
            tag = "DWAPGun",
        },
        { -- E99
            note = "crate @ farmstorage",
            coords = { x = 14562, y = 3043, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E100
            note = "crate @ farmstorage",
            coords = { x = 14562, y = 3043, z = 0 },
            stack = 2,
            distIncludeJunk = false,
            tag = "DWAPBuildMats",
        },
        { -- E101
            note = "metal_shelves @ farmstorage",
            coords = { x = 14562, y = 3044, z = 0 },
            tag = "DWAPFarm",
        },
        { -- E102
            note = "metal_shelves @ farmstorage",
            coords = { x = 14562, y = 3045, z = 0 },
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E103
            note = "metal_shelves @ farmstorage",
            coords = { x = 14552, y = 3040, z = 0 },
            distIncludeJunk = false,
            tag = "DWAPFarm",
        },
        { -- E104
            note = "metal_shelves @ farmstorage",
            coords = { x = 14549, y = 3040, z = 0 },
            tag = "DWAPFarm",
        },
    },
}

return ELVilleFarm
