local wtc = { x = 14556, y = 3044, z = -1 } -- waterTankCoords
local pb1 = { x = 14555, y = 3040, z = -1 } -- powerbankCoords
local ELVilleFarm = {
    group = "Louisville",
    baseBuildings = {
        { x = 14584, y = 3036, z = 1 },  -- farmhouse
        { x = 14571, y = 3035, z = -1 }, -- farmhouse basement
        { x = 14558, y = 3043, z = 0 },  -- barn
        { x = 14575, y = 3068, z = 0 },  -- shed
    },
    spawn = { x = 14584, y = 3036, z = 1 },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType = "generator", source = { x = 14556, y = 3041, z = 0 } },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_17",    x = 14576, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 14577, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_17",    x = 14585, y = 3035, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_19",    x = 14590, y = 3039, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "appliances_laundry_01_7", x = 14592, y = 3038, z = 0,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        -- 2nd floor
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3043, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3042, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_2",  x = 14583, y = 3043, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_25", x = 14583, y = 3041, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_1",  x = 14581, y = 3038, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3037, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_21",    x = 14581, y = 3036, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_26", x = 14582, y = 3035, z = 1,  sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },

        -- basement fixtures
        { sprite = "fixtures_sinks_01_8",     x = 14566, y = 3033, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_8",     x = 14567, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_33", x = 14561, y = 3039, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 14563, y = 3039, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "appliances_laundry_01_0", x = 14563, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
        { sprite = "fixtures_sinks_01_2",     x = 14561, y = 3037, z = -1, sourceType = "tank", source = { x = wtc.x, y = wtc.y, z = wtc.z } },
    },
    doorKeys = {
        name = "E Lville Farm",
        doors = {
        },
    },
    map = { name = "DWAPStashMap16", },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 14558, y = 3038, z = pb1.z },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 14560, y = 3038, z = -1, },
            fakeGenerators = {
                { x = 14578, y = 3037, z = -1, },
                { x = 14561, y = 3040, z = -1, },
            },
        },
    },
    objectSpawns = {
        -- { sprite = "camping_01_16", x = 14592, y = 3045, z = 0, enabled = "EnableWaterSystem", }, -- fountain
        { sprite = "industry_02_175", x = pb1.x,             y = pb1.y,                                      z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        -- { sprite = "furniture_shelving_01_24", x = 14562, y = 3045, z = 0, clearExisting = false, isContainer = true, },
        -- { sprite = "furniture_shelving_01_25", x = 14562, y = 3044, z = 0, clearExisting = false, isContainer = true, },
        -- { sprite = "carpentry_01_16", x = 14562, y = 3043, z = 0, renderYOffset = 0, clearExisting = false, isContainer = true, },
        -- { sprite = "carpentry_01_16", x = 14562, y = 3043, z = 0, renderYOffset = 32, clearExisting = false, isContainer = true, },
        -- { sprite = "carpentry_01_16", x = 14562, y = 3042, z = 0, renderYOffset = 0, clearExisting = false, isContainer = true, },
        -- { sprite = "carpentry_01_16", x = 14562, y = 3042, z = 0, renderYOffset = 32, clearExisting = false, isContainer = true, },
        -- { x = 14563, y = 3042, z = 0, clearExisting = true, },

        -- { sprite = "fixtures_doors_frames_01_9", x = 14578, y = 3036, z = 0, replaceWall = true, clearExisting = true, },
        -- { sprite = "walls_interior_house_02_59", x = 14578, y = 3036, z = 0, },
        -- { sprite = "walls_interior_house_02_48", x = 14578, y = 3036, z = 0, },
        -- { sprite = "fixtures_doors_01_5", x = 14578, y = 3036, z = 0, isDoor = true, doorN = true, },

        { barricade = "wood",         enabled = "Barricade", target = "location_shop_bargNclothes_01_32",    x = 14564, y = 3043,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14574, y = 3046,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14576, y = 3046,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "location_restaurant_pileocrepe_01_8", x = 14573, y = 3036,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_interior_house_02_57",          x = 14585, y = 3035,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14591, y = 3040,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14586, y = 3044,                          z = 0, },
        { barricade = "woodhalf",     enabled = "Barricade", target = "walls_exterior_house_01_41",          x = 14583, y = 3044,                          z = 0, },
    },
    loot = {
        { -- E1 cardboardbox in orange bunk room
            note = "cardboardbox @ bedroom",
            coords = { x = 14572, y = 3031, z = -1 },
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E2 east bluish bunk room
            note = "locker @ bedroom",
            coords = { x = 14577, y = 3039, z = -1 },
            special = "essentials",
        },
        { -- E3 center hallway crates
            note = "militarycrate @ storage",
            coords = { x = 14576, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E4
            note = "militarycrate @ storage",
            coords = { x = 14573, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E5
            note = "militarycrate @ storage",
            coords = { x = 14570, y = 3035, z = -1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- crates by stairs
        { -- E6
            note = "crate @ storage",
            coords = { x = 14584, y = 3034, z = -1 },
            dist = { "CrateRandomJunk", "RandomFiller", "CrateLiquor", "LiquorStoreWhiskey" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E7
            note = "crate @ storage",
            coords = { x = 14584, y = 3034, z = -1 },
            stack = 2,
            dist = { "CrateRandomJunk", "RandomFiller", "CrateLiquor", "LiquorStoreWhiskey" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E8
            note = "crate @ storage",
            coords = { x = 14584, y = 3035, z = -1 },
            dist = { "LiquorStoreBeer", "LiquorStoreBeerFancy", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E9
            note = "crate @ storage",
            coords = { x = 14584, y = 3035, z = -1 },
            stack = 2,
            dist = { "LiquorStoreBeer", "LiquorStoreBeerFancy", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E10
            note = "crate @ storage",
            coords = { x = 14584, y = 3036, z = -1 },
            dist = { "CrateGravelBags", "CrateSandBags", "CrateClayBags" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E11
            note = "crate @ storage",
            coords = { x = 14584, y = 3036, z = -1 },
            stack = 2,
            dist = { "CrateGravelBags", "CrateSandBags", "CrateClayBags" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E12 north gray bunk room
            note = "locker @ armytent",
            coords = { x = 14575, y = 3033, z = -1 },
            dist = { "GasStoreEmergency", "StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools", "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E13 north gray bunk room
            note = "locker @ armytent",
            coords = { x = 14577, y = 3031, z = -1 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E14 north orange bunk room
            note = "locker @ bedroom",
            coords = { x = 14574, y = 3031, z = -1 },
            dist = { "CrateLiquor", "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E15 south gray bunk room (foot locker)
            note = "locker @ bedroom",
            coords = { x = 14572, y = 3037, z = -1 },
            dist = { "SewingStoreTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E16 south gray bunk room (lockers)
            note = "locker @ bedroom",
            coords = { x = 14574, y = 3039, z = -1 },
            dist = { "CrateLiquor", "MusicStoreCDs", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "CrateLinens" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- security/armory
        { -- E17
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3033, z = -1 },
            dist = { "SafehouseTraps", "GunStoreKnives", "CampingStoreBackpacks", "CrateLiquor", "CarSupplyTools", "GasStorageMechanics", "DrugLabOutfit" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E18
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3032, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E19
            note = "militarylocker @ security",
            coords = { x = 14569, y = 3031, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E20
            note = "militarycrate @ security",
            coords = { x = 14571, y = 3033, z = -1 },
            dist = { "ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- infirmary
        { -- E21
            note = "metal_shelves @ medical",
            coords = { x = 14571, y = 3038, z = -1 },
            dist = { "TestingLab", "MedicalCabinet", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E22
            note = "metal_shelves @ medical",
            coords = { x = 14571, y = 3039, z = -1 },
            dist = { "ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E23
            note = "counter @ medical",
            coords = { x = 14567, y = 3037, z = -1 },
            dist = { "MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E24
            note = "sidetable @ medical",
            coords = { x = 14567, y = 3039, z = -1 },
            dist = { "CrateRandomJunk", "RandomFiller", "ArmySurplusMisc", "MedicalOfficeBooks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E25
            note = "medicine @ medical",
            coords = { x = 14569, y = 3037, z = -1 },
            slot = "upper",
            dist = { "MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- shooting range
        { -- E26
            note = "desk @ gunstore",
            coords = { x = 14563, y = 3031, z = -1 },
            dist = { "SafehouseTraps", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E27
            note = "counter @ gunstore",
            coords = { x = 14562, y = 3031, z = -1 },
            dist = { "ArmySurplusMisc", "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E28
            note = "desk @ gunstore",
            coords = { x = 14561, y = 3031, z = -1 },
            dist = { "GunStoreKnives", "PawnShopKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E29
            note = "counter @ gunstore",
            coords = { x = 14560, y = 3031, z = -1 },
            dist = { "SafehouseArmor", "SafehouseArmor_Late", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E30
            note = "desk @ gunstore",
            coords = { x = 14559, y = 3031, z = -1 },
            dist = { "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E31
            note = "counter @ gunstore",
            coords = { x = 14558, y = 3031, z = -1 },
            dist = { "CrateRandomJunk", "GunStoreMagsAmmo", "GunStoreAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E32
            note = "desk @ gunstore",
            coords = { x = 14557, y = 3031, z = -1 },
            dist = { "GunStoreKnives", "PawnShopKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E33
            note = "counter @ gunstore",
            coords = { x = 14556, y = 3031, z = -1 },
            dist = { "LiquorStoreBeer", "JanitorCleaning", "DrugLabGuns", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        { -- E34
            note = "medicine @ bathroom",
            coords = { x = 14561, y = 3037, z = -1 },
            slot = "upper",
            dist = { "SafehouseMedical", "BathroomCounter", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E35
            note = "counter @ bathroom",
            coords = { x = 14561, y = 3037, z = -1 },
            dist = { "LaundryCleaning", "JanitorCleaning", "BathroomCounter", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- workroom/ utility room
        { -- E36
            note = "counter @ weldingworkshop",
            coords = { x = 14555, y = 3037, z = -1 },
            dist = { "GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E37
            note = "counter @ weldingworkshop",
            coords = { x = 14555, y = 3038, z = -1 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E38
            note = "militarylocker @ weldingworkshop",
            coords = { x = 14560, y = 3040, z = -1 },
            dist = { "BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E39
            note = "counter @ weldingworkshop",
            coords = { x = 14560, y = 3042, z = -1 },
            dist = { "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E40 double crate
            note = "crate @ weldingworkshop",
            coords = { x = 14560, y = 3046, z = -1 },
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E41 double crate
            note = "crate @ weldingworkshop",
            coords = { x = 14560, y = 3046, z = -1 },
            stack = 2,
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E42
            note = "crate @ weldingworkshop",
            coords = { x = 14559, y = 3046, z = -1 },
            dist = { "CrateBlacksmithing" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E43
            note = "crate @ weldingworkshop",
            coords = { x = 14558, y = 3046, z = -1 },
            dist = { "ArtStorePottery", "CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },

        -- kitchen
        { -- E44
            note = "freezer @ kitchen",
            coords = { x = 14568, y = 3033, z = -1 },
            dist = { "FreezerIceCream", "WesternKitchenFreezer", "BakeryKitchenFreezer" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E45
            note = "freezer @ kitchen",
            coords = { x = 14568, y = 3032, z = -1 },
            dist = { "SushiKitchenFreezer", "WesternKitchenFreezer", "FreezerRich" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E46
            note = "fridge @ kitchen",
            coords = { x = 14568, y = 3031, z = -1 },
            dist = { "SafehouseFridge", "PizzaKitchenFridge", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E47
            note = "fridge @ kitchen",
            coords = { x = 14568, y = 3031, z = -1 },
            slot = "freezer",
            dist = { "ArenaKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E48
            note = "counter @ kitchen",
            coords = { x = 14566, y = 3031, z = -1 },
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E49
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3031, z = -1 },
            slot = "upper",
            dist = { "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E50
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3032, z = -1 },
            slot = "upper",
            dist = { "ButcherSpices", "GigamartSpices", "GroceryBagGourmet", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E51
            note = "counter @ kitchen",
            coords = { x = 14566, y = 3033, z = -1 },
            dist = { "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            note = "overhead @ kitchen",
            coords = { x = 14566, y = 3033, z = -1 },
            slot = "upper",
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },

        -- first floor
        { -- E53
            note = "counter @ bathroom",
            coords = { x = 14576, y = 3035, z = 0 },
            dist = { "MedicalCabinet", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E54
            note = "metal_shelves @ miscstorage",
            coords = { x = 14573, y = 3035, z = 0 },
            dist = { "CrateTortillaChips", "KitchenDryFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E55
            note = "metal_shelves @ miscstorage",
            coords = { x = 14574, y = 3035, z = 0 },
            dist = { "GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E56
            note = "crate @ miscstorage",
            coords = { x = 14575, y = 3035, z = 0 },
            dist = { "CrateFishing", "FishermanTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E57
            note = "crate @ miscstorage",
            coords = { x = 14575, y = 3036, z = 0 },
            dist = { "HuntingLockers", "RangerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E58
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3037, z = 0 },
            dist = { "CrateToiletPaper", "CrateLinens" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E59
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3038, z = 0 },
            dist = { "CrateLumber", "CrateSheetMetal" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E60
            note = "crate @ miscstorage",
            coords = { x = 14573, y = 3038, z = 0 },
            stack = 2,
            dist = { "CrateLumber", "CrateSheetMetal" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E61
            note = "crate @ miscstorage",
            coords = { x = 14574, y = 3038, z = 0 },
            dist = { "WeldingWorkshopMetal" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- living room
        { -- E62
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3039, z = 0 },
            dist = { "LockerArmyBedroomHome", "BookstoreMilitaryHistory" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E63
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3044, z = 0 },
            dist = { "BookstoreBiography", "BookstoreBusiness", "MusicStoreCDs", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E64
            note = "shelves @ livingroom",
            coords = { x = 14573, y = 3045, z = 0 },
            dist = { "BookstoreBiography", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- kitchen
        { -- E65
            note = "shelves @ kitchen",
            coords = { x = 14584, y = 3039, z = 0 },
            slot = "upper",
            dist = { "TheatrePopcorn", "FridgeSoda", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E66
            note = "fridge @ kitchen",
            coords = { x = 14589, y = 3036, z = 0 },
            dist = { "SafehouseFridge", "PizzaKitchenFridge", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E67
            note = "fridge @ kitchen",
            coords = { x = 14589, y = 3036, z = 0 },
            slot = "freezer",
            dist = { "FreezerRich", "ArenaKitchenFreezer", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E68
            note = "counter @ kitchen",
            coords = { x = 14584, y = 3035, z = 0 },
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E69
            note = "counter @ kitchen",
            coords = { x = 14585, y = 3035, z = 0 },
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E70
            note = "counter @ kitchen",
            coords = { x = 14586, y = 3035, z = 0 },
            dist = { "ButcherSpices", "GigamartSpices", "GroceryBagGourmet", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E71
            note = "counter @ kitchen",
            coords = { x = 14587, y = 3035, z = 0 },
            dist = { "KitchenDryFood", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E72
            note = "counter @ kitchen",
            coords = { x = 14588, y = 3039, z = 0 },
            dist = { "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E73
            note = "counter @ kitchen",
            coords = { x = 14589, y = 3039, z = 0 },
            dist = { "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- 2nd floor
        { -- E74
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3043, z = 1 },
            items = {
                { name = 'TvWideScreen',    chance = 1,   count = { 1, 1 } },
                { name = 'Base.Remote',     chance = 1,   count = { 1, 3 } },
                { name = 'Base.VideoGame',  chance = 1,   count = { 3, 3 } },
                { name = 'Base.Headphones', chance = 1,   count = { 3, 3 } },
                { name = 'Base.CDplayer',   chance = 1,   count = { 3, 3 } },
                { name = 'Base.Bullhorn',   chance = 0.5, count = { 1, 1 } },
            },
        },
        { -- E75
            note = "metal_shelves @ closet",
            coords = { x = 14578, y = 3038, z = 1 },
            slot = "upper",
            dist = { "MovieRentalShelves" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E76
            note = "wardrobe @ kidsbedroom",
            coords = { x = 14573, y = 3037, z = 1 },
            dist = { "SewingStoreTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E77
            note = "wardrobe @ kidsbedroom",
            coords = { x = 14573, y = 3038, z = 1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E78
            note = "wardrobe @ kidsbedroom",
            coords = { x = 14573, y = 3037, z = 1 },
            dist = { "SewingStoreFabric" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E79
            note = "cardboardbox @ closet",
            coords = { x = 14577, y = 3039, z = 1 },
            dist = { "CrateCannedFood", "ArmySurplusTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E80
            note = "cardboardbox @ closet",
            coords = { x = 14577, y = 3038, z = 1 },
            dist = { "CrateCannedFood", "ArmySurplusTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E81
            note = "wardrobe @ hall",
            coords = { x = 14579, y = 3040, z = 1 },
            dist = { "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E82
            note = "wardrobe @ hall",
            coords = { x = 14579, y = 3041, z = 1 },
            dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E83
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3042, z = 1 },
            dist = { "MedicalClinicTools", "MedicalStorageDrugs" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E84
            note = "dresser @ bedroom",
            coords = { x = 14573, y = 3040, z = 1 },
            dist = { "CrateLeather" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E85
            note = "clothingrack @ bedroom",
            coords = { x = 14575, y = 3043, z = 1 },
            dist = { "LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E86
            note = "clothingrack @ bedroom",
            coords = { x = 14576, y = 3043, z = 1 },
            dist = { "ArmyStorageOutfit", "DrugLabOutfit" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E87
            note = "wardrobe @ hall",
            coords = { x = 14585, y = 3038, z = 1 },
            dist = { "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E88
            note = "wardrobe @ hall",
            coords = { x = 14586, y = 3038, z = 1 },
            dist = { "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E89
            note = "sidetable @ hall",
            coords = { x = 14584, y = 3035, z = 1 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E90
            note = "counter @ bathroom",
            coords = { x = 14581, y = 3036, z = 1 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E91
            note = "sidetable @ hall",
            coords = { x = 14584, y = 3041, z = 1 },
            dist = { "BookstoreBiography", "BookstoreBusiness", "MusicStoreCDs", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },

        -- shed
        { -- E92
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3069, z = 0 },
            slot = "upper",
            dist = { "ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E93
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3068, z = 0 },
            slot = "upper",
            dist = { "ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E94
            note = "metal_shelves @ garagestorage",
            coords = { x = 14573, y = 3065, z = 0 },
            dist = { "GasStoreEmergency" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        -- barn
        { -- E95
            note = "crate @ farmstorage",
            coords = { x = 14557, y = 3040, z = 0 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E96
            note = "crate @ farmstorage",
            coords = { x = 14558, y = 3040, z = 0 },
            dist = { "CrateLumber" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E97
            note = "metal_shelves @ farmstorage",
            coords = { x = 14563, y = 3040, z = 0 },
            dist = { "CrateTools", "GarageTools", "BarnTools", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E98
            note = "metal_shelves @ farmstorage",
            coords = { x = 14563, y = 3041, z = 0 },
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E99
            note = "crate @ farmstorage",
            coords = { x = 14562, y = 3043, z = 0 },
            dist = { "CrateSheetMetal", "CrateLumber", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E100
            note = "crate @ farmstorage",
            coords = { x = 14562, y = 3043, z = 0 },
            stack = 2,
            dist = { "CrateSheetMetal", "CrateLumber", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E101
            note = "metal_shelves @ farmstorage",
            coords = { x = 14562, y = 3044, z = 0 },
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E102
            note = "metal_shelves @ farmstorage",
            coords = { x = 14562, y = 3045, z = 0 },
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E103
            note = "metal_shelves @ farmstorage",
            coords = { x = 14552, y = 3040, z = 0 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E104
            note = "metal_shelves @ farmstorage",
            coords = { x = 14549, y = 3040, z = 0 },
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
    },
}

return ELVilleFarm
