-- @TODO (2026-08-07 audit) unresolved - delete lines as they are fixed
--   * systems: waterTank 1 at 10094,8259,3 present but carrying no fluid
--     container - the conversion started and did not finish, so this one is a
--     bug rather than bad coords
local wtc = {x = 10094, y = 8259, z = 3}
local pb1 = {x = 10112, y = 8240, z = -1}
local McCoyEstate = {
    group = "McCoy Estate", -- Perhaps muldraugh, but kinda half way between there and west point, east of Dixie but really not close to anything
    baseBuildings = {
        { x = 10081, y = 8259, z = 1 }, -- estate house
        { x = 10093, y = 8290, z = 0 }, -- dock house/fishing
        { x = 10112, y = 8239, z = 0 }, -- workshop
        { x = 10112, y = 8239, z = -1 }, -- generator basement
    },
    spawn = { x = 10081, y = 8259, z = 1 },
    waterTanks = {
        { sprite = "crafted_01_11", x = wtc.x, y = wtc.y, z = wtc.z, isProp = true, sourceType="generator", source = {x = 10120, y = 8239, z = -1}},
        { sprite = "dwap_tiles_01_9", x = 10116, y = 8239, z = -1, sourceType="generator", source = {x = 10120, y = 8239, z = -1}},
    },
    waterFixtures = {
        -- fishing 
        { sprite = "fixtures_sinks_01_33", x = 10092, y = 8279, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 10095, y = 8279, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- butchering
        { sprite = "fixtures_sinks_01_33", x = 10092, y = 8252, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 10093, y = 8252, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        { sprite = "fixtures_bathroom_01_3", x = 10094, y = 8258, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- laundry
        { sprite = "fixtures_sinks_01_13", x = 10093, y = 8260, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_5", x = 10093, y = 8261, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_1", x = 10093, y = 8262, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- kitchen
        { sprite = "fixtures_sinks_01_16", x = 10084, y = 8261, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- master bath
        { sprite = "fixtures_bathroom_01_1", x = 10080, y = 8256, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 10080, y = 8255, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 10080, y = 8254, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_4", x = 10083, y = 8254, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- 3rd floor
        { sprite = "fixtures_sinks_01_13", x = 10080, y = 8257, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_13", x = 10080, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_13", x = 10088, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_33", x = 10088, y = 8260, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_2", x = 10090, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 10091, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 10092, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 10093, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 10094, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 10095, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "McCoy Estate",
        doors = {
            { sprite = "fixtures_doors_01_4", x = 10100, y = 8258, z = 0, },
            { sprite = "fixtures_doors_01_9", x = 10108, y = 8244, z = 0, },
            { sprite = "walls_logs_41", x = 10091, y = 8279, z = 0, },
        },
    },
    map = { name = "DWAPStashMap18", },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 10120, y = 8239, z = pb1.z },
            fuelTank = { sprite = "dwap_tiles_01_24", x= 10118, y= 8239, z= -1, },
            fakeGenerators = {
                { x = 10095, y = 8282, z = -1, },
                { x = 10087, y = 8268, z = -1, },
                { x = 10112, y = 8241, z = -1, },
            },
        },
    },
    objectSpawns = {
        { sprite = "crafted_01_11", x = 10094, y = 8259, z = 3, enabled = "EnableWaterSystem", }, -- invisible "tank" to simulate the well
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        { sprite = "constructedobjects_01_45", x = 10058, y = 8236, z = 0, clearExisting = true, isContainer = true, },
        { sprite = "carpentry_01_16", x = 10095, y = 8262, z = 0, clearExisting = true, isContainer = true, },

        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10088, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10082, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10081, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_8", x = 10101, y = 8260, z = 0, },
    },
    loot = {
        { -- E1
            note = "crate @ lobby",
            coords = {x = 10095, y = 8262, z = 0},
            special = "essentials",
        },

        -- first floor
        -- office
        { -- E2
            note = "desk @ livingroom",
            coords = {x=10093,y=8256,z=1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E3
            note = "shelves @ livingroom",
            coords = {x=10097,y=8254,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E4
            note = "shelves @ livingroom",
            coords = {x=10098,y=8254,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- E5
            note = "shelves @ livingroom",
            coords = {x=10093,y=8257,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        -- sitting area
        { -- E6
            note = "shelves @ livingroom",
            coords = {x=10095,y=8257,z=1},
            slot = "upper",
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E7
            note = "shelves @ livingroom",
            coords = {x=10099,y=8257,z=1},
            slot = "upper",
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E8
            note = "counter @ livingroom",
            coords = {x=10100,y=8261,z=1},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.VHS_Retail', chance = 1, count = {3,3} },
            },
            randUntilFull = true,
        },
        { -- E9
            note = "cardboardbox @ garage",
            coords = {x=10099,y=8261,z=2},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E10
            note = "counter @ livingroom",
            coords = {x=10100,y=8260,z=1},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E11
            note = "counter @ livingroom",
            coords = {x=10093,y=8260,z=1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E12
            note = "counter @ livingroom",
            coords = {x=10093,y=8261,z=1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E13
            note = "counter @ livingroom",
            coords = {x=10092,y=8262,z=1},
            dist = {"CrateInstruments"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E14
            note = "counter @ livingroom",
            coords = {x=10091,y=8262,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E15
            note = "counter @ lobby",
            coords = {x=10088,y=8254,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E16
            note = "counter @ lobby",
            coords = {x=10089,y=8254,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- near stairs
        { -- E17
            note = "shelves @ lobby",
            coords = {x=10092,y=8254,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E18
            note = "shelves @ lobby",
            coords = {x=10092,y=8255,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E19
            note = "dresser @ lobby",
            coords = {x=10089,y=8258,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E20
            note = "dishescabinet @ lobby",
            coords = {x=10089,y=8259,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E21
            note = "dishescabinet @ lobby",
            coords = {x=10089,y=8260,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        { -- E22
            note = "shelves @ kitchen",
            coords = {x=10088,y=8260,z=1},
            dist = {"StoreKitchenButcher", "CrateFlour", "CrateOilVegetable", "StoreKitchenSauce", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E23
            note = "counter @ kitchen",
            coords = {x=10085,y=8260,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E24
            note = "counter @ kitchen",
            coords = {x=10084,y=8260,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E25
            note = "counter @ kitchen",
            coords = {x=10084,y=8261,z=1},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E26
            note = "counter @ kitchen",
            coords = {x=10084,y=8262,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E27
            note = "overhead @ kitchen",
            coords = {x=10084,y=8262,z=1},
            slot = "upper",
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E28
            note = "fridge @ kitchen",
            coords = {x=10084,y=8263,z=1},
            dist = {"CatfishKitchenFridge", "ChineseKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E29
            note = "overhead @ kitchen",
            coords = {x=10084,y=8263,z=1},
            slot = "upper",
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E30
            note = "fridge @ kitchen",
            coords = {x=10084,y=8264,z=1},
            dist = {"WesternKitchenFreezer",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- master bedroom
        { -- E31
            note = "dresser @ bedroom",
            coords = {x=10080,y=8263,z=1},
            dist = {"FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E32
            note = "dresser @ bedroom",
            coords = {x=10080,y=8260,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E33
            note = "wardrobe @ bedroom",
            coords = {x=10080,y=8257,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E34
            note = "wardrobe @ bedroom",
            coords = {x=10081,y=8257,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- mb closet
        { -- E35
            note = "shelves @ lobby",
            coords = {x=10088,y=8257,z=1},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E36
            note = "shelves @ lobby",
            coords = {x=10087,y=8257,z=1},
            dist = {"CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E37
            note = "clothingrack @ lobby",
            coords = {x=10086,y=8257,z=1},
            dist = {"SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E38
            note = "clothingrack @ lobby",
            coords = {x=10085,y=8257,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E39
            note = "clothingrack @ lobby",
            coords = {x=10084,y=8257,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E40
            note = "clothingrack @ lobby",
            coords = {x=10088,y=8259,z=1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E41
            note = "clothingrack @ lobby",
            coords = {x=10087,y=8259,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E42
            note = "clothingrack @ lobby",
            coords = {x=10086,y=8259,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E43
            note = "clothingrack @ lobby",
            coords = {x=10085,y=8259,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- mb bath
        { -- E44
            note = "counter @ bathroom",
            coords = {x=10080,y=8254,z=1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- top floor
        { -- E45
            note = "locker @ bedroom",
            coords = {x=10083,y=8258,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E46
            note = "locker @ bedroom",
            coords = {x=10083,y=8259,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E47
            note = "dresser @ bedroom",
            coords = {x=10083,y=8261,z=2},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E48
            note = "desk @ bedroom",
            coords = {x=10087,y=8262,z=2},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        { -- E49
            note = "counter @ bedroom",
            coords = {x=10084,y=8260,z=2},
            dist = {"SafehouseTraps", "ArmyStorageAmmunition"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E50
            note = "cardboardbox @ bedroom",
            coords = {x=10084,y=8263,z=2},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E51
            note = "dishescabinet @ lobby",
            coords = {x=10090,y=8257,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            note = "dishescabinet @ lobby",
            coords = {x=10091,y=8257,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E53
            note = "medicine @ garage",
            coords = {x=10090,y=8260,z=2},
            slot = "upper",
            dist = {"MedicalCabinet"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E54
            note = "counter @ bathroom",
            coords = {x=10093,y=8255,z=2},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E55
            note = "counter @ bathroom",
            coords = {x=10092,y=8255,z=2},
            dist = {"BathroomCounter", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- first floor
        -- butcher room
        { -- E56
            note = "counter @ butcher",
            coords = {x=10090,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E57
            note = "counter @ butcher",
            coords = {x=10091,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable", "SeafoodKitchenSauce"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E58
            note = "counter @ butcher",
            coords = {x=10093,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable", "StoreKitchenCutlery"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E59
            note = "freezer @ butcher",
            coords = {x=10090,y=8254,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "FreezerRich"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E60
            note = "freezer @ butcher",
            coords = {x=10090,y=8255,z=0},
            dist = {"ArenaKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- hallway
        { -- E61
            note = "metal_shelves @ lobby",
            coords = {x=10092,y=8256,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E62
            note = "metal_shelves @ lobby",
            coords = {x=10093,y=8256,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E63
            note = "counter @ lobby",
            coords = {x=10091,y=8258,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E64
            note = "counter @ lobby",
            coords = {x=10090,y=8258,z=0},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        -- storage room with generator
        { -- E65
            note = "metal_shelves @ lobby",
            coords = {x=10089,y=8261,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E66
            note = "metal_shelves @ lobby",
            coords = {x=10089,y=8262,z=0},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E67
            note = "counter @ lobby",
            coords = {x=10085,y=8258,z=0},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E68
            note = "counter @ lobby",
            coords = {x=10085,y=8259,z=0},
            dist = {"LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E69
            note = "counter @ lobby",
            coords = {x=10085,y=8263,z=0},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        { -- E70
            note = "counter @ lobby",
            coords = {x=10085,y=8264,z=0},
            dist = {"CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E71
            note = "counter @ lobby",
            coords = {x=10086,y=8264,z=0},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- garage area
        { -- E72
            note = "toolcabinet @ garage",
            coords = {x=10082,y=8257,z=0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E73
            note = "metal_shelves @ garage",
            coords = {x=10081,y=8257,z=0},
            slot = "upper",
            dist = {"CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E74
            note = "metal_shelves @ garage",
            coords = {x=10084,y=8257,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E75
            note = "metal_shelves @ garage",
            coords = {x=10084,y=8258,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- more hallway
        { -- E76
            note = "counter @ lobby",
            coords = {x=10078,y=8255,z=0},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E77
            note = "counter @ lobby",
            coords = {x=10078,y=8256,z=0},
            dist = {"ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E78
            note = "counter @ lobby",
            coords = {x=10081,y=8254,z=0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E79
            note = "counter @ lobby",
            coords = {x=10082,y=8254,z=0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- more hallway other side of stairs
        { -- E80
            note = "counter @ lobby",
            coords = {x=10099,y=8263,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E81
            note = "counter @ lobby",
            coords = {x=10099,y=8264,z=0},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E82
            note = "counter @ lobby",
            coords = {x=10099,y=8265,z=0},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },

        { -- E83
            note = "metal_shelves @ lobby",
            coords = {x=10095,y=8261,z=0},
            items = {
                { name = 'Base.NailsCarton', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E84
            note = "metal_shelves @ lobby",
            coords = {x=10095,y=8260,z=0},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E85
            note = "metal_shelves @ lobby",
            coords = {x=10095,y=8258,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E86
            note = "metal_shelves @ lobby",
            coords = {x=10095,y=8257,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E87
            note = "crate @ outside",
            coords = {x=10100,y=8262,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E88
            note = "metal_shelves @ lobby",
            coords = {x=10098,y=8257,z=0},
            dist = {"ToolFactoryBarStock"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E89
            note = "locker @ lobby",
            coords = {x=10099,y=8257,z=0},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- food storage area
        { -- E90
            note = "freezer @ empty",
            coords = {x=10099,y=8254,z=0},
            dist = {"FreezerGarage" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E91
            note = "freezer @ empty",
            coords = {x=10098,y=8254,z=0},
            dist = {"FreezerGarage" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E92
            note = "metal_shelves @ empty",
            coords = {x=10097,y=8256,z=0},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E93
            note = "metal_shelves @ empty",
            coords = {x=10098,y=8256,z=0},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },

        -- shop building
        { -- E94
            note = "toolcabinet @ garage",
            coords = {x=10108,y=8248,z=0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E95
            note = "metal_shelves @ garage",
            coords = {x=10117,y=8243,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E96
            note = "metal_shelves @ garage",
            coords = {x=10117,y=8242,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E97
            note = "toolcabinet @ garage",
            coords = {x=10117,y=8239,z=0},
            dist = {"CrateBlacksmithing", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E98
            note = "metal_shelves @ garage",
            coords = {x=10114,y=8239,z=0},
            slot = "upper",
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- fishing building
        { -- E99
            note = "metal_shelves @ empty",
            coords = {x=10092,y=8282,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E100
            note = "metal_shelves @ empty",
            coords = {x=10093,y=8282,z=0},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E101
            note = "counter @ empty",
            coords = {x=10093,y=8279,z=0},
            dist = {"FishingStoreGear", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E102
            note = "counter @ empty",
            coords = {x=10094,y=8279,z=0},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E103
            note = "counter @ empty",
            coords = {x=10095,y=8279,z=0},
            dist = { "SushiKitchenBaking"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E104
            note = "freezer @ empty",
            coords = {x=10090,y=8280,z=0},
            dist = {"SushiKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E105
            note = "cardboardbox @ empty",
            coords = {x=10099,y=8279,z=0},
            dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E106
            note = "cardboardbox @ empty",
            coords = {x=10099,y=8280,z=0},
            dist = {"ArtStorePottery"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E107
            note = "crate @ empty",
            coords = {x=10099,y=8282,z=0},
            dist = {"TestingLab", "TobaccoStoreAccessories", "ToolStoreAccessories", "ArtStorePottery", "ArtSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },

        -- crate near chicken pen
        { -- E108
            note = "crate @ outside",
            coords = {x=10056,y=8236,z=0},
            dist = {"BarnTools", "CrateAnimalFeed", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E109
            note = "crate @ outside",
            coords = {x=10058,y=8236,z=0},
            dist = {"CrateGravelBags", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- woodpile
        { -- E110
            note = "logs @ outside",
            coords = {x=10115,y=8260,z=0},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
    },
}

return McCoyEstate

-- ArtStorePottery ArtSupplies
-- CrateBlacksmithing CrateCarpentry CrateMechanics CrateMetalwork