local wtc = {x = 10094, y = 8259, z = 3} -- waterTankCoords (well)
local McCoyEstate = {
    spawn = { x = 10081, y = 8259, z = 1 },
    waterTanks = {
        { sprite = "crafted_01_11", x = wtc.x, y = wtc.y, z = wtc.z, isProp = true, sourceType="generator", source = {x = 10113, y = 8240, z = 0}},
    },
    waterFixtures = {
        -- fishing 
        { sprite = "fixtures_sinks_01_33", x = 10092, y = 8279, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 10095, y = 8279, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- butchering
        { sprite = "fixtures_sinks_01_33", x = 10092, y = 8252, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 10093, y = 8252, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },


        { sprite = "fixtures_bathroom_01_37", x = 10094, y = 8258, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- laundry
        { sprite = "fixtures_sinks_01_13", x = 10093, y = 8260, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_5", x = 10093, y = 8261, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- kitchen
        { sprite = "fixtures_sinks_01_16", x = 10084, y = 8261, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- master bath
        { sprite = "fixtures_bathroom_01_1", x = 10080, y = 8256, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 10080, y = 8255, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 10080, y = 8254, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_4", x = 10083, y = 8254, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- 3rd floor
        { sprite = "fixtures_sinks_01_13", x = 10080, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_13", x = 10088, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_33", x = 10088, y = 8260, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_2", x = 10090, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 10091, y = 8261, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 10092, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 10093, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 10094, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_25", x = 10095, y = 8255, z = 2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "McCoy Estate",
        doors = {
            { sprite = "fixtures_doors_01_4", x = 10100, y = 8258, z = 0, },
            { sprite = "fixtures_doors_01_9", x = 10108, y = 8244, z = 0, },
            { sprite = "walls_logs_41", x = 10091, y = 8279, z = 0, },
        },
    },
    map = { name = "DWAPStashMap18", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 10113, y = 8240, z = 0, isProp=true, },
            chunks = {
                {1263, 1029},
                {1263, 1030},
                {1263, 1031},
                {1264, 1029},
                {1264, 1030},
                {1259, 1031},
                {1259, 1032},
                {1260, 1031},
                {1260, 1032},
                {1260, 1033},
                {1261, 1031},
                {1261, 1032},
                {1261, 1033},
                {1262, 1031},
                {1262, 1032},
                {1262, 1033},
                {1261, 1034},
                {1261, 1035},
                {1262, 1034},
                {1262, 1035},
                {1263, 1034},
            },
        },
    },
    objectSpawns = {
        { sprite = "industry_02_64", x = 10110, y = 8240, z = 0, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
        { sprite = "industry_02_68", x = 10110, y = 8239, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_65", x = 10111, y = 8240, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_69", x = 10111, y = 8239, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_66", x = 10112, y = 8240, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_70", x = 10112, y = 8239, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_67", x = 10113, y = 8240, z = 0, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_71", x = 10113, y = 8239, z = 0, enabled = "EnableGenSystem", clearExisting = true, },

        { sprite = "crafted_01_11", x = 10094, y = 8259, z = 3, enabled = "EnableWaterSystem", }, -- invisible "tank" to simulate the well

        { sprite = "constructedobjects_01_45", x = 10058, y = 8236, z = 0, clearExisting = true, isContainer = true, },
        { sprite = "carpentry_01_16", x = 10095, y = 8262, z = 0, clearExisting = true, isContainer = true, },

        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10088, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10082, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_105", x = 10081, y = 8254, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_logs_8", x = 10101, y = 8260, z = 0, },
    },
    loot = {
        {
            type = 'container',
            coords = {x = 10095, y = 8262, z = 0},
            special = "essentials",
        },

        -- first floor
        -- office
        {
            type = 'container',
            coords = {x=10093,y=8256,z=1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=10097,y=8254,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=10098,y=8254,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=10093,y=8257,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        -- sitting area
        {
            type = 'container',
            coords = {x=10095,y=8257,z=1.5},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8257,z=1.5},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10100,y=8261,z=1},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.VHS_Retail', chance = 1, count = {3,3} },
            },
            randUntilFull = true,
        },
        {
            type = 'container',
            coords = {x=10099,y=8261,z=2},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10100,y=8260,z=1},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8260,z=1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=10093,y=8261,z=1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10092,y=8262,z=1},
            dist = {"CrateInstruments"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10091,y=8262,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10088,y=8254,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10089,y=8254,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- near stairs
        {
            type = 'container',
            coords = {x=10092,y=8254,z=1},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10092,y=8255,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10092,y=8255,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10089,y=8258,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10089,y=8259,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10089,y=8260,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=10088,y=8260,z=1},
            dist = {"StoreKitchenButcher", "CrateFlour", "CrateOilVegetable", "StoreKitchenSauce", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8260,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8260,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8261,z=1},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8262,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8262,z=1.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8263,z=1},
            dist = {"CatfishKitchenFridge", "ChineseKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8263,z=1.5},
            dist = {"StoreKitchenBaking",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8264,z=1},
            dist = {"WesternKitchenFreezer",},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        -- master bedroom
        {
            type = 'container',
            coords = {x=10080,y=8263,z=1},
            dist = {"FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10080,y=8260,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10080,y=8257,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10081,y=8257,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- mb closet
        {
            type = 'container',
            coords = {x=10088,y=8257,z=1},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10087,y=8257,z=1},
            dist = {"CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10086,y=8257,z=1},
            dist = {"SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8257,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8257,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10088,y=8259,z=1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10087,y=8259,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10086,y=8259,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8259,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- mb bath
        {
            type = 'container',
            coords = {x=10080,y=8254,z=1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- top floor
        {
            type = 'container',
            coords = {x=10083,y=8258,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10083,y=8259,z=2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10083,y=8261,z=2},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10087,y=8262,z=2},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x=10084,y=8260,z=2},
            dist = {"SafehouseTraps", "ArmyStorageAmmunition"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8263,z=2},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8257,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10091,y=8257,z=2},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8260,z=2.5},
            dist = {"MedicalCabinet"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8255,z=2},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10092,y=8255,z=2},
            dist = {"BathroomCounter", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- first floor
        -- butcher room
        {
            type = 'container',
            coords = {x=10090,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10091,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable", "SeafoodKitchenSauce"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8252,z=0},
            dist = {"CrateFlour", "CrateOilVegetable", "StoreKitchenCutlery"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8254,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "FreezerRich"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8255,z=0},
            dist = {"ArenaKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        -- hallway
        {
            type = 'container',
            coords = {x=10092,y=8256,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8256,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10091,y=8258,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8258,z=0},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        -- storage room with generator
        {
            type = 'container',
            coords = {x=10089,y=8261,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10089,y=8262,z=0},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8258,z=0},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8259,z=0},
            dist = {"LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10085,y=8263,z=0},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=10085,y=8264,z=0},
            dist = {"CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10086,y=8264,z=0},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- garage area
        {
            type = 'container',
            coords = {x=10082,y=8257,z=0},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10081,y=8257,z=0.5},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8257,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10084,y=8258,z=0},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- more hallway
        {
            type = 'container',
            coords = {x=10078,y=8255,z=0},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10078,y=8256,z=0},
            dist = {"ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10081,y=8254,z=0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10082,y=8254,z=0},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- more hallway other side of stairs
        {
            type = 'container',
            coords = {x=10099,y=8263,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8264,z=0},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8265,z=0},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },

        {
            type = 'container',
            coords = {x=10095,y=8261,z=0},
            items = {
                { name = 'Base.NailsCarton', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10095,y=8260,z=0},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {2,5} },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10095,y=8258,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10095,y=8257,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10100,y=8262,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10098,y=8257,z=0},
            dist = {"ToolFactoryBarStock"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8257,z=0},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- food storage area
        {
            type = 'container',
            coords = {x=10099,y=8254,z=0},
            dist = {"FreezerGarage" },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10098,y=8254,z=0},
            dist = {"FreezerGarage" },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10097,y=8256,z=0},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10098,y=8256,z=0},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },

        -- shop building
        {
            type = 'container',
            coords = {x=10108,y=8248,z=0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10117,y=8243,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10117,y=8242,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10117,y=8239,z=0},
            dist = {"CrateBlacksmithing", "MetalShopTools", "MetalWorkerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10114,y=8239,z=0.5},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- fishing building
        {
            type = 'container',
            coords = {x=10092,y=8282,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8282,z=0},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10093,y=8279,z=0},
            dist = {"FishingStoreGear", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10094,y=8279,z=0},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10095,y=8279,z=0},
            dist = { "SushiKitchenBaking"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10090,y=8280,z=0},
            dist = {"SushiKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8279,z=0},
            dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8280,z=0},
            dist = {"ArtStorePottery"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10099,y=8282,z=0},
            dist = {"TestingLab", "TobaccoStoreAccessories", "ToolStoreAccessories", "ArtStorePottery", "ArtSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },

        -- crate near chicken pen
        {
            type = 'container',
            coords = {x=10056,y=8236,z=0},
            dist = {"BarnTools", "CrateAnimalFeed", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10058,y=8236,z=0},
            dist = {"CrateGravelBags", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- woodpile
        {
            type = 'container',
            coords = {x=10115,y=8260,z=0},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
    },
}

return McCoyEstate

-- ArtStorePottery ArtSupplies
-- CrateBlacksmithing CrateCarpentry CrateMechanics CrateMetalwork