local wtc = {x = 13453, y = 1884, z = -2,}
local CentralLVilleMansion = {
    spawn = { x = 13441, y = 1895, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 13459, y = 1884, z = -2, },
            chunks = {
                {1678, 236},
                {1678, 237},
                {1678, 238},
                {1679, 236},
                {1679, 237},
                {1679, 238},
                {1680, 236},
                {1680, 237},
                {1680, 238},
                {1679, 239},
                {1677, 233},
                {1677, 234},
                {1677, 235},
                {1677, 236},
                {1677, 237},
                {1678, 233},
                {1678, 234},
                {1678, 235},
                {1679, 233},
                {1679, 234},
                {1679, 235},
                {1680, 233},
                {1680, 234},
                {1680, 235},
                {1681, 233},
                {1681, 234},
                {1681, 235},
                {1681, 236},
                {1681, 237},
                {1682, 233},
                {1682, 234},
                {1682, 235},
                {1682, 236},
                {1682, 237},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_72", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = 13459, y = 1884, z = -2} },
        { sprite = "industry_02_72", x = 13458, y = 1887, z = -2, sourceType="generator", source = {x = 13459, y = 1884, z = -2} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_13", x = 13431, y = 1906, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_19", x = 13438, y = 1904, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 13440, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_20", x = 13441, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_2", x = 13442, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- 2nd floor
        { sprite = "fixtures_bathroom_01_52", x = 13431, y = 1901, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_32", x = 13431, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 13432, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 13433, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_2", x = 13438, y = 1893, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_3", x = 13438, y = 1892, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 13437, y = 1891, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement
        -- decon
        { sprite = "fixtures_bathroom_01_31", x = 13436, y = 1904, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_31", x = 13436, y = 1903, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_31", x = 13436, y = 1902, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- security bathroom
        { sprite = "fixtures_bathroom_01_33", x = 13429, y = 1902, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_3", x = 13431, y = 1902, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_3", x = 13431, y = 1901, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 13429, y = 1899, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_11", x = 13431, y = 1899, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- family suite
        { sprite = "fixtures_sinks_01_1", x = 13445, y = 1897, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 13449, y = 1893, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_1", x = 13445, y = 1892, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_1", x = 13449, y = 1888, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- laundry
        { sprite = "appliances_laundry_01_0", x = 13445, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_0", x = 13447, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_0", x = 13449, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_17", x = 13451, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- showers
        { sprite = "fixtures_sinks_01_1", x = 13452, y = 1881, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_3", x = 13455, y = 1881, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_30", x = 13456, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_4", x = 13457, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_30", x = 13458, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_4", x = 13459, y = 1878, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_22", x = 13456, y = 1882, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_7", x = 13457, y = 1882, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_22", x = 13458, y = 1882, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_7", x = 13459, y = 1882, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- infirmary
        { sprite = "fixtures_sinks_01_16", x = 13419, y = 1893, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- main room
        { sprite = "fixtures_sinks_01_25", x = 13434, y = 1885, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_32", x = 13434, y = 1876, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Louisville Safehouse",
        doors = {
            { sprite = "location_community_church_small_01_2", x = 13431, y = 1897, z = 0, },
            { sprite = "fixtures_doors_01_33", x = 13439, y = 1902, z = -2, },
        },
    },
    map = { name = "DWAPStashMap19", },
    objectSpawns = {
        { sprite = "camping_01_64", x = 13442, y = 1902, z = 0, enabled = "EnableWaterSystem", }, -- fountain

        -- { sprite = "industry_02_72", x = 13434, y = 1908, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank left
        -- { sprite = "industry_02_73", x = 13435, y = 1908, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, --tank right
        -- { sprite = "industry_02_74", x = 13434, y = 1907, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back left
        -- { sprite = "industry_02_75", x = 13435, y = 1907, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back right

        -- { sprite = "industry_02_64", x = 13436, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
        -- { sprite = "industry_02_68", x = 13436, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_65", x = 13437, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_69", x = 13437, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_66", x = 13438, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_70", x = 13438, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_67", x = 13439, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        -- { sprite = "industry_02_71", x = 13439, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },

        { x = 13431, y = 1905, z = 0, clearExisting = true, },
        { x = 13432, y = 1905, z = 0, clearExisting = true, },
        { x = 13433, y = 1905, z = 0, clearExisting = true, },
        { x = 13434, y = 1905, z = 0, clearExisting = true, },
        { x = 13431, y = 1906, z = 0, clearExisting = true, },
        -- { sprite = "fixtures_railings_01_36", x = 13432, y = 1908, z = 0, clearExisting = false, },
        -- { sprite = "fixtures_railings_01_36", x = 13432, y = 1909, z = 0, clearExisting = false, },
        -- { sprite = "fixtures_railings_01_36", x = 13432, y = 1910, z = 0, clearExisting = false, },

        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1914, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1913, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1912, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1911, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1910, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1909, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13435, y = 1908, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1914, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1913, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1912, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1911, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1910, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1909, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13436, y = 1908, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1914, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1913, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1912, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1911, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1910, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1909, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13437, y = 1908, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1914, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1913, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1912, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1911, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1910, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1909, z = -1, clearExisting = false, },
        -- { sprite = "floors_exterior_street_01_0", x = 13438, y = 1908, z = -1, clearExisting = false, },
        -- { sprite = "fixtures_railings_01_36", x = 13435, y = 1913, z = -1, clearExisting = false, },
        -- { sprite = "fixtures_railings_01_36", x = 13435, y = 1914, z = -1, clearExisting = false, },
        -- { sprite = "fixtures_railings_01_36", x = 13435, y = 1915, z = -1, clearExisting = false, },
        -- { x = 13434, y = 1914, z = -1, clearExisting = true, },
        -- { x = 13434, y = 1915, z = -1, clearExisting = true, },

        -- attic crates
        { sprite = "constructedobjects_01_45", x = 13432, y = 1896, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13432, y = 1901, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13437, y = 1901, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13438, y = 1894, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13439, y = 1894, z = 2, isContainer = true, },

        -- shelf replacements
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+7, z = bunkerTopLeft.z, renderYOffset = 0, enabled = "Loot", clearExisting = true, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+7, z = bunkerTopLeft.z, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+6, z = bunkerTopLeft.z, renderYOffset = 0, enabled = "Loot", clearExisting = true, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+6, z = bunkerTopLeft.z, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+5, z = bunkerTopLeft.z, renderYOffset = 0, enabled = "Loot", clearExisting = true, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+5, z = bunkerTopLeft.z, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y, z = bunkerTopLeft.z, renderYOffset = 0, enabled = "Loot", clearExisting = true, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y, z = bunkerTopLeft.z, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+1, z = bunkerTopLeft.z, renderYOffset = 0, enabled = "Loot", clearExisting = true, isContainer = true, },
        -- { sprite = "location_military_generic_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+1, z = bunkerTopLeft.z, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },

        -- { sprite = "furniture_tables_high_01_16", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+2, z = bunkerTopLeft.z, clearExisting = true },
        -- { sprite = "appliances_com_01_0", x = bunkerTopLeft.x+2, y = bunkerTopLeft.y+2, z = bunkerTopLeft.z,  IsoType = "IsoRadio" }, -- renderYOffset = 34,

        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1903, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1902, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1900, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="location_community_church_small_01_28", x = 13431, y = 1898, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="location_community_church_small_01_24", x = 13431, y = 1897, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1895, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1893, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1892, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13432, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13433, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13435, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13437, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13438, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_48", x = 13441, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_49", x = 13442, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_50", x = 13443, y = 1891, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_28", x = 13445, y = 1893, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_interior_house_03_29", x = 13435, y = 1911, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_29", x = 13432, y = 1911, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_29", x = 13438, y = 1905, z = 0, },
    },
    loot = {
        --- Basement ---
        { -- decon locker
            type = 'container',
            coords = {x = 13438, y = 1902, z = -2},
            items = {
                { name = 'Base.Bag_ProtectiveCaseBulkyHazard', },
                { name = 'Base.Hat_NBCmask', },
                { name = 'Base.Glasses_SafetyGoggles', },
                { name = 'Base.Hat_BuildersRespirator', },
                { name = 'Base.HazmatSuit', },
                { name = 'Base.RespiratorFilters', },
                { name = 'Base.Hat_GasMask', },
                { name = 'Base.GasmaskFilter', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- decon locker
            type = 'container',
            coords = {x = 13438, y = 1904, z = -2},
            items = {
                { name = 'Base.Oxygen_Tank', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- short locker
            type = 'container',
            coords = {x = 13442, y = 1901, z = -2},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- short locker
            type = 'container',
            coords = {x = 13441, y = 1901, z = -2},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- desk
            type = 'container',
            coords = {x = 13438, y = 1899, z = -2},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- locker
            type = 'container',
            coords = {x = 13435, y = 1899, z = -2},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        { -- locker
            type = 'container',
            coords = {x = 13435, y = 1902, z = -2},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy", "RandomFiller"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- mil locker
            type = 'container',
            coords = {x = 13432, y = 1899, z = -2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- mil locker
            type = 'container',
            coords = {x = 13432, y = 1902, z = -2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- bathroom
            type = 'container',
            coords = {x = 13431, y = 1901, z = -2},
            dist = {"JanitorCleaning","MedicalCabinet","MedicalClinicDrugs", "CrateLinens"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 13431, y = 1901, z = -1.5},
            dist = {"BathroomCounter", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        --------------------------
        ----- Recreation Area ----
        --------------------------
        { -- bar
            type = 'container',
            coords = {x = 13442, y = 1897, z = -2},
            dist = {"LiquorStoreMix", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- bar
            type = 'container',
            coords = {x = 13442, y = 1896, z = -2},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- bar
            type = 'container',
            coords = {x = 13442, y = 1895, z = -2},
            dist = {"LiquorStoreBrandy", "LiquorStoreGin"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- movie snack stand
            type = 'container',
            coords = {x = 13438, y = 1890, z = -2},
            dist = {"TheatreDrinks", "TheatreSnacks"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- movie snack stand
            type = 'container',
            coords = {x = 13437, y = 1890, z = -2},
            dist = {"TheatrePopcorn", "TheatreSnacks"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        ------------------------------
        ----- Kitchen/Dining Area ----
        ------------------------------
        { -- under drink machine
            type = 'container',
            coords = {x = 13434, y = 1882, z = -2},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- under toaster
            type = 'container',
            coords = {x = 13434, y = 1878, z = -2},
            dist = {"StoreKitchenBaking", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13434, y = 1877, z = -2},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13434, y = 1875, z = -2},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- under microwave
            type = 'container',
            coords = {x = 13438, y = 1877, z = -2},
            dist = {"KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1876, z = -2},
            dist = {"KitchenDryFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1875, z = -2},
            dist = {"SafehouseFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- drink stand
            type = 'container',
            coords = {x = 13441, y = 1877, z = -2},
            dist = {"KitchenBottles", "CrateSodaCans", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- drink stand
            type = 'container',
            coords = {x = 13443, y = 1877, z = -2},
            dist = {"KitchenBottles", "CrateSodaCans", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- ice freezer
            type = 'container',
            coords = {x = 13444, y = 1875, z = -2},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- ice freezer
            type = 'container',
            coords = {x = 13443, y = 1875, z = -2},
            dist = {"PizzaKitchenFreezer", "PizzaKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- coolers
            type = 'container',
            coords = {x = 13442, y = 1875, z = -2},
            dist = {"SafehouseFridge"},
            frozen = true,
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13441, y = 1875, z = -2},
            dist = {"UniversityFridge"},
            frozen = true,
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13440, y = 1875, z = -2},
            dist = {"WesternKitchenFridge"},
            frozen = true,
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        ------------------------------
        --- Library and School Area --
        ------------------------------
        {
            type = 'container',
            coords = {x = 13425, y = 1897, z = -2},
            dist = {"LivingRoomShelfClassy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 13425, y = 1896, z = -2},
            dist = {"CrateBooks", "BookstoreChilds", "CrateMagazines"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 13428, y = 1897, z = -2},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x = 13429, y = 1897, z = -2},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x = 13430, y = 1897, z = -2},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x = 13431, y = 1897, z = -2},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- desk
            type = 'container',
            coords = {x = 13430, y = 1893, z = -2},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- desk
            type = 'container',
            coords = {x = 13432, y = 1893, z = -2},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        -----------------
        --- Infirmary ---
        -----------------
        {
            type = 'container',
            coords = {x = 13419, y = 1897, z = -2},
            dist = {"SafehouseMedical_Late", "StoreShelfMedical", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 13419, y = 1896, z = -2},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 13419, y = 1895, z = -2},
            dist = {"MedicalClinicDrugs" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 13419, y = 1893, z = -2},
            dist = {"MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        --------------------
        ----- Gun Range ----
        --------------------
        {
            type = 'container',
            coords = {x = 13433, y = 1872, z = -2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13433, y = 1872, z = -2},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13430, y = 1869, z = -2},
            dist = {"GunStoreMagsAmmo", "GunStoreAmmunition", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13430, y = 1873, z = -2},
            dist = {"GunStoreMagsAmmo", "GunStoreAmmunition", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        ---------------------------
        ----- Workroom / Power ----
        ---------------------------
        {
            type = 'container',
            coords = {x = 13445, y = 1886, z = -2},
            dist = {"CrateCarpentry","LoggingFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13445, y = 1884, z = -2},
            dist = {"RadioFactoryComponents", "CrateElectronics", "ArmyStorageElectronics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13445, y = 1883, z = -2},
            dist = {"ToolCabinetMechanics","CrateMechanics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13447, y = 1883, z = -2},
            dist = {"RailYardSpikes", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13449, y = 1883, z = -2},
            dist = {"ToolStoreMetalwork","ToolStoreMisc", "ToolStoreTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13450, y = 1883, z = -2},
            dist = {"CrateTailoring", "CrateFabric_Cotton", "CrateFabric_DenimBlack", "CrateLeather","SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x = 13450, y = 1885, z = -2},
            dist = {"GolfFactoryTools","KnifeFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13451, y = 1883, z = -2},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13451, y = 1884, z = -2},
            dist = {"CrateCarpentry","MannequinFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13451, y = 1885, z = -2},
            dist = {"WireFactoryBarbed", "CrateLongStick", "WireFactoryBasic"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13451, y = 1886, z = -2},
            dist = {"RailYardTools","Homesteading","SurvivalGear"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -----------------------
        ----- Laundry Room ----
        -----------------------
        {
            type = 'container',
            coords = {x = 13445, y = 1882, z = -2},
            dist = {"ArmyHangarOutfit", "ArmyStorageOutfit", "ArmySurplusOutfit", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13446, y = 1882, z = -2},
            dist = {"CrateClothesRandom"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13447, y = 1882, z = -2},
            dist = {"DrugLabOutfit", "MechanicOutfit", "WildWestClothing"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13448, y = 1882, z = -2},
            dist = {"BackstageClothingRack", "ArmySurplusOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13449, y = 1882, z = -2},
            dist = {"ClothingStorageWinter", "GymLaundry"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13450, y = 1882, z = -2},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- counter under sink
            type = 'container',
            coords = {x = 13451, y = 1878, z = -2},
            dist = {"LaundryCleaning"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        ----------------------
        ----- Shower Room ----
        ----------------------
        { -- counter under sink
            type = 'container',
            coords = {x = 13455, y = 1881, z = -2},
            dist = {"BathroomCabinet", "BathroomCounter","BathroomShelf"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- counter under sink
            type = 'container',
            coords = {x = 13452, y = 1881, z = -2},
            dist = {"CrateToiletPaper", "CrateLinens","GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        --------------
        ----- Gym ----
        --------------
        {
            type = 'container',
            coords = {x = 13429, y = 1882, z = -2},
            dist = {"FitnessTrainer"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 13430, y = 1882, z = -2},
            dist = {"CrateFitnessWeights"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -----------------------------
        ----- Warehouse Freezers ----
        -----------------------------
        {
            type = 'container',
            coords = {x = 13437, y = 1870, z = -2},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1870, z = -2},
            dist = {"WesternKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13440, y = 1870, z = -2},
            dist = {"ArenaKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13441, y = 1870, z = -2},
            dist = {"BurgerKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1872, z = -2},
            dist = {"ButcherFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1872, z = -2},
            dist = {"CafeteriaKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13440, y = 1872, z = -2},
            dist = {"DeepFryKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13441, y = 1872, z = -2},
            dist = {"CatfishKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        --------------------
        ----- Warehouse ----
        --------------------
        {
            type = 'container',
            coords = {x = 13434, y = 1869, z = -2},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13435, y = 1869, z = -2},
            dist = {"CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13436, y = 1869, z = -2},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1869, z = -2},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1869, z = -2},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13434, y = 1873, z = -2},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13435, y = 1873, z = -2},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13436, y = 1873, z = -2},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1873, z = -2},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1873, z = -2},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- ⬆ West of door way ⬇ East of door way
        {
            type = 'container',
            coords = {x = 13440, y = 1869, z = -2},
            dist = {"GigamartDryGoods", "CafeKitchenCoffee"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13441, y = 1869, z = -2},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13440, y = 1873, z = -2},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13441, y = 1873, z = -2},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13443, y = 1869, z = -2},
            dist = {"HuntingLockers", "RangerTools", "CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x = 13443, y = 1870, z = -2},
            dist = {"Trapper", "CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x = 13447, y = 1869, z = -2},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13447, y = 1870, z = -2},
            dist = {"CrateAntiqueStove", "CampingStoreLighting"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x = 13449, y = 1869, z = -2},
            dist = {"ArmyStorageAmmunition", "SafehouseTraps", "GunStoreKnives",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13449, y = 1870, z = -2},
            dist = {"ArmyStorageGuns","ArmyStorageAmmunition","FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- south side crates
        {
            type = 'container',
            coords = {x = 13444, y = 1873, z = -2},
            dist = {"SewingStoreTools","SewingStoreFabric", "CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x = 13445, y = 1873, z = -2},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13446, y = 1873, z = -2},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13447, y = 1873, z = -2},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13448, y = 1873, z = -2},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13449, y = 1873, z = -2},
            dist = {"CrateLiquor", "LiquorStoreBrandy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13450, y = 1873, z = -2},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13451, y = 1873, z = -2},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },

        -- garage
        -- {
        --     type = 'container',
        --     coords = {x = 13435, y = 1905, z = 0},
        --     dist = {"GasStoreEmergency","StoreCounterTobacco"},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_ToolsLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 13434, y = 1905, z = 0},
        --     dist = {"CarSupplyTools", "GasStorageMechanics",},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_ToolsLevel",
        -- },
        {
            type = 'container',
            coords = {x = 13434, y = 1909, z = 0},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13435, y = 1909, z = 0},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13433, y = 1909, z = 0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13432, y = 1909, z = 0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- kitchen
        { -- fridge
            type = 'container',
            coords = {x = 13440, y = 1904, z = 0},
            dist = {"WesternKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13439, y = 1904, z = 0},
            dist = {"KitchenDryFood",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1904, z = 0},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1904, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1904, z = 0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1903, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1903, z = 0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1901, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1901, z = 0.5},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1900, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1900, z = 0.5},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1899, z = 0},
            dist = {"CrateTortillaChips", "CandyStoreSnacks","FridgeSoda",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1899, z = 0.5},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1899, z = 0},
            dist = {"WesternKitchenSauce", "WhiskeyBottlingFull", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- laundry
        {
            type = 'container',
            coords = {x=13444,y=1897,z=0.5},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1898,z=0},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- office
        {
            type = 'container',
            coords = {x=13441,y=1891,z=0},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x=13440,y=1891,z=0},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1892,z=0},
            dist = {"BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1893,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1894,z=0},
            dist = {"SafehouseTraps", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1893,z=0},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1892,z=0},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1891,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- piano room
        {
            type = 'container',
            coords = {x=13436,y=1891,z=0},
            dist = {"FirearmWeapons_Late","ArmyStorageAmmunition",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1894,z=0},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- dining room
        {
            type = 'container',
            coords = {x=13431,y=1899,z=0},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1899,z=0},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs","MedicalCabinet"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- 2nd floor
        {
            type = 'container',
            coords = {x=13431,y=1897,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1896,z=1},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1895,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1891,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1891,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1904,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1903,z=1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1902,z=1},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13435,y=1902,z=1},
            dist = {"SewingStoreFabric","CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13438,y=1902,z=1},
            dist = {"SewingStoreFabric","CrateLeather", "ArtSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1894,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=13441,y=1893,z=1},
            dist = {"LivingRoomShelfClassy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13441,y=1892,z=1},
            dist = {"CrateVHSTapes","BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1894,z=1},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1896,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1893,z=1},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1893,z=1},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1892,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1891,z=1},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- attic
        {
            type = 'container',
            coords = {x=13432,y=1896,z=2},
            dist = {"BarnTools", "CrateAnimalFeed", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=13432,y=1901,z=2},
            dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13437,y=1901,z=2},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13438,y=1894,z=2},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1894,z=2},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1895,z=2},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1894,z=2},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13435,y=1894,z=2},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then

    table.insert(CentralLVilleMansion.objectSpawns, { sprite = "walls_interior_house_03_43", x = 13451, y = 1874, z = 0, clearExisting = true, })
    table.insert(CentralLVilleMansion.objectSpawns, { sprite = "fixtures_doors_01_5", x = 13451, y = 1874, z = 0, isDoor = true, doorN = true, })
    table.insert(CentralLVilleMansion.objectSpawns, { sprite = "walls_interior_house_03_33", x = 13452, y = 1874, z = 0, removeFloor = true, clearExisting = true, })
    table.insert(CentralLVilleMansion.objectSpawns, { sprite = "walls_interior_house_03_32", x = 13453, y = 1874, z = 0, })
else
    table.insert(CentralLVilleMansion.objectSpawns, { sprite = "industry_trucks_01_50", x = 13452, y = 1874, z = -2, removeWall = "north", })
end
-- if FA is activated, plumb the soda machines
if getActivatedMods():contains("\\FunctionalAppliances2") then
    table.insert(CentralLVilleMansion.waterFixtures, { sprite = "location_shop_zippee_01_57", x = 13434, y = 1883, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} })
    table.insert(CentralLVilleMansion.waterFixtures, { sprite = "location_shop_accessories_01_9", x = 13434, y = 1882, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} })
end

return CentralLVilleMansion