-- @TODO really need to redo this one with a full custom basement instead of all the object overrides.
local wtc = {x = 13435, y = 1908, z = -1,}
local bunkerTopLeft = {x = 13432, y = 1904, z = -2}
local CentralLVilleMansion = {
    spawn = { x = 13441, y = 1895, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 13439, y = 1907, z = -1, },
            chunks = {
                {1678, 236},
                {1678, 237},
                {1678, 238},
                {1679, 236},
                {1679, 237},
                {1679, 238},
                {1680, 236},
                {1680, 237},
                {1680, 238},
                {1678, 238},
                {1679, 238},
                {1679, 239},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, isProp = true, sourceType="generator", source = {x = 13439, y = 1907, z = -1} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_13", x = 13431, y = 1906, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_19", x = 13438, y = 1904, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_3", x = 13440, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_20", x = 13441, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "appliances_laundry_01_2", x = 13442, y = 1898, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- 2nd floor
        { sprite = "fixtures_bathroom_01_52", x = 13431, y = 1901, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_32", x = 13431, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_0", x = 13432, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_22", x = 13433, y = 1898, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_2", x = 13438, y = 1893, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_3", x = 13438, y = 1892, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_26", x = 13437, y = 1891, z = 1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },

        -- basement
        { sprite = "fixtures_sinks_01_32", x = 13431, y = 1907, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_16", x = 13432, y = 1908, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_6", x = 13434, y = 1912, z = -2, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    doorKeys = {
        name = "Louisville Safehouse",
        doors = {
            { sprite = "location_community_church_small_01_2", x = 13431, y = 1897, z = 0, },
        },
    },
    map = { name = "DWAPStashMap19", },
    objectSpawns = {
        { sprite = "camping_01_64", x = 13442, y = 1902, z = 0, enabled = "EnableWaterSystem", }, -- fountain

        { sprite = "industry_02_72", x = 13434, y = 1908, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank left
        { sprite = "industry_02_73", x = 13435, y = 1908, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, --tank right
        { sprite = "industry_02_74", x = 13434, y = 1907, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back left
        { sprite = "industry_02_75", x = 13435, y = 1907, z = -1, enabled = "EnableWaterSystem", clearExisting = true, }, -- tank back right

        { sprite = "industry_02_64", x = 13436, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, }, -- generator
        { sprite = "industry_02_68", x = 13436, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_65", x = 13437, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_69", x = 13437, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_66", x = 13438, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_70", x = 13438, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_67", x = 13439, y = 1908, z = -1, enabled = "EnableGenSystem", clearExisting = true, },
        { sprite = "industry_02_71", x = 13439, y = 1907, z = -1, enabled = "EnableGenSystem", clearExisting = true, },

        { x = 13431, y = 1907, z = 0, clearExisting = true, },
        { x = 13431, y = 1908, z = 0, clearExisting = true, },
        { x = 13431, y = 1909, z = 0, clearExisting = true, },
        { x = 13431, y = 1910, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 13432, y = 1908, z = 0, clearExisting = false, },
        { sprite = "fixtures_railings_01_36", x = 13432, y = 1909, z = 0, clearExisting = false, },
        { sprite = "fixtures_railings_01_36", x = 13432, y = 1910, z = 0, clearExisting = false, },

        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1914, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1913, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1912, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1911, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1910, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1909, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13435, y = 1908, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1914, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1913, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1912, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1911, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1910, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1909, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13436, y = 1908, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1914, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1913, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1912, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1911, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1910, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1909, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13437, y = 1908, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1914, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1913, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1912, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1911, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1910, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1909, z = -1, clearExisting = false, },
        { sprite = "floors_exterior_street_01_0", x = 13438, y = 1908, z = -1, clearExisting = false, },
        { sprite = "fixtures_railings_01_36", x = 13435, y = 1913, z = -1, clearExisting = false, },
        { sprite = "fixtures_railings_01_36", x = 13435, y = 1914, z = -1, clearExisting = false, },
        { sprite = "fixtures_railings_01_36", x = 13435, y = 1915, z = -1, clearExisting = false, },
        { x = 13434, y = 1914, z = -1, clearExisting = true, },
        { x = 13434, y = 1915, z = -1, clearExisting = true, },

        -- attic crates
        { sprite = "constructedobjects_01_45", x = 13432, y = 1896, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13432, y = 1901, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13437, y = 1901, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13438, y = 1894, z = 2, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 13439, y = 1894, z = 2, isContainer = true, },

        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1903, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1902, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1900, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="location_community_church_small_01_28", x = 13431, y = 1898, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="location_community_church_small_01_24", x = 13431, y = 1897, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1895, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1893, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_10", x = 13431, y = 1892, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13432, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13433, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13435, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13437, y = 1891, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="walls_interior_house_05_11", x = 13438, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_48", x = 13441, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_49", x = 13442, y = 1891, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_50", x = 13443, y = 1891, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_28", x = 13445, y = 1893, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_interior_house_03_29", x = 13435, y = 1911, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_29", x = 13432, y = 1911, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_29", x = 13438, y = 1905, z = 0, },
    },
    loot = {
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            dist = {"GunCache1.GunBox", "GunCache1.Bag_DuffelBagTINT"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            special = "essentials",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        -- garage
        {
            type = 'container',
            coords = {x = 13435, y = 1905, z = 0},
            dist = {"GasStoreEmergency","StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13434, y = 1905, z = 0},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13434, y = 1909, z = 0},
            items = {
                { name = 'Base.NailsCarton', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13435, y = 1909, z = 0},
            items = {
                { name = 'Base.ScrewsCarton', chance = 1, count = {1,3} },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13433, y = 1909, z = 0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 13432, y = 1909, z = 0},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- basement
        {
            type = 'container',
            coords = {x = 13432, y = 1910, z = -0.5},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13432, y = 1909, z = -1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13432, y = 1908, z = -1},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 13436, y = 1909, z = -1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1909, z = -1},
            dist = {"KitchenDryFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1909, z = -1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1910, z = -1},
            dist = {"WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1910, z = -1},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1911, z = -1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1914, z = -1},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x = 13436, y = 1914, z = -1},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- kitchen
        { -- fridge
            type = 'container',
            coords = {x = 13440, y = 1904, z = 0},
            dist = {"WesternKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13439, y = 1904, z = 0},
            dist = {"KitchenDryFood",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1904, z = 0},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1904, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1904, z = 0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1903, z = 0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1903, z = 0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1901, z = 0},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1901, z = 0.5},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1900, z = 0},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1900, z = 0.5},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1899, z = 0},
            dist = {"CrateTortillaChips", "CandyStoreSnacks","FridgeSoda",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13437, y = 1899, z = 0.5},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 13438, y = 1899, z = 0},
            dist = {"WesternKitchenSauce", "WhiskeyBottlingFull", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- laundry
        {
            type = 'container',
            coords = {x=13444,y=1897,z=0.5},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1898,z=0},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- office
        {
            type = 'container',
            coords = {x=13441,y=1891,z=0},
            items = {
                { name = 'Base.Pencil', chance = 1, count = {2,5} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.Notebook', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_DigitalBlack', chance = 1, count = {1,1} },
                { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x=13440,y=1891,z=0},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1892,z=0},
            dist = {"BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1893,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1894,z=0},
            dist = {"SafehouseTraps", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1893,z=0},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1892,z=0},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1891,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- piano room
        {
            type = 'container',
            coords = {x=13436,y=1891,z=0},
            dist = {"FirearmWeapons_Late","ArmyStorageAmmunition",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1894,z=0},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- dining room
        {
            type = 'container',
            coords = {x=13431,y=1899,z=0},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1899,z=0},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs","MedicalCabinet"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- 2nd floor
        {
            type = 'container',
            coords = {x=13431,y=1897,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1896,z=1},
            dist = {"FirearmWeapons_Late", "ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1895,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1891,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1891,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1904,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13431,y=1903,z=1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1902,z=1},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13435,y=1902,z=1},
            dist = {"SewingStoreFabric","CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13438,y=1902,z=1},
            dist = {"SewingStoreFabric","CrateLeather", "ArtSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1894,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=13441,y=1893,z=1},
            dist = {"LivingRoomShelfClassy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13441,y=1892,z=1},
            dist = {"CrateVHSTapes","BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=13440,y=1894,z=1},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1896,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13444,y=1893,z=1},
            dist = {"SurvivalGear",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1893,z=1},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1892,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1891,z=1},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- attic
        {
            type = 'container',
            coords = {x=13432,y=1896,z=2},
            dist = {"BarnTools", "CrateAnimalFeed", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=13432,y=1901,z=2},
            dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13437,y=1901,z=2},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=13438,y=1894,z=2},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13439,y=1894,z=2},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1895,z=2},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13434,y=1894,z=2},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=13435,y=1894,z=2},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
    },
}

return CentralLVilleMansion