local wtc1 = {x = 594, y = 9371, z = 0,}
local bunkerTopLeft = {x = 581, y = 9373, z = -2}
local EkronFactory = {
    spawn = { x = 565, y = 9374, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 583, y = 9374, z = -1, },
            chunks = {
                {72, 1171}, -- generator
                {69, 1172},
                {70, 1172},
                {70, 1171},
                {71, 1171},
                {71, 1172},
                {72, 1172},
                {74, 1171},
                {74, 1172},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 583, y = 9374, z = -1} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_52", x = 564, y = 9375, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_13", x = 564, y = 9376, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_8", x = 564, y = 9378, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_29", x = 576, y = 9376, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_29", x = 576, y = 9377, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
    },
    doorKeys = {
        name = "Ekron Factory",
        doors = {
            { sprite = "fixtures_doors_01_44", x = 576, y = 9379, z = 0, },
        },
    },
    map = { name = "DWAPStashMap21", },
    objectSpawns = {
        { x = 583, y = 9382, z = -1, clearExisting = true, },
        { sprite = "lighting_outdoor_01_33", x = 579, y = 9375, z = -1, isLightSwitch = true, },
        { sprite = "lighting_outdoor_01_33", x = 583, y = 9381, z = -1, isLightSwitch = true, },
        { sprite = "lighting_outdoor_01_32", x = 578, y = 9378, z = -1, isLightSwitch = true, },
        { sprite = "lighting_outdoor_01_32", x = 573, y = 9378, z = -1, isLightSwitch = true, },
        { sprite = "appliances_cooking_01_16", x = 564, y = 9374, z = 1, isFireplace = true,},

        { sprite = "constructedobjects_01_45", x = 576, y = 9371, z = 1, enabled = "Loot", clearExisting = true, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 576, y = 9371, z = 1, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 576, y = 9371, z = 1, renderYOffset = 64, enabled = "Loot", clearExisting = false, isContainer = true, },

        { sprite = "constructedobjects_01_45", x = 575, y = 9371, z = 1, enabled = "Loot", clearExisting = true, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 575, y = 9371, z = 1, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 575, y = 9371, z = 1, renderYOffset = 64, enabled = "Loot", clearExisting = false, isContainer = true, },

        { x = 574, y = 9372, z = 1, enabled = "Loot", clearExisting = true, },
        { sprite = "constructedobjects_01_45", x = 574, y = 9371, z = 1, enabled = "Loot", clearExisting = true, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 574, y = 9371, z = 1, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 574, y = 9371, z = 1, renderYOffset = 64, enabled = "Loot", clearExisting = false, isContainer = true, },

        { sprite = "constructedobjects_01_45", x = 573, y = 9371, z = 1, enabled = "Loot", clearExisting = true, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 573, y = 9371, z = 1, renderYOffset = 32, enabled = "Loot", clearExisting = false, isContainer = true, },
        { sprite = "constructedobjects_01_45", x = 573, y = 9371, z = 1, renderYOffset = 64, enabled = "Loot", clearExisting = false, isContainer = true, },

        -- hallway kitchen
        { sprite = "fixtures_counters_01_35", x = 564, y = 9378, z = 1, clearExisting = false, },
        { sprite = "fixtures_sinks_01_8", x = 564, y = 9378, z = 1, clearExisting = false, },
        { sprite = "fixtures_counters_01_35", x = 564, y = 9379, z = 1, clearExisting = false, },
        { sprite = "appliances_cooking_01_29", x = 564, y = 9379, z = 1, clearExisting = false, isStove = true, },
        { sprite = "fixtures_counters_01_35", x = 564, y = 9380, z = 1, clearExisting = false, },

        { sprite = "carpentry_01_16", x = 576, y = 9380, z = 1, enabled = "Loot", isContainer = true, },

        { sprite = "furniture_storage_02_1", x = 564, y = 9380, z = 0, clearExisting = false, },
        { sprite = "lighting_outdoor_01_49", x = 566, y = 9378, z = 0, isLightSwitch = true, },
        { sprite = "lighting_outdoor_01_49", x = 581, y = 9378, z = -1, isLightSwitch = true, },

        { barricade = "metalbar", target="walls_commercial_01_84", x = 577, y = 9378, z = 0, },
        { barricade = "metal", target="walls_commercial_01_84", x = 577, y = 9380, z = 0, },
    },
    loot = {
        { -- upper hallway
            type = 'container',
            coords = {x = 576, y = 9380, z = 1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            dist = {"MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z+0.5},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },

        -- 2nd floor
        {
            type = 'container',
            coords = {x=576,y=9371,z=1},
            dist = {"CrateCannedFood", "KitchenCannedFood", "ArmyBunkerKitchen"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=575,y=9371,z=1},
            dist = {"FirearmWeapons_Late", "DrugLabGuns","ArmyStorageGuns","PoliceStorageGuns", "PoliceStorageAmmunition",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=574,y=9371,z=1},
            dist = {"GunStoreKnives","SafehouseTraps", "ArmyStorageAmmunition","CampingStoreBackpacks", "ArmySurplusMisc"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=573,y=9371,z=1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools", "GigamartTools", "JanitorTools", "LoggingFactoryTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=572,y=9371,z=1},
            dist = {"CrateBlacksmithing", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=569,y=9371,z=1},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=566,y=9371,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=575,y=9377,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=572,y=9377,z=1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=569,y=9377,z=1},
            dist = {"BookstoreMilitaryHistory","MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=573,y=9378,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=574,y=9378,z=1},
            dist = { "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=575,y=9378,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=576,y=9378,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor
        {
            type = 'container',
            coords = {x=564,y=9378,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=564,y=9380,z=0},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=575,y=9371,z=0},
            dist = {"SewingStoreTools", "CrateLeather", "SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=572,y=9371,z=0},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=569,y=9371,z=0},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=566,y=9371,z=0},
            dist = {"CarSupplyTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=566,y=9377,z=0},
            dist = {"GigamartDryGoods" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=569,y=9377,z=0},
            dist = {"StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles", "ArtStorePottery", "ArtSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=572,y=9377,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },

        -- hallway kitchen
        {
            type = 'container',
            coords = {x=564,y=9380,z=1},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=564,y=9379,z=1},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=564,y=9378,z=1},
            dist = {"FoodCache1.FoodBox",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },

        -- exterior near water tank
        {
            type = 'container',
            coords = {x=593,y=9374,z=0},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=593,y=9375,z=0},
            dist = {"CrateLumber", "WoodcraftDudeCounter"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=594,y=9375,z=0},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
    },
}

return EkronFactory