local wtc1 = { x = 10888, y = 10028, z = -1, }
local pb1 = { x = 10882, y = 10028, z = -1 }
local CortmanMedical = {
    group = "Muldraugh",
    baseBuildings = {
        { x = 10881, y = 10022, z = 1 },  -- medical clinic house
        { x = 10886, y = 10025, z = -1 }, -- main basement
        { x = 10864, y = 10038, z = 0 },  -- medical clinic
    },
    spawn = { x = 10881, y = 10022, z = 1 },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 10884, y = 10028, z = pb1.z },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 10886, y = 10028, z = -1, },
            fakeGenerators = {
                { x = 10873, y = 10028, z = -1, createTile = true },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType = "generator", source = { x = 10885, y = 10028, z = -1 } },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_8",     x = 10872, y = 10018, z = 0, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 10872, y = 10020, z = 0, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_14",    x = 10873, y = 10020, z = 0, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_4",     x = 10885, y = 10022, z = 0, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_bathroom_01_5",  x = 10876, y = 10028, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_21",    x = 10876, y = 10027, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_21",    x = 10876, y = 10026, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_25", x = 10879, y = 10026, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_2",  x = 10880, y = 10028, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_16",    x = 10880, y = 10023, z = 1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
    },
    doorKeys = {
        name = "Cortman Medical",
        doors = {
            { sprite = "fixtures_doors_02_5",            x = 10879, y = 10028, z = 0, },
            { sprite = "fixtures_doors_02_44",           x = 10871, y = 10037, z = 0, },
            { sprite = "location_community_police_01_5", x = 10864, y = 10035, z = -1, },
            { sprite = "fixtures_doors_01_32",           x = 10865, y = 10036, z = -1, },
        },
    },
    map = { name = "DWAPStashMap22", },
    objectSpawns = {
        { barricade = "metal",        target = "walls_commercial_02_50",                x = 10888, y = 10024, z = 0, },
        { barricade = "metalbar",     target = "walls_commercial_02_49",                x = 10887, y = 10024, z = 0, },
        { barricade = "metal",        target = "walls_commercial_02_48",                x = 10886, y = 10024, z = 0, },
        { barricade = "metalbar",     target = "walls_exterior_house_03_11",            x = 10883, y = 10028, z = 0, },
        { barricade = "metalbar",     target = "walls_exterior_house_03_11",            x = 10873, y = 10028, z = 0, },
        { barricade = "metal",        target = "walls_exterior_house_01_25",            x = 10868, y = 10040, z = 0, },
        { barricade = "metalbar",     target = "walls_exterior_house_01_24",            x = 10866, y = 10042, z = 0, },
        { barricade = "woodhalf",     target = "fixtures_doors_01_40",                  x = 10866, y = 10045, z = 0, },
        { barricade = "metal",        target = "walls_exterior_house_01_25",            x = 10864, y = 10048, z = 0, },
        { barricade = "metal",        target = "walls_exterior_house_01_25",            x = 10864, y = 10048, z = 0, },
        { barricade = "metal",        target = "walls_exterior_house_01_25",            x = 10861, y = 10048, z = 0, },
        { barricade = "metalbar",     target = "walls_interior_house_03_28",            x = 10860, y = 10042, z = 0, },
        { barricade = "metalbar",     target = "location_restaurant_pizzawhirled_01_9", x = 10868, y = 10034, z = 0, },
        { barricade = "metalbar",     target = "walls_interior_house_03_29",            x = 10873, y = 10017, z = 0, },
        { barricade = "woodhalf",     target = "fixtures_doors_02_5",                   x = 10878, y = 10029, z = 0, },
        { barricade = "woodhalf",     target = "walls_commercial_02_54",                x = 10885, y = 10024, z = 1, },
        { barricade = "woodhalf",     target = "walls_commercial_02_55",                x = 10886, y = 10023, z = 1, },
        { barricade = "woodhalf",     target = "walls_commercial_02_55",                x = 10886, y = 10022, z = 1, },
        { barricade = "woodhalf",     target = "walls_commercial_02_54",                x = 10885, y = 10022, z = 1, },
    },
    loot = {
        -- upstairs office
        { -- E1
            note = "shelves @ medicaloffice",
            coords = { x = 10880, y = 10027, z = 1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E2
            note = "shelves @ medicaloffice",
            coords = { x = 10880, y = 10026, z = 1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- E3
            note = "shelves @ medicaloffice",
            coords = { x = 10880, y = 10025, z = 1 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E4
            note = "counter @ medicaloffice",
            coords = { x = 10880, y = 10024, z = 1 },
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E5
            note = "counter @ medicaloffice",
            coords = { x = 10880, y = 10023, z = 1 },
            special = "essentials",
        },
        { -- E6
            note = "desk @ medicaloffice",
            coords = { x = 10882, y = 10026, z = 1 },
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E7
            note = "medicine @ medicaloffice",
            coords = { x = 10881, y = 10020, z = 1 },
            dist = { "LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E8
            note = "medicine @ medicaloffice",
            coords = { x = 10882, y = 10020, z = 1 },
            dist = { "MorgueTools", "MedicalCabinet", "ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E9
            note = "shelves @ medicaloffice",
            coords = { x = 10883, y = 10020, z = 1 },
            dist = { "BookstoreBiography", "MedicalOfficeBooks", "LibraryMedical", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E10
            note = "shelves @ medicaloffice",
            coords = { x = 10884, y = 10020, z = 1 },
            dist = { "CrateVHSTapes" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E11
            note = "desk @ medicaloffice",
            coords = { x = 10885, y = 10022, z = 1 },
            dist = { "MusicStoreCDs" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- bigger upstairs bedroom
        { -- E12
            note = "dresser @ bedroom",
            coords = { x = 10872, y = 10026, z = 1 },
            dist = { "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E13
            note = "dresser @ bedroom",
            coords = { x = 10872, y = 10023, z = 1 },
            dist = { "ArmyStorageOutfit", "DrugLabOutfit", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E14
            note = "wardrobe @ bedroom",
            coords = { x = 10875, y = 10027, z = 1 },
            dist = { "HuntingLockers", "RangerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E15
            note = "wardrobe @ bedroom",
            coords = { x = 10875, y = 10026, z = 1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E16
            note = "dresser @ bedroom",
            coords = { x = 10875, y = 10023, z = 1 },
            dist = { "CrateLiquor" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E17
            note = "shelves @ bedroom",
            coords = { x = 10875, y = 10023, z = 1 },
            slot = "upper",
            dist = { "CrateLiquor" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E18
            note = "shelves @ bedroom",
            coords = { x = 10874, y = 10023, z = 1 },
            slot = "upper",
            dist = { "SafehouseTraps", "ArmyStorageAmmunition" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- 2nd bedroom
        { -- E19
            note = "cardboardbox @ bedroom",
            coords = { x = 10875, y = 10022, z = 1 },
            dist = { "CrateTVWide", "CrateVHSTapes" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E20
            note = "cardboardbox @ bedroom",
            coords = { x = 10874, y = 10020, z = 1 },
            dist = { "ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E21
            note = "shelves @ bedroom",
            coords = { x = 10875, y = 10020, z = 1 },
            dist = { "ToolFactoryHandles", "ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- hallway
        { -- E22
            note = "dresser @ lobby",
            coords = { x = 10877, y = 10020, z = 1 },
            dist = { "GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E23
            note = "dresser @ lobby",
            coords = { x = 10878, y = 10020, z = 1 },
            dist = { "CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        { -- E24
            note = "counter @ bathroom",
            coords = { x = 10876, y = 10026, z = 1 },
            dist = { "MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E25
            note = "counter @ bathroom",
            coords = { x = 10876, y = 10027, z = 1 },
            dist = { "BathroomCounter" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor, sitting room
        { -- E26
            note = "dresser @ livingroom",
            coords = { x = 10876, y = 10022, z = 0 },
            dist = { "CrateBlacksmithing", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E27
            note = "wardrobe @ livingroom",
            coords = { x = 10872, y = 10022, z = 0 },
            dist = { "SewingStoreTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E28
            note = "wardrobe @ livingroom",
            coords = { x = 10872, y = 10023, z = 0 },
            dist = { "SewingStoreFabric", "CrateLeather" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E29
            note = "dresser @ livingroom",
            coords = { x = 10872, y = 10024, z = 0 },
            dist = { "CrateToiletPaper" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E30
            note = "dresser @ livingroom",
            coords = { x = 10872, y = 10025, z = 0 },
            dist = { "LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        { -- E31
            note = "wardrobe @ livingroom",
            coords = { x = 10872, y = 10026, z = 0 },
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E32
            note = "wardrobe @ livingroom",
            coords = { x = 10872, y = 10027, z = 0 },
            dist = { "GunStoreKnives", "PawnShopKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- dining room
        { -- E33
            note = "dishescabinet @ diningroom",
            coords = { x = 10880, y = 10024, z = 0 },
            dist = { "CrateFishing", "FishermanTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E34
            note = "dishescabinet @ diningroom",
            coords = { x = 10880, y = 10023, z = 0 },
            dist = { "HuntingLockers", "RangerTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E35
            note = "dresser @ diningroom",
            coords = { x = 10880, y = 10022, z = 0 },
            dist = { "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E36
            note = "fireplace @ diningroom",
            coords = { x = 10882, y = 10022, z = 0 },
            items = {
                { name = 'Base.Firewood', chance = 1, count = { 10, 10 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E37
            note = "dresser @ diningroom",
            coords = { x = 10884, y = 10022, z = 0 },
            dist = { "ArtStorePottery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- exam room
        { -- E38
            note = "counter @ medical",
            coords = { x = 10885, y = 10022, z = 0 },
            dist = { "CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E39
            note = "counter @ medical",
            coords = { x = 10885, y = 10021, z = 0 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- hallway
        { -- E40
            note = "dresser @ lobby",
            coords = { x = 10881, y = 10020, z = 0 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E41
            note = "dresser @ lobby",
            coords = { x = 10882, y = 10020, z = 0 },
            dist = { "LaundryCleaning", "JanitorCleaning" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        { -- E42
            note = "fridge @ kitchen",
            coords = { x = 10872, y = 10019, z = 0 },
            dist = { "FridgeFarmStorage", "FridgeGeneric" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E43
            note = "freezer @ kitchen",
            coords = { x = 10872, y = 10019, z = 0 },
            dist = { "FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E44
            note = "counter @ kitchen",
            coords = { x = 10872, y = 10018, z = 0 },
            dist = { "GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E45
            note = "counter @ kitchen",
            coords = { x = 10872, y = 10018, z = 0 },
            slot = "upper",
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E46
            note = "counter @ kitchen",
            coords = { x = 10872, y = 10017, z = 0 },
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E47
            note = "overhead @ kitchen",
            coords = { x = 10872, y = 10017, z = 0 },
            slot = "upper",
            dist = { "KitchenDryFood", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E48
            note = "counter @ kitchen",
            coords = { x = 10873, y = 10017, z = 0 },
            dist = { "ButcherSpices", "GigamartSpices", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E49
            note = "counter @ kitchen",
            coords = { x = 10873, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E50
            note = "counter @ kitchen",
            coords = { x = 10877, y = 10017, z = 0 },
            dist = { "GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E51
            note = "counter @ kitchen",
            coords = { x = 10877, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GigamartBreakfast", "GigamartCandy" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            note = "counter @ kitchen",
            coords = { x = 10878, y = 10017, z = 0 },
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E53
            note = "counter @ kitchen",
            coords = { x = 10878, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E54
            note = "counter @ kitchen",
            coords = { x = 10879, y = 10017, z = 0 },
            dist = { "GigamartCrisps", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E55
            note = "counter @ kitchen",
            coords = { x = 10879, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- pantry
        { -- E56
            note = "shelves @ kitchen",
            coords = { x = 10880, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GroceryStorageCrate1", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E57
            note = "shelves @ kitchen",
            coords = { x = 10881, y = 10017, z = 0 },
            slot = "upper",
            dist = { "CrateTortillaChips", "KitchenDryFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E58
            note = "shelves @ kitchen",
            coords = { x = 10882, y = 10017, z = 0 },
            slot = "upper",
            dist = { "GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E59
            note = "fridge @ kitchen",
            coords = { x = 10880, y = 10019, z = 0 },
            dist = { "FridgeRich" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E60
            note = "freezer @ kitchen",
            coords = { x = 10880, y = 10019, z = 0 },
            slot = "freezer",
            dist = { "FreezerRich" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E61
            note = "freezer @ kitchen",
            coords = { x = 10881, y = 10019, z = 0 },
            dist = { "FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E62
            note = "freezer @ kitchen",
            coords = { x = 10882, y = 10019, z = 0 },
            dist = { "SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- outside pantry crate
        { -- E63
            note = "crate @ outside",
            coords = { x = 10883, y = 10018, z = 0 },
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- basement
        { -- E64
            note = "fridge @ morgue",
            coords = { x = 10862, y = 10042, z = -1 },
            dist = { "FridgeFarmStorage", "FridgeGeneric" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E65
            note = "fridge @ morgue",
            coords = { x = 10862, y = 10041, z = -1 },
            dist = { "UniversityFridge" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E66
            note = "fridge @ morgue",
            coords = { x = 10862, y = 10040, z = -1 },
            dist = { "SafehouseFridge" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E67
            note = "medicine @ morgue",
            coords = { x = 10863, y = 10039, z = -1 },
            dist = { "CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E68
            note = "medicine @ morgue",
            coords = { x = 10863, y = 10038, z = -1 },
            dist = { "CrateLumber" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E69
            note = "metal_shelves @ morgue",
            coords = { x = 10864, y = 10034, z = -1 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E70
            note = "metal_shelves @ morgue",
            coords = { x = 10865, y = 10034, z = -1 },
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E71
            note = "crate @ morgue",
            coords = { x = 10864, y = 10032, z = -1 },
            dist = { "GasStoreEmergency", "StoreCounterTobacco", "CandyStoreSnacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E72
            note = "crate @ morgue",
            coords = { x = 10864, y = 10032, z = -1 },
            stack = 2,
            dist = { "GasStoreEmergency", "StoreCounterTobacco", "CandyStoreSnacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E73
            note = "crate @ morgue",
            coords = { x = 10865, y = 10032, z = -1 },
            dist = { "CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "GasStorageMechanics", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools", "GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E74
            note = "crate @ morgue",
            coords = { x = 10865, y = 10032, z = -1 },
            stack = 2,
            dist = { "CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "GasStorageMechanics", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools", "GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E75
            note = "crate @ morgue",
            coords = { x = 10867, y = 10032, z = -1 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E76
            note = "crate @ morgue",
            coords = { x = 10867, y = 10032, z = -1 },
            stack = 2,
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E77
            note = "metal_shelves @ morgue",
            coords = { x = 10860, y = 10031, z = -1 },
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E78
            note = "crate @ morgue",
            coords = { x = 10860, y = 10028, z = -1 },
            dist = { "GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E79
            note = "crate @ morgue",
            coords = { x = 10860, y = 10028, z = -1 },
            stack = 2,
            dist = { "GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E80
            note = "crate @ morgue",
            coords = { x = 10860, y = 10027, z = -1 },
            dist = { "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E81
            note            = "crate @ morgue",
            coords          = { x = 10860, y = 10027, z = -1 },
            stack           = 2,
            dist            = { "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull   = true,
            level           = "Loot_FoodLevel",
        },
        { -- E82
            note = "crate @ morgue",
            coords = { x = 10861, y = 10027, z = -1 },
            dist = { "LiquorStoreBeer", "JanitorCleaning", "DrugLabGuns", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E83
            note = "militarylocker @ gunstore",
            coords = { x = 10868, y = 10027, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E84
            note = "militarylocker @ gunstore",
            coords = { x = 10869, y = 10027, z = -1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E85
            note = "militarylocker @ gunstore",
            coords = { x = 10870, y = 10027, z = -1 },
            dist = { "MeleeWeapons", "MeleeWeapons_Mid", "CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E86
            note = "militarylocker @ gunstore",
            coords = { x = 10871, y = 10027, z = -1 },
            dist = { "ArmyStorageGuns", "FirearmWeapons_Late" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E87
            note = "militarycrate @ gunstore",
            coords = { x = 10871, y = 10029, z = -1 },
            dist = { "CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E88
            note = "medicine @ storage",
            coords = { x = 10886, y = 10023, z = -1 },
            slot = "upper",
            dist = { "MedicalCabinet", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(CortmanMedical.objectSpawns,
        { enabled = "EnableLadders", x = 10909, y = 10020, z = 0, clearExisting = true, removeFloor = true, })
else
    table.insert(CortmanMedical.objectSpawns,
        { sprite = "walls_interior_house_02_50", x = 10890, y = 10020, z = -1, clearExisting = true, replaceWall = true, })
end

return CortmanMedical
