local wtc1 = {x = 10877, y = 10022, z = 2,}
local CortmanMedical = {
    spawn = { x = 10881, y = 10022, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 10890, y = 10016, z = 0, },
            chunks = {
                {1361, 1252},
                {1357, 1254},
                {1357, 1255},
                {1358, 1254},
                {1358, 1255},
                {1359, 1252},
                {1359, 1253},
                {1360, 1252},
                {1360, 1253},
                {1356, 1255},
                {1356, 1254},
                {1357, 1255},
                {1358, 1253},
            },
        },
    },
    waterTanks = {
        { sprite = "crafted_01_11", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 10890, y = 10016, z = 0} },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_8", x = 10872, y = 10018, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 10872, y = 10020, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_14", x = 10873, y = 10020, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_bathroom_01_5", x = 10876, y = 10028, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_21", x = 10876, y = 10027, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_21", x = 10876, y = 10026, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 10879, y = 10026, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_5", x = 10880, y = 10028, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_16", x = 10880, y = 10023, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
    },
    doorKeys = {
        name = "Cortman Medical",
        doors = {
            { sprite = "fixtures_doors_02_5", x = 10879, y = 10028, z = 0, },
            { sprite = "fixtures_doors_02_44", x = 10871, y = 10037, z = 0, },
            { sprite = "location_community_police_01_5", x = 10864, y = 10035, z = -1, },
            { sprite = "fixtures_doors_01_32", x = 10865, y = 10036, z = -1, },
        },
    },
    map = { name = "DWAPStashMap22", },
    objectSpawns = {
        { sprite = "crafted_01_11", x = wtc1.x, y = wtc1.y, z = wtc1.z, enabled = "EnableWaterSystem", }, -- invisible "tank" to simulate the well
        { sprite = "camping_01_64", x = 10863, y = 10022, z = 0, enabled = "EnableWaterSystem", }, -- fountain

        { sprite = "industry_02_64", x = 10887, y = 10016, z = 0, enabled = "EnableGenSystem", clearExisting = false, }, -- generator
        { sprite = "industry_02_68", x = 10887, y = 10015, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_65", x = 10888, y = 10016, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_69", x = 10888, y = 10015, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_66", x = 10889, y = 10016, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_70", x = 10889, y = 10015, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_67", x = 10890, y = 10016, z = 0, enabled = "EnableGenSystem", clearExisting = false, },
        { sprite = "industry_02_71", x = 10890, y = 10015, z = 0, enabled = "EnableGenSystem", clearExisting = false, },

        { sprite = "carpentry_01_16", x = 10857, y = 10044, z = -1, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10044, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10045, z = -1, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10045, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10046, z = -1, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10046, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10047, z = -1, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10857, y = 10047, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },

        { sprite = "carpentry_01_16", x = 10861, y = 10040, z = -1, enabled = "Loot", isContainer = true, clearExisting = true, },
        { sprite = "carpentry_01_16", x = 10861, y = 10040, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10861, y = 10041, z = -1, enabled = "Loot", isContainer = true, clearExisting = true, },
        { sprite = "carpentry_01_16", x = 10861, y = 10041, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 10861, y = 10042, z = -1, enabled = "Loot", isContainer = true, clearExisting = true, },
        { sprite = "carpentry_01_16", x = 10861, y = 10042, z = -1, renderYOffset = 32, enabled = "Loot", isContainer = true, },

        { x = 10889, y = 10020, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 10889, y = 10021, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 10889, y = 10022, z = 0, clearExisting = true, },
        { sprite = "fixtures_railings_01_36", x = 10889, y = 10023, z = 0, clearExisting = true, },

        { sprite = "fixtures_doors_01_32", x = 10865, y = 10036, z = -1, isDoor = true, doorN = false, },
        { sprite = "location_sewer_01_18", x = 10865, y = 10036, z = -1, replaceWall = true, },
        { sprite = "location_sewer_01_10", x = 10865, y = 10037, z = -1, replaceWall = true, },

        { barricade = "metal", target="walls_commercial_02_50", x = 10888, y = 10024, z = 0, },
        { barricade = "metalbar", target="walls_commercial_02_49", x = 10887, y = 10024, z = 0, },
        { barricade = "metal", target="walls_commercial_02_48", x = 10886, y = 10024, z = 0, },
        { barricade = "metalbar", target="walls_exterior_house_03_11", x = 10883, y = 10028, z = 0, },
        { barricade = "metalbar", target="walls_exterior_house_03_11", x = 10873, y = 10028, z = 0, },
        { barricade = "metal", target="walls_exterior_house_01_25", x = 10868, y = 10040, z = 0, },
        { barricade = "metalbar", target="walls_exterior_house_01_24", x = 10866, y = 10042, z = 0, },
        { barricade = "woodhalf", target="fixtures_doors_01_40", x = 10866, y = 10045, z = 0, },
        { barricade = "metal", target="walls_exterior_house_01_25", x = 10864, y = 10048, z = 0, },
        { barricade = "metal", target="walls_exterior_house_01_25", x = 10864, y = 10048, z = 0, },
        { barricade = "metal", target="walls_exterior_house_01_25", x = 10861, y = 10048, z = 0, },
        { barricade = "metalbar", target="walls_interior_house_03_28", x = 10860, y = 10042, z = 0, },
        { barricade = "metalbar", target="location_restaurant_pizzawhirled_01_9", x = 10868, y = 10034, z = 0, },
        { barricade = "metalbar", target="walls_interior_house_03_29", x = 10873, y = 10017, z = 0, },
        { barricade = "woodhalf", target="fixtures_doors_02_5", x = 10878, y = 10029, z = 0, },
        { barricade = "woodhalf", target="walls_commercial_02_54", x = 10885, y = 10024, z = 1, },
        { barricade = "woodhalf", target="walls_commercial_02_55", x = 10886, y = 10023, z = 1, },
        { barricade = "woodhalf", target="walls_commercial_02_55", x = 10886, y = 10022, z = 1, },
        { barricade = "woodhalf", target="walls_commercial_02_54", x = 10885, y = 10022, z = 1, },
    },
    loot = {
        -- upstairs office
        {
            type = 'container',
            coords = {x=10880,y=10027,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=10880,y=10026,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=10880,y=10025,z=1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=10880,y=10024,z=1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=10880,y=10023,z=1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=10882,y=10026,z=1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=10881,y=10020,z=1},
            dist = {"LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10882,y=10020,z=1},
            dist = {"MorgueTools", "MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10883,y=10020,z=1},
            dist = {"BookstoreBiography", "MedicalOfficeBooks", "LibraryMedical", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10884,y=10020,z=1},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=10885,y=10022,z=1},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- bigger upstairs bedroom
        {
            type = 'container',
            coords = {x=10872,y=10026,z=1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10023,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10875,y=10027,z=1},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10875,y=10026,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10875,y=10023,z=1},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10875,y=10023,z=1.5},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10874,y=10023,z=1.5},
            dist = {"SafehouseTraps", "ArmyStorageAmmunition"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- 2nd bedroom
        {
            type = 'container',
            coords = {x=10875,y=10022,z=1},
            items = {
                { name = 'TvWideScreen', chance = 1, count = {1,1} },
                { name = 'Base.Remote', chance = 1, count = {1,3} },
                { name = 'Base.VideoGame', chance = 1, count = {3,3} },
                { name = 'Base.Headphones', chance = 1, count = {3,3} },
                { name = 'Base.CDplayer', chance = 1, count = {3,3} },
                { name = 'Base.Bullhorn', chance = 0.5, count = {1,1} },
            },
        },
        {
            type = 'container',
            coords = {x=10874,y=10020,z=1},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=10875,y=10020,z=1},
            dist = {"ToolFactoryHandles","ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- hallway
        {
            type = 'container',
            coords = {x=10877,y=10020,z=1},
            dist = {"GigamartTools", "JanitorTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10878,y=10020,z=1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        {
            type = 'container',
            coords = {x=10876,y=10026,z=1},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=10876,y=10027,z=1},
            dist = {"BathroomCounter"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor, sitting room
        {
            type = 'container',
            coords = {x=10872,y=10022,z=0},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10023,z=0},
            dist = {"SewingStoreFabric", "CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10024,z=0},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10025,z=0},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = 1,
        },
        {
            type = 'container',
            coords = {x=10872,y=10026,z=0},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10027,z=0},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- dining room
        {
            type = 'container',
            coords = {x=10880,y=10024,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10880,y=10023,z=0},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=10880,y=10022,z=0},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=10882,y=10022,z=0},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10884,y=10022,z=0},
            dist = {"ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- exam room
        {
            type = 'container',
            coords = {x=10885,y=10022,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10885,y=10021,z=0},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10889,y=10021,z=0},
            dist = {"CrateBlacksmithing", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=10889,y=10020,z=0},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- hallway
        {
            type = 'container',
            coords = {x=10881,y=10020,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10882,y=10020,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=10872,y=10019,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10018,z=0},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10018,z=0.5},
            dist = {"GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10017,z=0},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10872,y=10017,z=0.5},
            dist = {"KitchenDryFood",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10873,y=10017,z=0},
            dist = {"ButcherSpices","GigamartSpices", "GigamartDryGoods",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10877,y=10017,z=0},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10877,y=10017,z=0.5},
            dist = {"GigamartBreakfast","GigamartCandy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10878,y=10017,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10878,y=10017,z=0.5},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10879,y=10017,z=0},
            dist = {"GigamartCrisps", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10879,y=10017,z=0.5},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- pantry
        {
            type = 'container',
            coords = {x=10880,y=10017,z=0.5},
            dist = {"GroceryStorageCrate1", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10881,y=10017,z=0.5},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10882,y=10017,z=0.5},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10880,y=10019,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10881,y=10019,z=0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=10882,y=10019,z=0},
            dist = {"SushiKitchenFreezer", "WesternKitchenFreezer", "BakeryKitchenFreezer"},
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        -- outside pantry crate
        {
            type = 'container',
            coords = {x=10883,y=10018,z=0},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- basement
        {
            type = 'container',
            coords = {x=10853,y=10047,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10853,y=10046,z=-1},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=10853,y=10045,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10853,y=10044,z=-1},
            dist = {"ArmyStorageGuns","FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=10853,y=10043,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- spawned crates

        -- { sprite = "carpentry_01_16", , enabled = "Loot", isContainer = true, },
        {
            type = 'container',
            coords = {x = 10857, y = 10044, z = -1},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 10857, y = 10045, z = -1},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 10857, y = 10046, z = -1},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 10857, y = 10047, z = -1},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 10861, y = 10040, z = -1},
            dist = {"GasStoreEmergency", "StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 10861, y = 10041, z = -1},
            dist = {"CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools","GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 10861, y = 10042, z = -1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
    },
}

return CortmanMedical