local wtc1 = {x = 9850, y = 13117, z = -4,}
local MRSecret = {
    spawn = { x = 9850, y = 13111, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 9848, y = 13117, z = -4, },
            chunks = {
                -- shed
                {1229, 1641},
                -- apts
                {1230, 1636},
                {1231, 1636},
                {1230, 1637},
                {1231, 1637},
                {1230, 1638},
                {1231, 1638},
                {1230, 1639},
                {1231, 1639},
                {1230, 1640},
                {1231, 1640},
                {1228, 1639},
                {1228, 1640},
                {1229, 1639},
                {1229, 1640},
            },
        },
    },
    waterTanks = {
        { sprite = "industry_02_72", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 9848, y = 13117, z = -4} },
    },
    waterFixtures = {
        -- apts
        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13121, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13120, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13120, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13122, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13118, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13119, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13119, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13117, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13109, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13108, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13108, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13110, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13106, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13107, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13107, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13105, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13097, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13096, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13096, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13098, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13094, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13095, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13095, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13093, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        -- basement
        { sprite = "fixtures_sinks_01_25", x = 9834, y = 13119, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_25", x = 9834, y = 13119, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_bathroom_01_32", x = 9841, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9842, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9843, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9844, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9845, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 9846, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
    },
    doorKeys = {
        name = "March Ridge Complex",
        doors = {
            { sprite = "fixtures_doors_01_28", x = 9834, y = 13129, z = 0, },
            { sprite = "fixtures_doors_01_44", x = 9853, y = 13124, z = 0, },
            { sprite = "fixtures_doors_01_32", x = 9851, y = 13114, z = -1, },
        },
    },
    map = { name = "DWAPStashMap24", },
    objectSpawns = {
        -- { sprite = "crafted_01_11", x = wtc1.x, y = wtc1.y, z = wtc1.z, enabled = "EnableWaterSystem", }, -- invisible "tank" to simulate the well
        { sprite = "camping_01_64", x = 9837, y = 13130, z = 0, enabled = "EnableWaterSystem", }, -- fountain

        { sprite = "fixtures_railings_01_28", x = 9832, y = 13130, z = 0, clearExisting = true, }, -- basement railing
        { sprite = "fixtures_railings_01_28", x = 9832, y = 13129, z = 0, clearExisting = true, }, -- basement railing
        { sprite = "fixtures_railings_01_28", x = 9832, y = 13128, z = 0, clearExisting = true, }, -- basement railing
        { x = 9832, y = 13127, z = 0, clearExisting = true, }, -- basement railing
        { x = 9831, y = 13130, z = 0, clearExisting = true, }, -- basement railing
        { x = 9831, y = 13129, z = 0, clearExisting = true, }, -- basement railing
        { x = 9831, y = 13128, z = 0, clearExisting = true, }, -- basement railing
        { x = 9831, y = 13127, z = 0, clearExisting = true, }, -- basement railing
        { sprite = "furniture_storage_02_3", x = 9834, y = 13126, z = 0, isContainer = true, },

        { sprite = "carpentry_01_16", x = 9844, y = 13111, z = 1, enabled = "Loot", isContainer = true, },
        { sprite = "carpentry_01_16", x = 9844, y = 13111, z = 1, renderYOffset = 32, enabled = "Loot", isContainer = true, },
        { sprite = "appliances_cooking_01_17", x = 9847, y = 13108, z = 0, isFireplace = true, },
        { sprite = "appliances_refreigeration_01_38", x = 9848, y = 13108, z = 0, },
        { sprite = "appliances_refreigeration_01_39", x = 9849, y = 13108, z = 0, },

        { x = 9846, y = 13124, z = 0, clearExisting = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13125, z = 0, replaceWall = true, },
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13125, z = 0, isDoor = true, doorN = true, },
        { sprite = "walls_interior_house_02_48", x = 9846, y = 13125, z = 0, },

        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13115, z = 0, replaceWall = true, clearExisting = true, },
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13115, z = 0, isDoor = true, doorN = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13114, z = 0, replaceWall = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13113, z = 0, },
        { sprite = "walls_interior_house_02_48", x = 9846, y = 13114, z = 0, replaceWall = true, },
        { sprite = "walls_interior_house_02_48", x = 9846, y = 13113, z = 0, replaceWall = true, },
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13113, z = 0, isDoor = true, doorN = true, },
        { x = 9846, y = 13112, z = 0, clearExisting = true, },

        { x = 9846, y = 13100, z = 0, clearExisting = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13103, z = 0, replaceWall = true, clearExisting = true,},
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13103, z = 0, isDoor = true, doorN = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13102, z = 0, replaceWall = true, },
        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13101, z = 0, clearExisting = true, },
        { sprite = "walls_interior_house_02_48", x = 9846, y = 13101, z = 0, replaceWall = true, },
        { sprite = "walls_interior_house_02_48", x = 9846, y = 13102, z = 0, replaceWall = true, },
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13101, z = 0, isDoor = true, doorN = true, },

        { sprite = "fixtures_doors_frames_01_1", x = 9846, y = 13091, z = 0, replaceWall = true, clearExisting = true, },
        { sprite = "fixtures_doors_01_57", x = 9846, y = 13091, z = 0, isDoor = true, doorN = true, },

        { barricade = "metalbar", target="location_trailer_01_9", x = 9833, y = 13131, z = 0, },
        { barricade = "metalbar", target="location_trailer_01_8", x = 9835, y = 13127, z = 0, },
        { barricade = "metalbar", target="walls_garage_01_45", x = 9832, y = 13127, z = -1, },

        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13121, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13118, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13109, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13106, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13097, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13094, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13091, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13100, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13103, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13115, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13124, z = 0, },

        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13124, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13121, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13118, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13115, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13109, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13106, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13103, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13100, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13097, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13094, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13091, z = 0, },
    },
    loot = {
        -- spawn apartment
        -- 2nd floor
        -- bedroom
        {
            type = 'container',
            coords = {x=9852,y=13110,z=1.5},
            dist = {"BookstoreBiography", "MedicalOfficeBooks", "LibraryMedical", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=9853,y=13113,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=9849,y=13112,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- hall spawned crates
        {
            type = 'container',
            coords = {x = 9844, y = 13111, z = 1},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- office
        {
            type = 'container',
            coords = {x=9847,y=13108,z=1.5},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- closet
        {
            type = 'container',
            coords = {x=9849,y=13108,z=1.5},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        {
            type = 'container',
            coords = {x=9850,y=13108,z=1},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=9851,y=13108,z=1},
            dist = {"BathroomCounter"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor
        -- bathroom
        {
            type = 'container',
            coords = {x=9851,y=13108,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=9846,y=13108,z=0},
            dist = {"StoreKitchenGlasses", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13108,z=0},
            dist = {"ButcherSpices","GigamartSpices", "GigamartDryGoods",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13109,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13110,z=0},
            dist = {"GigamartBreakfast","GigamartCandy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13113,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13113,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 9848, y = 13108, z = 0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 9849, y = 13108, z = 0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        -- apt 1 extras
        {
            type = 'container',
            coords = {x=9844,y=13122,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13125,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13125,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13098,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9844,y=13101,z=0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13101,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- entrance shed
        {
            type = 'container',
            coords = {x=9831,y=13126,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=9834,y=13126,z=0},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- complex, -1
        -- guard station
        {
            type = 'container',
            coords = {x=9831,y=13124,z=-1},
            dist = {"ArmyStorageGuns","FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9832,y=13124,z=-1},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9833,y=13124,z=-1},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9833,y=13125,z=-1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- -1 stairwell
        {
            type = 'container',
            coords = {x=9830,y=13116,z=-1},
            dist = {"ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9831,y=13127,z=-1},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- complex, -4
        -- stairwell
        {
            type = 'container',
            coords = {x=9830,y=13116,z=-4},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9831,y=13116,z=-4},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9830,y=13118,z=-4},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9831,y=13118,z=-4},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=9832,y=13118,z=-4},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- guard desk
        {
            type = 'container',
            coords = {x=9838,y=13124,z=-4},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- armory
        {
            type = 'container',
            coords = {x=9837,y=13122,z=-4},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=9837,y=13121,z=-4},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9837,y=13120,z=-4},
            dist = {"ArmyStorageGuns","ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9837,y=13119,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9839,y=13122,z=-4},
            dist = {"DrugLabGuns"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9839,y=13121,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9839,y=13120,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9839,y=13119,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- workroom
        {
            type = 'container',
            coords = {x=9840,y=13122,z=-4},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=9840,y=13120,z=-4},
            dist = { "GunStoreKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=9842,y=13119,z=-4},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        -- bunk room
        {
            type = 'container',
            coords = {x=9845,y=13126,z=-4},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=9847,y=13126,z=-4},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=9850,y=13126,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=9851,y=13126,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- bunk room kitchen
        {
            type = 'container',
            coords = {x=9851,y=13124,z=-4},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9851,y=13124,z=-3.5},
            dist = {"GigamartCrisps", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9849,y=13124,z=-4},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9849,y=13124,z=-3.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9848,y=13124,z=-4},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9848,y=13124,z=-3.5},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- infirmary
        {
            type = 'container',
            coords = {x=9845,y=13123,z=-4},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13121,z=-4},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13121,z=-3.5},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=9850,y=13121,z=-4},
            dist = {"LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=9851,y=13121,z=-4},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=9851,y=13123,z=-4},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- machine room
        {
            type = 'container',
            coords = {x=9845,y=13120,z=-4},
            dist = {"GasStoreEmergency", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13118,z=-4},
            dist = { "ArmyHangarTools", "CarSupplyTools", "GarageTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=9846,y=13120,z=-4},
            dist = {"CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools","GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=9847,y=13120,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=9848,y=13120,z=-4},
            dist = { "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=9849,y=13120,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=9850,y=13120,z=-4},
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=9851,y=13120,z=-4},
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- office
        {
            type = 'container',
            coords = {x=9839,y=13117,z=-4},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=9837,y=13118,z=-4},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=9837,y=13117,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=9837,y=13116,z=-4},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bathrooms
        {
            type = 'container',
            coords = {x=9842,y=13114,z=-4},
            dist = {"BookstoreBiography", "BathroomCounter", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=9841,y=13115,z=-4},
            dist = {"BathroomCounter", "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=9845,y=13114,z=-4},
            dist = {"SewingStoreTools","SewingStoreFabric", "CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
    },
}

return MRSecret