local wtc1 = {x = 9850, y = 13117, z = -4,}
local pb1 = { x = 9850, y = 13108, z = -1 }
local MRSecret = {
    group = "March Ridge",
    baseBuildings = {
        { x = 9850, y = 13111, z = 1 }, -- apartment
        { x = 9841, y = 13119, z = -4 }, -- basement
        { x = 9833, y = 13127, z = 0 }, -- shed
    },
    spawn = { x = 9850, y = 13111, z = 1 },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 9848, y = 13117, z = -4 },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 9846, y = 13117, z = -4, },
            fakeGenerators = {
                { x = 9849, y = 13128, z = -1, createTile = true },
                { x = 9849, y = 13103, z = -1, createTile = true },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_8", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 9848, y = 13117, z = -4} },
    },
    waterFixtures = {
        -- apts
        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13121, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13120, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13120, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13122, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13120, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13118, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13119, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13119, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13117, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13119, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13109, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13108, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13108, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13110, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13108, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13106, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13107, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13107, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13105, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13107, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13097, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13096, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13096, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13098, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9850, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9851, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9852, y = 13096, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_8", x = 9844, y = 13094, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13095, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13095, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13093, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9850, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 9851, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 9852, y = 13095, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        -- basement
        { sprite = "fixtures_sinks_01_25", x = 9834, y = 13119, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_25", x = 9834, y = 13119, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_bathroom_01_32", x = 9840, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9842, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9843, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 9844, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_2", x = 9845, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 9847, y = 13114, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "appliances_laundry_01_2", x = 9850, y = 13123, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
    },
    doorKeys = {
        name = "March Ridge Complex",
        doors = {
            { sprite = "fixtures_doors_01_28", x = 9834, y = 13129, z = 0, },
            { sprite = "fixtures_doors_01_44", x = 9853, y = 13124, z = 0, },
            { sprite = "fixtures_doors_01_32", x = 9851, y = 13114, z = -1, },
        },
    },
    map = { name = "DWAPStashMap24", },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        { barricade = "metalbar", target="location_trailer_01_9", x = 9833, y = 13131, z = 0, },
        { barricade = "metalbar", target="location_trailer_01_8", x = 9835, y = 13127, z = 0, },
        { barricade = "metalbar", target="walls_garage_01_45", x = 9832, y = 13127, z = -1, },

        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13121, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13118, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13109, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13106, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13097, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_exterior_house_02_40", x = 9853, y = 13094, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13091, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13100, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13103, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13115, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9854, y = 13124, z = 0, },

        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13124, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13121, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13118, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13115, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13109, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13106, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13103, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13100, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13097, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="walls_interior_house_04_92", x = 9844, y = 13094, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_doors_01_44", x = 9844, y = 13091, z = 0, },
    },
    loot = {
        -- spawn apartment
        -- 2nd floor
        -- bedroom
        { -- E1
            coords = {x=9852,y=13110,z=1},
            slot = "upper",
            dist = {"BookstoreBiography", "MedicalOfficeBooks", "LibraryMedical", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E2
            coords = {x=9853,y=13113,z=1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E3
            coords = {x=9849,y=13112,z=1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- office
        { -- E4
            coords = {x=9847,y=13108,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- closet
        { -- E5
            coords = {x=9849,y=13108,z=1},
            slot = "upper",
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        { -- E6
            coords = {x=9850,y=13108,z=1},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E7
            coords = {x=9851,y=13108,z=1},
            dist = {"BathroomCounter"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor
        -- bathroom
        { -- E8
            coords = {x=9851,y=13108,z=0},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        -- kitchen
        { -- E9
            coords = {x=9846,y=13108,z=0},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E10
            coords = {x=9844,y=13108,z=0},
            dist = {"ButcherSpices","GigamartSpices", "GigamartDryGoods",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E11
            coords = {x=9844,y=13109,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E12
            coords = {x=9844,y=13110,z=0},
            dist = {"GigamartBreakfast","GigamartCandy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E13
            coords = {x=9844,y=13113,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E14
            coords = {x=9845,y=13113,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E15
            coords = {x = 9848, y = 13108, z = 0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E16
            coords = {x = 9849, y = 13108, z = 0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- apt 1 extras
        { -- E17
            coords = {x=9844,y=13120,z=0},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E18
            coords = {x=9844,y=13121,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E19
            coords = {x=9844,y=13122,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E20
            coords = {x=9844,y=13125,z=0},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E21
            coords = {x=9845,y=13125,z=0},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E22
            coords = {x=9844,y=13098,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E23
            coords = {x=9844,y=13101,z=0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E24
            coords = {x=9845,y=13101,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- entrance shed
        { -- E25
            coords = {x=9831,y=13126,z=0},
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- complex, -1
        -- guard station
        { -- E26
            coords = {x=9831,y=13124,z=-1},
            dist = {"ArmyStorageGuns","FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E27
            coords = {x=9832,y=13124,z=-1},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E28
            coords = {x=9833,y=13124,z=-1},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E29
            coords = {x=9833,y=13125,z=-1},
            dist = {"CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- -1 stairwell
        { -- E30
            coords = {x=9830,y=13116,z=-1},
            dist = {"ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E31
            coords = {x=9831,y=13127,z=-1},
            dist = {"ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- complex, -4
        -- stairwell
        { -- E32
            coords = {x=9830,y=13116,z=-4},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E33
            coords = {x=9831,y=13116,z=-4},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E34
            coords = {x=9830,y=13118,z=-4},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E35
            coords = {x=9831,y=13118,z=-4},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E36
            coords = {x=9832,y=13118,z=-4},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- guard desk
        { -- E37
            coords = {x=9838,y=13124,z=-4},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- armory
        { -- E38
            coords = {x=9837,y=13122,z=-4},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E39
            coords = {x=9837,y=13121,z=-4},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E40
            coords = {x=9837,y=13120,z=-4},
            dist = {"ArmyStorageGuns","ArmyStorageAmmunition"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E41
            coords = {x=9837,y=13119,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E42
            coords = {x=9839,y=13122,z=-4},
            dist = {"DrugLabGuns"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E43
            coords = {x=9839,y=13121,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E44
            coords = {x=9839,y=13120,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E45
            coords = {x=9839,y=13119,z=-4},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- workroom
        { -- E46
            coords = {x=9840,y=13122,z=-4},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E47
            coords = {x=9840,y=13120,z=-4},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E48
            coords = {x=9842,y=13119,z=-4},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        -- bunk room
        { -- E49
            coords = {x=9845,y=13126,z=-4},
            special = "essentials",
        },
        { -- E50
            coords = {x=9847,y=13126,z=-4},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E51
            coords = {x=9850,y=13126,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E52
            coords = {x=9851,y=13126,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- bunk room kitchen
        { -- E53
            coords = {x=9851,y=13124,z=-4},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E54
            coords = {x=9851,y=13124,z=-4},
            slot = "upper",
            dist = {"GigamartCrisps", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E55
            coords = {x=9849,y=13124,z=-4},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E56
            coords = {x=9849,y=13124,z=-4},
            slot = "upper",
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E57
            coords = {x=9848,y=13124,z=-4},
            dist = {"FridgeFarmStorage", "FridgeGeneric"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E58
            coords = {x=9848,y=13124,z=-4},
            slot = "upper",
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- infirmary
        { -- E59
            coords = {x=9845,y=13123,z=-4},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E60
            coords = {x=9845,y=13121,z=-4},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E61
            coords = {x=9845,y=13121,z=-4},
            slot = "upper",
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E62
            coords = {x=9850,y=13121,z=-4},
            dist = {"LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E63
            coords = {x=9851,y=13121,z=-4},
            dist = {"MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E64
            coords = {x=9851,y=13123,z=-4},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- machine room
        { -- E65
            coords = {x=9845,y=13120,z=-4},
            dist = {"GasStoreEmergency", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E66
            coords = {x=9845,y=13118,z=-4},
            dist = { "ArmyHangarTools", "GasStorageMechanics", "GarageTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E67
            coords = {x=9846,y=13120,z=-4},
            dist = {"CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools","GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E68
            coords = {x=9847,y=13120,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E69
            coords = {x=9848,y=13120,z=-4},
            dist = { "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E70
            coords = {x=9849,y=13120,z=-4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E71
            coords = {x=9850,y=13120,z=-4},
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E72
            coords = {x=9851,y=13120,z=-4},
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- office
        { -- E73
            coords = {x=9839,y=13117,z=-4},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E74
            coords = {x=9837,y=13118,z=-4},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E75
            coords = {x=9837,y=13117,z=-4},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E76
            coords = {x=9837,y=13116,z=-4},
            dist = {"CrateLiquor"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bathrooms
        { -- E77
            coords = {x=9842,y=13114,z=-4},
            dist = {"BookstoreBiography", "BathroomCounter", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E78
            coords = {x=9840,y=13115,z=-4},
            dist = {"BathroomCounter", "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E79
            coords = {x=9845,y=13114,z=-4},
            dist = {"SewingStoreTools","SewingStoreFabric", "CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
    },
}

return MRSecret