local wtc1 = { x = 9850, y = 13117, z = -4, }
local pb1 = { x = 9850, y = 13108, z = -1 }
local MRSecret = {
    group = "March Ridge",
    baseBuildings = {
        { x = 9850, y = 13111, z = 1 },  -- apartment
        { x = 9841, y = 13119, z = -4 }, -- basement
        { x = 9833, y = 13127, z = 0 },  -- shed
    },
    spawn = { x = 9850, y = 13111, z = 1 },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 9848, y = 13117, z = -4 },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 9846, y = 13117, z = -4, },
            fakeGenerators = {
                { x = 9849, y = 13128, z = -1, createTile = true },
                { x = 9849, y = 13103, z = -1, createTile = true },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_8", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType = "generator", source = { x = 9848, y = 13117, z = -4 } },
    },
    waterFixtures = {
        -- apts
        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13121, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13120, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13120, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13122, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9850, y = 13120, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13120, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13120, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13118, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13119, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13119, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13117, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9850, y = 13119, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13119, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13119, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13109, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13108, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13108, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13110, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9850, y = 13108, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13108, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13108, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13106, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13107, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13107, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13105, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9850, y = 13107, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13107, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13107, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13097, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13096, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13096, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13098, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9850, y = 13096, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9851, y = 13096, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9852, y = 13096, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_sinks_01_8",     x = 9844, y = 13094, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13095, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13095, z = 0,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_55", x = 9851, y = 13093, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9850, y = 13095, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_0",     x = 9851, y = 13095, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_3",  x = 9852, y = 13095, z = 1,  sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        -- basement
        { sprite = "fixtures_sinks_01_25",    x = 9834, y = 13119, z = -1, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_25",    x = 9834, y = 13119, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },

        { sprite = "fixtures_bathroom_01_32", x = 9840, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9842, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9843, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_0",  x = 9844, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_sinks_01_2",     x = 9845, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "fixtures_bathroom_01_25", x = 9847, y = 13114, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
        { sprite = "appliances_laundry_01_2", x = 9850, y = 13123, z = -4, sourceType = "tank", source = { x = wtc1.x, y = wtc1.y, z = wtc1.z } },
    },
    doorKeys = {
        name = "March Ridge Complex",
        doors = {
            { sprite = "fixtures_doors_01_28", x = 9834, y = 13129, z = 0, },
            { sprite = "fixtures_doors_01_44", x = 9853, y = 13124, z = 0, },
            { sprite = "fixtures_doors_01_32", x = 9851, y = 13114, z = -1, },
        },
    },
    map = { name = "DWAPStashMap24", },
    objectSpawns = {
        { barricade = "metalbar",     target="fixtures_windows_01_1", x = 9833, y = 13131, z = 0, }, -- window N | garagestorage, bld 38,51#4
        { barricade = "metalbar",     target="fixtures_windows_01_0", x = 9835, y = 13127, z = 0, }, -- window W | garagestorage, bld 38,51#4

        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13121,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13118,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13109,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13106,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13097,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_exterior_house_02_40", x = 9853,  y = 13094,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9854,  y = 13091,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9854,  y = 13100,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9854,  y = 13103,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9854,  y = 13115,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9854,  y = 13124,                         z = 0, },

        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9844,  y = 13124,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13121,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13118,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9844,  y = 13115,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13109,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13106,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9844,  y = 13103,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9844,  y = 13100,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13097,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "walls_interior_house_04_92", x = 9844,  y = 13094,                         z = 0, },
        { barricade = "wood",         enabled = "Barricade",            target = "fixtures_doors_01_44",       x = 9844,  y = 13091,                         z = 0, },
    },
    loot = {
        -- spawn apartment
        -- 2nd floor
        -- bedroom
        { -- E1
            note = "shelves @ bedroom",
            coords = { x = 9852, y = 13110, z = 1 },
            slot = "upper",
            dist = { "BookstoreBiography", "MedicalOfficeBooks", "LibraryMedical", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E2
            note = "sidetable @ bedroom",
            coords = { x = 9853, y = 13113, z = 1 },
            dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E3
            note = "dresser @ bedroom",
            coords = { x = 9849, y = 13112, z = 1 },
            dist = { "LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- office
        { -- E4
            note = "militarylocker @ bedroom",
            coords = { x = 9847, y = 13108, z = 1 },
            dist = { "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E5
            note = "desk @ bedroom",
            coords = { x = 9844, y = 13109, z = 1 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- closet
        { -- E6
            note = "metal_shelves @ closet",
            coords = { x = 9849, y = 13108, z = 1 },
            slot = "upper",
            dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        { -- E7
            note = "counter @ bathroom",
            coords = { x = 9850, y = 13108, z = 1 },
            dist = { "MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E8
            note = "counter @ bathroom",
            coords = { x = 9851, y = 13108, z = 1 },
            dist = { "BathroomCounter" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- first floor
        -- bathroom
        { -- E9
            note = "counter @ bathroom",
            coords = { x = 9851, y = 13108, z = 0 },
            dist = { "CrateFishing", "FishermanTools" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        -- kitchen
        { -- E10
            note = "counter @ kitchen",
            coords = { x = 9846, y = 13108, z = 0 },
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E11
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13108, z = 0 },
            dist = { "ButcherSpices", "GigamartSpices", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E12
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13109, z = 0 },
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E13
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13110, z = 0 },
            dist = { "GigamartBreakfast", "GigamartCandy" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E14
            note = "fridge @ kitchen",
            coords = { x = 9844, y = 13113, z = 0 },
            dist = { "FridgeFarmStorage", "FridgeGeneric" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E15
            note = "freezer @ kitchen",
            coords = { x = 9844, y = 13113, z = 0 },
            slot = "freezer",
            dist = { "FreezerGeneric" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E16
            note = "counter @ kitchen",
            coords = { x = 9845, y = 13113, z = 0 },
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E17
            note = "freezer @ kitchen",
            coords = { x = 9848, y = 13108, z = 0 },
            dist = { "FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E18
            note = "freezer @ livingroom",
            coords = { x = 9849, y = 13108, z = 0 },
            dist = { "FreezerIceCream", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- apt 1 extras
        { -- E19
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13120, z = 0 },
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E20
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13121, z = 0 },
            dist = { "CrateVHSTapes" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E21
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13122, z = 0 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E22
            note = "fridge @ kitchen",
            coords = { x = 9844, y = 13125, z = 0 },
            dist = { "FridgeFarmStorage", "FridgeGeneric" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E23
            note = "counter @ kitchen",
            coords = { x = 9845, y = 13125, z = 0 },
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E24
            note = "counter @ kitchen",
            coords = { x = 9844, y = 13098, z = 0 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E25
            note = "freezer @ kitchen",
            coords = { x = 9844, y = 13101, z = 0 },
            slot = "freezer",
            dist = { "FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E26
            note = "counter @ kitchen",
            coords = { x = 9845, y = 13101, z = 0 },
            dist = { "CrateLiquor", "DishCabinetVIPLounge" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- entrance shed
        { -- E27
            note = "metal_shelves @ garagestorage",
            coords = { x = 9831, y = 13126, z = 0 },
            sandboxEnable = 'SeedLibrary',
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- complex, -1
        -- guard station
        { -- E28
            note = "counter @ hall",
            coords = { x = 9831, y = 13124, z = -1 },
            dist = { "ArmyStorageGuns", "FirearmWeapons_Late" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E29
            note = "counter @ hall",
            coords = { x = 9832, y = 13124, z = -1 },
            dist = { "ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E30
            note = "counter @ hall",
            coords = { x = 9833, y = 13124, z = -1 },
            dist = { "GunStoreKnives", "PawnShopKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E31
            note = "counter @ hall",
            coords = { x = 9833, y = 13125, z = -1 },
            dist = { "CampingStoreBackpacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- -1 stairwell
        { -- E32
            note = "cardboardbox @ storage",
            coords = { x = 9830, y = 13116, z = -1 },
            dist = { "ArtStorePottery", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E33
            note = "cardboardbox @ hall",
            coords = { x = 9831, y = 13127, z = -1 },
            dist = { "ToolFactoryHandles" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- complex, -4
        -- stairwell
        { -- E34
            note = "militarycrate @ storage",
            coords = { x = 9830, y = 13116, z = -4 },
            dist = { "CrateLumber" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E35
            note = "militarycrate @ storage",
            coords = { x = 9830, y = 13116, z = -4 },
            stack = 2,
            dist = { "CrateLumber" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E36
            note = "militarycrate @ storage",
            coords = { x = 9831, y = 13116, z = -4 },
            dist = { "CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E37
            note = "militarycrate @ storage",
            coords = { x = 9831, y = 13116, z = -4 },
            stack = 2,
            dist = { "CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E38
            note = "militarycrate @ storage",
            coords = { x = 9830, y = 13118, z = -4 },
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E39
            note = "militarycrate @ storage",
            coords = { x = 9830, y = 13118, z = -4 },
            stack = 2,
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E40
            note = "militarycrate @ storage",
            coords = { x = 9831, y = 13118, z = -4 },
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E41
            note = "militarycrate @ storage",
            coords = { x = 9832, y = 13118, z = -4 },
            dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- guard desk
        { -- E42
            note = "desk @ hall",
            coords = { x = 9838, y = 13124, z = -4 },
            dist = { "StoreCounterTobacco", "CandyStoreSnacks" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- armory
        { -- E43
            note = "militarylocker @ armory",
            coords = { x = 9837, y = 13122, z = -4 },
            dist = { "SafehouseArmor", "SafehouseLighting" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E44
            note = "militarylocker @ armory",
            coords = { x = 9837, y = 13121, z = -4 },
            dist = { "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E45
            note = "militarylocker @ armory",
            coords = { x = 9837, y = 13120, z = -4 },
            dist = { "ArmyStorageGuns", "ArmyStorageAmmunition" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E46
            note = "militarylocker @ armory",
            coords = { x = 9837, y = 13119, z = -4 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E47
            note = "militarylocker @ armory",
            coords = { x = 9839, y = 13122, z = -4 },
            dist = { "DrugLabGuns" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E48
            note = "militarylocker @ armory",
            coords = { x = 9839, y = 13121, z = -4 },
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E49
            note = "militarycrate @ armory",
            coords = { x = 9839, y = 13120, z = -4 },
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E50
            note = "militarycrate @ armory",
            coords = { x = 9839, y = 13120, z = -4 },
            stack = 2,
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E51
            note = "militarycrate @ armory",
            coords = { x = 9839, y = 13119, z = -4 },
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E52
            note = "militarycrate @ armory",
            coords = { x = 9839, y = 13119, z = -4 },
            stack = 2,
            dist = { "ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- workroom
        { -- E53
            note = "desk @ storage",
            coords = { x = 9840, y = 13122, z = -4 },
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E54
            note = "desk @ storage",
            coords = { x = 9840, y = 13120, z = -4 },
            dist = { "GunStoreKnives", "PawnShopKnives", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E55
            note = "filingcabinet @ storage",
            coords = { x = 9842, y = 13119, z = -4 },
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        -- bunk room
        { -- E56
            note = "locker @ bedroom",
            coords = { x = 9845, y = 13126, z = -4 },
            special = "essentials",
        },
        { -- E57
            note = "locker @ bedroom",
            coords = { x = 9847, y = 13126, z = -4 },
            dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E58
            note = "shelves @ bedroom",
            coords = { x = 9850, y = 13126, z = -4 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E59
            note = "shelves @ bedroom",
            coords = { x = 9851, y = 13126, z = -4 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- bunk room kitchen
        { -- E60
            note = "counter @ bedroom",
            coords = { x = 9851, y = 13124, z = -4 },
            dist = { "GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E61
            note = "overhead @ bedroom",
            coords = { x = 9851, y = 13124, z = -4 },
            slot = "upper",
            dist = { "GigamartCrisps", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E62
            note = "counter @ bedroom",
            coords = { x = 9849, y = 13124, z = -4 },
            dist = { "GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E63
            note = "overhead @ bedroom",
            coords = { x = 9849, y = 13124, z = -4 },
            slot = "upper",
            dist = { "ButcherSpices", "GigamartSpices", "GroceryBagGourmet", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E64
            note = "fridge @ bedroom",
            coords = { x = 9848, y = 13124, z = -4 },
            dist = { "SafehouseFridge" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E65
            note = "freezer @ bedroom",
            coords = { x = 9848, y = 13124, z = -4 },
            slot = "freezer",
            dist = { "SafehouseFreezer" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E66
            note = "overhead @ bedroom",
            coords = { x = 9848, y = 13124, z = -4 },
            slot = "upper",
            dist = { "CrateTortillaChips", "KitchenDryFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- infirmary
        { -- E67
            note = "militarycrate @ infirmary",
            coords = { x = 9845, y = 13123, z = -4 },
            dist = { "CrateTortillaChips", "KitchenDryFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E68
            note = "militarycrate @ infirmary",
            coords = { x = 9845, y = 13121, z = -4 },
            dist = { "CrateTortillaChips", "KitchenDryFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E69
            note = "medicine @ infirmary",
            coords = { x = 9845, y = 13121, z = -4 },
            slot = "upper",
            dist = { "MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E70
            note = "medicine @ infirmary",
            coords = { x = 9850, y = 13121, z = -4 },
            dist = { "LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E71
            note = "medicine @ infirmary",
            coords = { x = 9851, y = 13121, z = -4 },
            dist = { "MedicalClinicDrugs", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E72
            note = "militarycrate @ infirmary",
            coords = { x = 9851, y = 13123, z = -4 },
            dist = { "GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- machine room
        { -- E73
            note = "cardboardbox @ garagestorage",
            coords = { x = 9845, y = 13120, z = -4 },
            dist = { "GasStoreEmergency", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E74
            note = "metal_shelves @ garagestorage",
            coords = { x = 9845, y = 13118, z = -4 },
            dist = { "ArmyHangarTools", "GasStorageMechanics", "GarageTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E75
            note = "metal_shelves @ garagestorage",
            coords = { x = 9846, y = 13120, z = -4 },
            dist = { "CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools", "GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E76
            note = "metal_shelves @ garagestorage",
            coords = { x = 9847, y = 13120, z = -4 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E77
            note = "metal_shelves @ garagestorage",
            coords = { x = 9848, y = 13120, z = -4 },
            dist = { "BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E78
            note = "metal_shelves @ garagestorage",
            coords = { x = 9849, y = 13120, z = -4 },
            dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E79
            note = "metal_shelves @ garagestorage",
            coords = { x = 9850, y = 13120, z = -4 },
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E80
            note = "metal_shelves @ garagestorage",
            coords = { x = 9851, y = 13120, z = -4 },
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- office
        { -- E81
            note = "desk @ office",
            coords = { x = 9839, y = 13117, z = -4 },
            dist = { "MusicStoreCDs" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E82
            note = "filingcabinet @ office",
            coords = { x = 9837, y = 13118, z = -4 },
            dist = { "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E83
            note = "shelves @ office",
            coords = { x = 9837, y = 13117, z = -4 },
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E84
            note = "militarycrate @ office",
            coords = { x = 9837, y = 13116, z = -4 },
            dist = { "CrateLiquor" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E85
            note = "militarycrate @ office",
            coords = { x = 9837, y = 13116, z = -4 },
            stack = 2,
            dist = { "CrateLiquor" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bathrooms
        { -- E86
            note = "counter @ bathroom",
            coords = { x = 9842, y = 13114, z = -4 },
            dist = { "BookstoreBiography", "BathroomCounter", "BookstoreComputer", "BookstoreCrimeFiction" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E87
            note = "locker @ bathroom",
            coords = { x = 9840, y = 13115, z = -4 },
            dist = { "BathroomCounter", "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E88
            note = "counter @ bathroom",
            coords = { x = 9845, y = 13114, z = -4 },
            dist = { "SewingStoreTools", "SewingStoreFabric", "CrateLeather" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
    },
}

return MRSecret
