-- @TODO (2026-08-07 audit) unresolved - delete lines as they are fixed
--   * entries 1,53,54,56,57,59,60,61,63: square holds no container at all -
--     coords are stale or the object was removed
--   * entries 2,7,9: square has a container but not the one addressed - needs
--     slot = "upper" / "freezer" or stack = n
--   * entries 58,62: resolved to a container but no DWAP stamp - the freezer
--     bug is fixed, so these are the only unexplained fills left
--   * systems: 19 components at 11903-11908,6845-6865 z=0,1 name a sprite
--     that is not on the square, though the square itself loads - config
--     drifted from the map
local wtc1 = {x = 11912, y = 6844, z = -1,}
local pb1 = { x = 11907, y = 6843, z = -1 }
local TheDrake = {
    group = "West Point",
    baseBuildings = {
        { x = 11908, y = 6853, z = 1 }, -- apartments
        { x = 11908, y = 6853, z = -1 }, -- basement
    },
    spawn = { x = 11908, y = 6853, z = 1 },
    generators = {
        {
            controls = { sprite = "dwap_tiles_01_22", x = 11908, y = 6844, z = pb1.z },
            fuelTank = { sprite = "dwap_tiles_01_24", x = 11910, y = 6844, z= -1, },
            fakeGenerators = {
                { x = 11913, y = 6851, z = -1, createTile = false },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_8", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 11911, y = 6844, z = -1} },
    },
    waterFixtures = {
        -- 2nd floor apts
        { sprite = "fixtures_sinks_01_9", x = 11908, y = 6851, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_0", x = 11906, y = 6851, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_12", x = 11905, y = 6851, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 11904, y = 6851, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_11", x = 11908, y = 6850, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 11906, y = 6850, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_28", x = 11905, y = 6850, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 11904, y = 6849, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_10", x = 11907, y = 6865, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_2", x = 11907, y = 6863, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_29", x = 11907, y = 6862, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_26", x = 11906, y = 6861, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_8", x = 11908, y = 6865, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_1", x = 11908, y = 6863, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_13", x = 11908, y = 6862, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_26", x = 11908, y = 6861, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        -- 1st floor
        { sprite = "fixtures_sinks_01_17", x = 11903, y = 6845, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_18", x = 11904, y = 6849, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_13", x = 11904, y = 6858, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_1", x = 11904, y = 6859, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        -- basement
        { sprite = "fixtures_sinks_01_2", x = 11902, y = 6839, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "appliances_laundry_01_2", x = 11902, y = 6841, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_1", x = 11896, y = 6841, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

    },
    doorKeys = {
        name = "The Drake",
        doors = {
            { sprite = "fixtures_doors_02_5", x = 11905, y = 6841, z = -1, },
            { sprite = "fixtures_doors_02_4", x = 11912, y = 6852, z = 0, },
            { sprite = "fixtures_doors_01_52", x = 11902, y = 6860, z = 0, },
            { sprite = "fixtures_doors_01_0", x = 11904, y = 6854, z = 1, },
        },
    },
    map = { name = "DWAPStashMap27", },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_51", x = 11914, y = 6859, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_52", x = 11914, y = 6858, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_53", x = 11914, y = 6857, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_4", x = 11913, y = 6853, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_4", x = 11913, y = 6852, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_51", x = 11914, y = 6848, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_52", x = 11914, y = 6847, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_02_53", x = 11914, y = 6846, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_01_52", x = 11902, y = 6860, z = 0, },
    },
    loot = {
        -- basement
        -- shelter area
        { -- E1
            type = 'container',
            coords = {x=11896,y=6843,z=-1},
            slot = "upper",
            dist = {"SafehouseMedical", "BathroomCounter", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E2
            type = 'container',
            coords = {x=11900,y=6841,z=-1},
            slot = "upper",
            dist = {"MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E3
            type = 'container',
            coords = {x=11901,y=6839,z=-1},
            special = "essentials",
        },
        { -- E4
            type = 'container',
            coords = {x=11902,y=6839,z=-1},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E5
            type = 'container',
            coords = {x=11902,y=6841,z=-1},
            slot = "upper",
            dist = {"LaundryCleaning", "JanitorCleaning", "Homesteading"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E6
            type = 'container',
            coords = {x=11903,y=6839,z=-1},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E7
            type = 'container',
            coords = {x=11903,y=6841,z=-1},
            slot = "upper",
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E8
            type = 'container',
            coords = {x=11904,y=6839,z=-1},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E9
            type = 'container',
            coords = {x=11904,y=6841,z=-1},
            slot = "upper",
            dist = {"SafehouseFireplace", "SafehouseLighting", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E10
            type = 'container',
            coords = {x=11906,y=6839,z=-1},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E11
            type = 'container',
            coords = {x=11907,y=6839,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E12
            type = 'container',
            coords = {x=11908,y=6839,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E13
            type = 'container',
            coords = {x=11909,y=6839,z=-1},
            dist = {"ArmyStorageAmmunition", "GunStoreKnives", "PawnShopKnives", "DerelictHouseCrime" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E14
            type = 'container',
            coords = {x=11910,y=6839,z=-1},
            dist = {"GunStoreAmmunition", "GunStoreKnives", "GunStoreBodyArmor", "GunStoreMagsAmmo", "GunStoreGuns", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E15
            type = 'container',
            coords = {x=11911,y=6839,z=-1},
            dist = {"CrateFishing", "FishermanTools", "Trapper"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E16
            type = 'container',
            coords = {x=11912,y=6839,z=-1},
            dist = {"GasStoreEmergency"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E17
            type = 'container',
            coords = {x=11913,y=6839,z=-1},
            dist = {"LoggingFactoryTools", "CrateTools", "GarageTools", "BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E18
            type = 'container',
            coords = {x=11914,y=6839,z=-1},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMetalwork", "CrateMechanics", "CrateMasonry", "CrateTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E19
            type = 'container',
            coords = {x=11914,y=6841,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E20
            type = 'container',
            coords = {x=11913,y=6841,z=-1},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E21
            type = 'container',
            coords = {x=11912,y=6841,z=-1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E22
            type = 'container',
            coords = {x=11911,y=6841,z=-1},
            dist = {"CrateBooks", "MusicStoreCDs", "CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E23
            type = 'container',
            coords = {x=11910,y=6841,z=-1},
            dist = {"ArmySurplusBackpacks", "ArmySurplusOutfit", "ArmyStorageOutfit", "ArmySurplusFootwear", "ArmySurplusHeadwear", "ArmySurplusMisc" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E24
            type = 'container',
            coords = {x=11909,y=6841,z=-1},
            dist = {"GigamartCannedFood", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E25
            type = 'container',
            coords = {x=11908,y=6841,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E26
            type = 'container',
            coords = {x=11907,y=6841,z=-1},
            dist = {"MorgueTools", "MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E27
            type = 'container',
            coords = {x=11906,y=6841,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E28
            type = 'container',
            coords = {x=11904,y=6841,z=-1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E29
            type = 'container',
            coords = {x=11903,y=6841,z=-1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E30
            type = 'container',
            coords = {x=11900,y=6841,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E31
            type = 'container',
            coords = {x=11899,y=6841,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        -- rest of basement
        { -- E32
            type = 'container',
            coords = {x=11907,y=6846,z=-1},
            dist = {"CrateLumber"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E33
            type = 'container',
            coords = {x=11907,y=6847,z=-1},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E34
            type = 'container',
            coords = {x=11913,y=6857,z=-1},
            dist = {"CrateSheetMetal" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E35
            type = 'container',
            coords = {x=11913,y=6869,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E36
            type = 'container',
            coords = {x=11907,y=6865,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- storage rooms, south to north
        { -- E37
            type = 'container',
            coords = {x=11904,y=6858,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E38
            type = 'container',
            coords = {x=11904,y=6854,z=-1},
            dist = {"SafehouseTraps",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E39
            type = 'container',
            coords = {x=11902,y=6854,z=-1},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E40
            type = 'container',
            coords = {x=11902,y=6853,z=-1},
            dist = {"ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E41
            type = 'container',
            coords = {x=11902,y=6852,z=-1},
            dist = {"StoreShelfMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E42
            type = 'container',
            coords = {x=11904,y=6850,z=-1},
            dist = { "CrateLeather", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E43
            type = 'container',
            coords = {x=11902,y=6848,z=-1},
            dist = {"SewingStoreTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E44
            type = 'container',
            coords = {x=11902,y=6847,z=-1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "ArmySurplusOutfit", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E45
            type = 'container',
            coords = {x=11903,y=6847,z=-1},
            dist = { "SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E46
            type = 'container',
            coords = {x=11904,y=6846,z=-1},
            dist = {"ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- first floor
        -- bar area
        { -- E47
            type = 'container',
            coords = {x=11902,y=6853,z=0},
            dist = {"CrateBeer",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E48
            type = 'container',
            coords = {x=11902,y=6852,z=0},
            dist = {"CrateWine",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E49
            type = 'container',
            coords = {x=11902,y=6851,z=0},
            dist = {"StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E50
            type = 'container',
            coords = {x=11902,y=6850,z=0},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E51
            type = 'container',
            coords = {x=11902,y=6849,z=0},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            type = 'container',
            coords = {x=11902,y=6848,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E53
            type = 'container',
            coords = {x=11904,y=6849,z=0},
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E54
            type = 'container',
            coords = {x=11904,y=6848,z=0},
            dist = {"TestingLab", "TobaccoStoreAccessories", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bar kitchen
        { -- E55
            type = 'container',
            coords = {x=11902,y=6846,z=0},
            dist = {"BurgerKitchenFridge","BurgerKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E56
            type = 'container',
            coords = {x=11902,y=6845,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E57
            type = 'container',
            coords = {x=11904,y=6845,z=0},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E58
            type = 'container',
            coords = {x=11902,y=6859,z=0},
            slot = "upper",
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- 2nd floor apt
        { -- E59
            type = 'container',
            coords = {x=11909,y=6851,z=1},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E60
            type = 'container',
            coords = {x=11908,y=6851,z=1},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E61
            type = 'container',
            coords = {x=11907,y=6851,z=1},
            dist = {"BurgerKitchenFridge","BurgerKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E62
            type = 'container',
            coords = {x=11913,y=6851,z=1},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E63
            type = 'container',
            coords = {x=11905,y=6851,z=1},
            slot = "upper",
            dist = {"MedicalCabinet","BathroomCounter",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(TheDrake.objectSpawns, { enabled = "EnableLadders", x = 11889, y = 6880, z = 0, removeFloor = true, })
    table.insert(TheDrake.objectSpawns, { enabled = "EnableLadders", sprite = "location_business_office_generic_01_35", x = 11889, y = 6879, z = 0, })
end

return TheDrake