local wtc0 = {x = 14152, y = 2635, z = -1,} -- tank for the core area
local wtc1 = {x = 14148, y = 2658, z = -1,} -- tank for the southern house
local wtc2 = {x = 14178, y = 2629, z = -1,} -- tank for the eastern house
local wtc3 = {x = 14150, y = 2607, z = -1,} -- tank for the northern house
local pb1 = { x = 14151, y = 2631, z = -1 }
local bunker1TopLeft = {x = 14145, y = 2648, z = -1}
local bunker2TopLeft = {x = 14176, y = 2619, z = -1}
local bunker3TopLeft = {x = 14148, y = 2597, z = -1}
local LVilleComplex = {
    spawn = { x = 14140, y = 2656, z = 1 },
    generators = {
        { -- southern house
            controls = { sprite = "industry_02_67", x = 14156, y = 2632, z = -4, },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = pb1.x, y = pb1.y, z = pb1.z },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2637,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2638,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2639,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2640,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2641,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2642,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14147,
                        y = 2637,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14147,
                        y = 2638,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14147,
                        y = 2639,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14147,
                        y = 2640,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14147,
                        y = 2641,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_9",
                        x = 14145,
                        y = 2642,
                        z = 0,
                        pb = 1,
                        spawn = true,
                    },
                },
            },
            fakeGenerators = {
                { x = 14147, y = 2663, z = -1, createTile = true },
                { x = 14152, y = 2636, z = -4, createTile = true },
            },
        },
        { -- eastern house
            controls = { sprite = "industry_02_67", x = 14156, y = 2628, z = -4, },
            fakeGenerators = {
                { x = 14180, y = 2631, z = -1, createTile = true },
            },
        },
        { -- northern house
            controls = { sprite = "industry_02_67", x = 14156, y = 2624, z = -4, },
            fakeGenerators = {
                { x = 14158, y = 2605, z = -1, createTile = true },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = 14150, y = 2635, z = -4, sourceType="generator", source = {x = 14156, y = 2632, z = -4} },
        { sprite = "dwap_tiles_01_8", x = wtc0.x, y = wtc0.y, z = wtc0.z, sourceType="generator", source = {x = 14156, y = 2632, z = -4} },
        { sprite = "dwap_tiles_01_9", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 14156, y = 2632, z = -4} },
        { sprite = "dwap_tiles_01_8", x = wtc2.x, y = wtc2.y, z = wtc2.z, sourceType="generator", source = {x = 14156, y = 2628, z = -4} },
        { sprite = "dwap_tiles_01_8", x = wtc3.x, y = wtc3.y, z = wtc3.z, sourceType="generator", source = {x = 14156, y = 2624, z = -4} },
    },
    waterFixtures = {
        -- core -1
        { sprite = "appliances_laundry_01_1", x = 14144, y = 2626, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_24", x = 14146, y = 2627, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_16", x = 14149, y = 2625, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_30", x = 14151, y = 2628, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_30", x = 14152, y = 2628, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_30", x = 14153, y = 2628, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_22", x = 14151, y = 2630, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_22", x = 14152, y = 2630, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_22", x = 14153, y = 2630, z = -1, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        -- core -2
        { sprite = "fixtures_sinks_01_16", x = 14148, y = 2625, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "location_shop_zippee_01_57", x = 14148, y = 2626, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_0", x = 14144, y = 2639, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_0", x = 14145, y = 2639, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_0", x = 14146, y = 2639, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_28", x = 14144, y = 2641, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_28", x = 14145, y = 2641, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_32", x = 14148, y = 2639, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "appliances_laundry_01_0", x = 14149, y = 2639, z = -2, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        -- core -4
        { sprite = "fixtures_bathroom_01_5", x = 14144, y = 2636, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_24", x = 14146, y = 2636, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_5", x = 14144, y = 2639, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_24", x = 14146, y = 2639, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_30", x = 14147, y = 2641, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_24", x = 14149, y = 2636, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_6", x = 14151, y = 2638, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_sinks_01_24", x = 14149, y = 2639, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        { sprite = "fixtures_bathroom_01_6", x = 14151, y = 2641, z = -4, sourceType="tank", source = {x = wtc0.x, y = wtc0.y, z = wtc0.z} },
        -- southern house
        { sprite = "fixtures_bathroom_01_6", x = 14147, y = 2656, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_16", x = 14145, y = 2652, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_28", x = 14152, y = 2662, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 14153, y = 2662, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_11", x = 14151, y = 2667, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_4", x = 14145, y = 2667, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "appliances_laundry_01_5", x = 14145, y = 2665, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_1", x = 14150, y = 2662, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_1", x = 14150, y = 2661, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_1", x = 14151, y = 2660, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 14153, y = 2660, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_28", x = 14147, y = 2667, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 14145, y = 2667, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_25", x = 14144, y = 2666, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        -- eastern house
        { sprite = "fixtures_bathroom_01_6", x = 14178, y = 2627, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_16", x = 14176, y = 2623, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "appliances_laundry_01_3", x = 14188, y = 2632, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_2", x = 14191, y = 2630, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_29", x = 14191, y = 2631, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_10", x = 14191, y = 2638, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_10_26", x = 14190, y = 2635, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 14191, y = 2637, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 14190, y = 2637, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 14189, y = 2637, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 14184, y = 2641, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_0", x = 14183, y = 2641, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_3", x = 14181, y = 2641, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_26", x = 14179, y = 2641, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_32", x = 14179, y = 2639, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        -- northern house
        { sprite = "fixtures_bathroom_01_6", x = 14150, y = 2605, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_16", x = 14148, y = 2601, z = -1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_29", x = 14153, y = 2601, z = 0, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_bathroom_01_2", x = 14153, y = 2602, z = 0, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "appliances_laundry_01_3", x = 14155, y = 2597, z = 0, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_6", x = 14155, y = 2595, z = 0, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_11", x = 14160, y = 2606, z = 0, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_bathroom_01_26", x = 14150, y = 2602, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_bathroom_01_0", x = 14150, y = 2600, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_2", x = 14151, y = 2600, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_2", x = 14152, y = 2600, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_bathroom_01_25", x = 14157, y = 2603, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_bathroom_01_2", x = 14161, y = 2604, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_29", x = 14161, y = 2605, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },
        { sprite = "fixtures_sinks_01_29", x = 14161, y = 2606, z = 1, sourceType="tank", source = {x = wtc3.x, y = wtc3.y, z = wtc3.z} },

    },
    doorKeys = {
        name = "Louisville Complex",
        doors = {
            -- core
            { sprite = "fixtures_doors_01_32", x = 14147, y = 2637, z = -4, },
            -- southern
            { sprite = "fixtures_doors_01_45", x = 14147, y = 2655, z = 0, },
            -- eastern
            { sprite = "fixtures_doors_02_4", x = 14179, y = 2635, z = 0, },
            -- northern
            { sprite = "fixtures_doors_01_45", x = 14155, y = 2605, z = 0, },
        },
    },
    map = { name = "DWAPStashMap29", },
    objectSpawns = {
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        -- southern house
        -- { x = 14139, y = 2662, z = 0, removeWall = "north" },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_8", x = 14139, y = 2659, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_9", x = 14140, y = 2654, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_9", x = 14143, y = 2654, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_24", x = 14154, y = 2661, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_24", x = 14154, y = 2665, z = 0, },
        -- { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_27", x = 14148, y = 2668, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_25", x = 14142, y = 2668, z = 0, },
        -- eastern house
        -- { x = 14185, y = 2635, z = 0, removeWall = "west" },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_8", x = 14179, y = 2640, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_8", x = 14179, y = 2638, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_41", x = 14190, y = 2630, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_24", x = 14192, y = 2638, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_4", x = 14192, y = 2640, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_25", x = 14187, y = 2642, z = 0, },
        -- northern house
        -- { x = 14157, y = 2597, z = 0, removeWall = "west" },
        -- { sprite = "industry_trucks_01_4", x = 14155, y = 2618, z = -1, },
        -- { sprite = "floors_exterior_street_01_16", x = 14155, y = 2618, z = -1, },
        -- { sprite = "floors_exterior_street_01_16", x = 14156, y = 2618, z = -1, },
        -- { sprite = "industry_trucks_01_4", x = 14157, y = 2618, z = -1, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_25", x = 14160, y = 2607, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_25", x = 14158, y = 2607, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_72", x = 14148, y = 2599, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_73", x = 14151, y = 2595, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_5", x = 14154, y = 2595, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_41", x = 14159, y = 2595, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_02_25", x = 14163, y = 2601, z = 0, },
    },
    loot = {
        -- {
        --     type = 'container',
        --     coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+2,z=bunker1TopLeft.z},
        --     sandboxEnable = 'Loot_EnableMaps',
        --     special = "maps",
        -- },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+3,z=bunker1TopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+3,z=bunker1TopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+4,z=bunker1TopLeft.z+0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+4,z=bunker1TopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+5,z=bunker1TopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+5,z=bunker1TopLeft.z},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+7,z=bunker1TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+8,z=bunker1TopLeft.z},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+9,z=bunker1TopLeft.z},
            dist = {"BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+10,z=bunker1TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+11,z=bunker1TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x,y=bunker1TopLeft.y+12,z=bunker1TopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y+5,z=bunker1TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y+6,z=bunker1TopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y+7,z=bunker1TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y,z=bunker1TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y+1,z=bunker1TopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y,z=bunker1TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker1TopLeft.x+2,y=bunker1TopLeft.y+1,z=bunker1TopLeft.z},
            dist = {"GunStoreKnives","CrateLiquor", "GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+3,z=bunker2TopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+3,z=bunker2TopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+4,z=bunker2TopLeft.z+0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+4,z=bunker2TopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+5,z=bunker2TopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+5,z=bunker2TopLeft.z},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+7,z=bunker2TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+8,z=bunker2TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+9,z=bunker2TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+10,z=bunker2TopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+11,z=bunker2TopLeft.z},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x,y=bunker2TopLeft.y+12,z=bunker2TopLeft.z},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y+5,z=bunker2TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y+6,z=bunker2TopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y+7,z=bunker2TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y,z=bunker2TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y+1,z=bunker2TopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y,z=bunker2TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker2TopLeft.x+2,y=bunker2TopLeft.y+1,z=bunker2TopLeft.z},
            dist = {"GunStoreKnives","CrateLiquor", "GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+2,z=bunker3TopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+3,z=bunker3TopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+3,z=bunker3TopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+4,z=bunker3TopLeft.z+0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+4,z=bunker3TopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+5,z=bunker3TopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+5,z=bunker3TopLeft.z},
            dist = {"GigamartCrisps","ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+7,z=bunker3TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+8,z=bunker3TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+9,z=bunker3TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+10,z=bunker3TopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+11,z=bunker3TopLeft.z},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x,y=bunker3TopLeft.y+12,z=bunker3TopLeft.z},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y+5,z=bunker3TopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y+6,z=bunker3TopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y+7,z=bunker3TopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y,z=bunker3TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y+1,z=bunker3TopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y,z=bunker3TopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunker3TopLeft.x+2,y=bunker3TopLeft.y+1,z=bunker3TopLeft.z},
            dist = {"GunStoreKnives","CrateLiquor", "GasStorageMechanics","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        ------------------------
        --- Core Bunker Area ---
        ------------------------
        { -- decon locker
            type = 'container',
            coords = {x = 14149, y = 2628, z = -1},
            items = {
                { name = 'Base.Oxygen_Tank', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- decon locker
            type = 'container',
            coords = {x = 14149, y = 2629, z = -1},
            items = {
                { name = 'Base.Bag_ProtectiveCaseBulkyHazard', },
                { name = 'Base.Hat_NBCmask', },
                { name = 'Base.Glasses_SafetyGoggles', },
                { name = 'Base.Hat_BuildersRespirator', },
                { name = 'Base.HazmatSuit', },
                { name = 'Base.RespiratorFilters', },
                { name = 'Base.Hat_GasMask', },
                { name = 'Base.GasmaskFilter', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- decon locker
            type = 'container',
            coords = {x = 14149, y = 2630, z = -1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        -- infirmary
        {
            type = 'container',
            coords = {x = 14149, y = 2627, z = -1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2626, z = -1},
            dist = {"MedicalClinicDrugs" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2625, z = -1},
            dist = {"MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2623, z = -1},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14153, y = 2623, z = -1},
            dist = {"MedicalClinicDrugs" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14153, y = 2627, z = -1},
            dist = {"LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- fridge
            type = 'container',
            coords = {x = 14152, y = 2627, z = -1},
            dist = {"SafehouseMedical_Late", "StoreShelfMedical", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- gym
        {
            type = 'container',
            coords = {x = 14144, y = 2625, z = -1},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2626, z = -0.5},
            dist = {"FitnessTrainer"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2625, z = -0.5},
            dist = {"CrateFitnessWeights"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- pantry
        {
            type = 'container',
            coords = {x = 14144, y = 2626, z = -2},
            dist = {"CrateTortillaChips", "CandyStoreSnacks","FridgeSoda",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2625, z = -2},
            dist = {"WesternKitchenSauce", "WhiskeyBottlingFull", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2624, z = -2},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2623, z = -2},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14145, y = 2623, z = -2},
            dist = {"BurgerKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2623, z = -2},
            dist = {"WesternKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14147, y = 2623, z = -2},
            dist = {"ButcherFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14147, y = 2625, z = -2},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14147, y = 2626, z = -2},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2626, z = -2},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14145, y = 2626, z = -2},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- dining/bar area
        {
            type = 'container', -- drinks under sink
            coords = {x = 14148, y = 2625, z = -2},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2623, z = -2},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2623, z = -2},
            dist = {"CatfishKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14154, y = 2623, z = -2},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2623, z = -2},
            dist = {"StoreKitchenBaking", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2624, z = -2},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2625, z = -2},
            dist = {"KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2626, z = -2},
            dist = {"KitchenBottles", "CrateSodaCans", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2627, z = -2},
            dist = {"LiquorStoreMix", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2628, z = -2},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2629, z = -2},
            dist = {"LiquorStoreBrandy", "LiquorStoreGin"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container', -- media center
            coords = {x = 14156, y = 2630, z = -2},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container', -- theater stand
            coords = {x = 14156, y = 2633, z = -2},
            dist = {"TheatreDrinks", "TheatreSnacks"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container', -- theater stand
            coords = {x = 14156, y = 2634, z = -2},
            dist = {"TheatrePopcorn", "TheatreSnacks"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bunk rooms
        {
            type = 'container',
            coords = {x = 14146, y = 2642, z = -2},
            dist = {"ArmyHangarOutfit", "ArmyStorageOutfit", "ArmySurplusOutfit", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2641, z = -1.5},
            dist = {"JanitorCleaning","MedicalCabinet","MedicalClinicDrugs", "CrateLinens"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x = 14145, y = 2641, z = -1.5},
            dist = {"BathroomCounter", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2636, z = -2},
            dist = {"DrugLabOutfit", "MechanicOutfit", "WildWestClothing"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2638, z = -2},
            dist = {"BackstageClothingRack", "ArmySurplusOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14150, y = 2638, z = -2},
            dist = {"ClothingStorageWinter", "GymLaundry"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14150, y = 2637, z = -2},
            dist = {"SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2644, z = -2},
            dist = {"SafehouseArmor", "ArmySurplusOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- reading lounge
        {
            type = 'container',
            coords = {x = 14145, y = 2630, z = -3},
            dist = {"CrateVHSTapes","BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 14145, y = 2629, z = -3},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 14145, y = 2628, z = -3},
            dist = {"BookstoreMilitaryHistory"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2627, z = -3},
            dist = {"LivingRoomShelf"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2628, z = -3},
            dist = {"LivingRoomShelfClassy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2629, z = -3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2630, z = -3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2631, z = -3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2634, z = -3},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2635, z = -3},
            dist = {"ArmyStorageElectronics", "RandomFiller" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- security office
        {
            type = 'container',
            coords = {x = 14144, y = 2626, z = -3},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x = 14147, y = 2626, z = -3},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x = 14147, y = 2623, z = -3},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2623, z = -3},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 14149, y = 2623, z = -3},
            dist = {"MeleeWeapons", "MeleeWeapons_Mid" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- gun range
        {
            type = 'container',
            coords = {x = 14152, y = 2623, z = -3},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 14154, y = 2623, z = -3},
            dist = {"GunStoreKnives", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "MeleeWeapons", "MeleeWeapons_Mid" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2623, z = -3},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- -4
        -- stairway shelves
        {
            type = 'container',
            coords = {x = 14146, y = 2628, z = -4},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2627, z = -4},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2628, z = -4},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2627, z = -4},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- warehouse/utility
        {
            type = 'container',
            coords = {x = 14144, y = 2625, z = -4},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2624, z = -4},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 14144, y = 2623, z = -4},
            dist = {"CrateTailoring", "CrateFabric_Cotton", "CrateFabric_DenimBlack", "CrateLeather","SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2625, z = -4},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2624, z = -4},
            dist = {"RailYardTools","Homesteading","SurvivalGear"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 14146, y = 2623, z = -4},
            dist = {"WireFactoryBarbed", "CrateLongStick", "WireFactoryBasic"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2625, z = -4},
            dist = {"GasStoreEmergency","StoreCounterTobacco", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2624, z = -4},
            dist = {"ToolCabinetMechanics","CrateMechanics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 14148, y = 2623, z = -4},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2634, z = -4},
            dist = {"ToolStoreMetalwork","CrateBlacksmithing", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 14156, y = 2635, z = -4},
            dist = {"RailYardSpikes", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x = 14154, y = 2635, z = -4},
            dist = {"CrateCarpentry","LoggingFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x = 14152, y = 2635, z = -4},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
    },
}

return LVilleComplex