
local wtcHouse = {x = 7678, y = 12271, z = 1}
local wtcTunnel = {x = 7684, y = 12221, z = -1}
local PrisonBreak = {
    spawn = { x = 7680, y = 12018, z = -1 },
    optionalSpawn = {
        beforeTeleport = "DWAP_31_beforeTeleport",
        -- afterTeleport = "DWAP_31_afterTeleport",
        question = "IGUI_DWAP_31_OptionalSpawnQ",
        coords = { x = 7680, y = 11854, z = 0 },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z, sourceType="generator", source = {x = 7681, y = 12221, z = -1} },
        { sprite = "crafted_01_11", x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z, isProp = true, sourceType="generator", source = {x = 7681, y = 12221, z = -1} },
    },
    waterFixtures = {
        -- house
        { sprite = "fixtures_bathroom_01_25", x = 7674, y = 12271, z = 0, sourceType="tank", source = {x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z} },
        { sprite = "fixtures_bathroom_01_0", x = 7675, y = 12271, z = 0, sourceType="tank", source = {x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z} },
        { sprite = "fixtures_sinks_01_22", x = 7676, y = 12271, z = 0, sourceType="tank", source = {x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z} },
        { sprite = "fixtures_sinks_01_10", x = 7684, y = 12269, z = 0, sourceType="tank", source = {x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z} },
        -- tunnel
        { sprite = "appliances_laundry_01_1", x = 7681, y = 12219, z = -1, sourceType="tank", source = {x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z} },
        { sprite = "fixtures_bathroom_01_33", x = 7681, y = 12217, z = -1, sourceType="tank", source = {x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z} },
        { sprite = "fixtures_sinks_01_12", x = 7683, y = 12217, z = -1, sourceType="tank", source = {x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z} },
        { sprite = "fixtures_bathroom_01_3", x = 7683, y = 12219, z = -1, sourceType="tank", source = {x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z} },
        { sprite = "fixtures_sinks_01_4", x = 7681, y = 12213, z = -1, sourceType="tank", source = {x = wtcTunnel.x, y = wtcTunnel.y, z = wtcTunnel.z} },
    },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 7681, y = 12221, z = -1, },
            fakeGenerators = {
                { x = 7678, y = 12277, z = -1, createTile = true },
                { x = 7678, y = 12256, z = -1, createTile = true },
                { x = 7678, y = 12235, z = -1, createTile = true },
                { x = 7687, y = 12216, z = -1, createTile = true },
                -- { x = 7678, y = 12210, z = -1, createTile = true },
                { x = 7678, y = 12195, z = -1, createTile = true },
                { x = 7678, y = 12174, z = -1, createTile = true },
                { x = 7678, y = 12153, z = -1, createTile = true },
                { x = 7678, y = 12132, z = -1, createTile = true },
            },
        },
    },
    doorKeys = {
        name = "South Rosewood Home",
        doors = {
            { sprite = "fixtures_doors_01_45", x = 2611, y = 14456, z = 0, },
            { sprite = "fixtures_doors_01_53", x = 2608, y = 14449, z = -1, },
            { sprite = "location_community_police_01_4", x = 7684, y = 11854, z = 0, },
            { sprite = "location_community_police_01_4", x = 7678, y = 12268, z = 0, },
        },
    },
    map = { name = "DWAPStashMap31", },
    objectSpawns = {
        { sprite = "crafted_01_11", x = wtcHouse.x, y = wtcHouse.y, z = wtcHouse.z, enabled = "EnableWaterSystem", },

      -- a to b junction
        -- { sprite = "walls_exterior_house_01_4", x = 7674, y = 12227, z = -1, replaceWall = true,},
        -- { sprite = "industry_02_194", x = 7674, y = 12227, z = -1, },
        -- { sprite = "floors_exterior_natural_01_10", x = 7674, y = 12227, z = -1, },
        -- { sprite = "walls_exterior_house_01_4", x = 7678, y = 12227, z = -1, removeWall = "west", clearExisting = true},

        -- -- b to c junction
        -- { sprite = "walls_exterior_house_01_4", x = 7674, y = 12177, z = -1, replaceWall = true,},
        -- { sprite = "industry_02_194", x = 7674, y = 12177, z = -1, },
        -- { sprite = "floors_exterior_natural_01_10", x = 7674, y = 12177, z = -1, },
        -- { sprite = "walls_exterior_house_01_4", x = 7678, y = 12177, z = -1, removeWall = "west", clearExisting = true},

        -- -- c to d junction
        -- { sprite = "walls_logs_99", x = 7676, y = 11987, z = -1,},
        -- { sprite = "floors_exterior_natural_01_10", x = 7677, y = 11987, z = -1, },
        -- { sprite = "walls_logs_97", x = 7677, y = 11987, z = -1, removeWall = "north", clearExisting = true},

        -- -- d into prison
        -- { sprite = "walls_logs_97", x = 7677, y = 11887, z = -1,},
        -- { sprite = "floors_exterior_natural_01_10", x = 7677, y = 11887, z = -1, },
        -- { sprite = "walls_logs_98", x = 7677, y = 11888, z = -1, clearExisting = true},
        -- { sprite = "walls_commercial_01_58", x = 7678, y = 11887, z = -1, removeWall = "west"},


        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 7675, y = 12275, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 7682, y = 12275, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 7685, y = 12272, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 7685, y = 12269, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_04_93", x = 7680, y = 12268, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_03_40", x = 7674, y = 12269, z = 0, },
    },
    loot = {
        -- prison cell spawn
        {
            type = 'container',
            coords = {x=7678,y=11853,z=0},
            items = {
                { name = 'Base.Nightstick', },
                { name = 'Base.ShortBat', },
                { name = 'Base.Hammer', },
                { name = 'Base.Screwdriver', },
                { name = 'Base.Saw', },
            },
            dist = {"PrisonCellRandom", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = 2,
        },
        -- camp room near prison
        {
            type = 'container',
            coords = {x=7686,y=12015,z=-1},
            dist = {"CrateLumber",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12016,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12017,z=-1},
            items = {
                { name = 'Base.NailsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- tunnel
        {
            type = 'container',
            coords = {x=7674,y=12166,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- main underground rooms
        -- generator/ warehouse room
        {
            type = 'container',
            coords = {x=7679,y=12225,z=-1},
            dist = {"CrateBlacksmithing", "CrateCarpentry", "CrateMechanics", "CrateMetalwork" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7679,y=12224,z=-1},
            dist = {"CrateVHSTapes","BookstoreNonFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12225,z=-1},
            dist = {"ArmyHangarOutfit", "ArmyStorageOutfit", "ArmySurplusOutfit", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12224,z=-1},
            dist = {"CrateTailoring", "CrateFabric_Cotton", "CrateFabric_DenimBlack", "CrateLeather","SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=7682,y=12225,z=-1},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7682,y=12224,z=-1},
            dist = {"GasStoreEmergency","StoreCounterTobacco", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7682,y=12223,z=-1},
            dist = {"ToolCabinetMechanics","CrateMechanics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12225,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12224,z=-1},
            dist = {"ToolStoreMetalwork","CrateBlacksmithing", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12223,z=-1},
            dist = {"RailYardSpikes", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12225,z=-1},
            dist = {"CrateCarpentry","LoggingFactoryTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12223,z=-1},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12226,z=-1},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12225,z=-1},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12224,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        {
            type = 'container',
            coords = {x=7686,y=12223,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=7686,y=12222,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=7686,y=12221,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=7686,y=12220,z=-1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=7685,y=12220,z=-1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        -- bar area
        {
            type = 'container',
            coords = {x=7678,y=12219,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7678,y=12218,z=-1},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7678,y=12217,z=-1},
            dist = {"LiquorStoreBrandy", "LiquorStoreGin"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- bathroom
        { -- over sink cabinet
            type = 'container',
            coords = {x=7683,y=12217,z=-0.5},
            dist = {"JanitorCleaning","MedicalCabinet","MedicalClinicDrugs", "CrateLinens"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=7681,y=12219,z=-0.5},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- south bunk room
        {
            type = 'container',
            coords = {x=7684,y=12217,z=-1},
            dist = {"SafehouseArmor", "ArmySurplusOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12217,z=-1},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- north bunk room
        {
            type = 'container',
            coords = {x=7684,y=12213,z=-1},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=7686,y=12213,z=-1},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- med bay
        {
            type = 'container',
            coords = {x=7681,y=12213,z=-1},
            dist = {"SafehouseMedical_Late", "StoreShelfMedical", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=7681,y=12213,z=-0.5},
            dist = {"MedicalClinicTools", "MedicalStorageDrugs"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=7682,y=12211,z=-0.5},
            dist = {"MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12211,z=-1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- armory
        {
            type = 'container',
            coords = {x=7678,y=12213,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=7678,y=12212,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=7678,y=12211,z=-1},
            dist = {"MeleeWeapons", "MeleeWeapons_Mid" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12211,z=-1},
            dist = {"ArmySurplusMisc", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12211,z=-0.5},
            dist = {"GunStoreKnives", "GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "MeleeWeapons", "MeleeWeapons_Mid" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- kitchen area
        {
            type = 'container',
            coords = {x=7678,y=12216,z=-1},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7678,y=12214,z=-1},
            dist = {"BurgerKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12214,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7680,y=12214,z=-0.5},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12214,z=-1},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7683,y=12214,z=-0.5},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12214,z=-1},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7681,y=12216,z=-1},
            dist = {"KitchenDryFood", "GigamartDryGoods", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- containers along tunnel wall
        {
            type = 'container',
            coords = {x=7674,y=12216,z=-1},
            dist = {"RailYardTools","Homesteading","SurvivalGear"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=7674,y=12215,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7674,y=12214,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7674,y=12213,z=-1},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=7674,y=12212,z=-1},
            dist = {"CrateToiletPaper", "Homesteading", "CrateLinens", "StoreCounterTobacco"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        ---------------------
        ---- Main House -----
        ---------------------
        -- basement
        {
            type = 'container',
            coords = {x=7675,y=12272,z=-1},
            items = {
                { name = 'Base.LongStick', chance = 1, count = {10,10} },
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=7676,y=12271,z=-1},
            dist = {"CampingStoreLighting"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=7681,y=12268,z=0},
            dist = {"SafehouseFridge"},
            frozen = true,
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7682,y=12268,z=0},
            dist = {"SafehouseFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12268,z=0},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12269,z=0},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=7684,y=12270,z=0},
            dist = { "ArmyStorageAmmunition","SafehouseTraps","GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- south bedroom
        {
            type = 'container',
            coords = {x=7675,y=12273,z=0},
            dist = {"ArmyHangarOutfit", "ArmyStorageOutfit", "ArmySurplusOutfit", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- bathroom
        {
            type = 'container',
            coords = {x=7676,y=12271,z=0},
            dist = {"MedicalCabinet","BathroomCounter", "GasStoreToiletries"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- north bedroom
        {
            type = 'container',
            coords = {x=7674,y=12268,z=0},
            dist = {"DrugLabOutfit", "MechanicOutfit", "WildWestClothing"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=7677,y=12268,z=0},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(PrisonBreak.objectSpawns, { x = 7678, y = 12206, z = -1, removeWall = "west" })
    table.insert(PrisonBreak.objectSpawns, { x = 7679, y = 12205, z = 0, removeFloor = true, clearExisting = true, })
else
--     table.insert(PrisonBreak.objectSpawns, { sprite = "industry_trucks_01_4", x = 2607, y = 14453, z = -1, replaceWall = true, })
end
return PrisonBreak