local wtc = {x = 11606, y = 9299, z = -1}
local generator = {x = 11608, y = 9291, z = -1}
local DrugShack = {
    spawn = { x = 11613, y = 9293, z = 0 },
    waterTanks = {
        { sprite = "industry_02_73", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = {x = generator.x, y = generator.y, z = generator.z} },
    },
    waterFixtures = {
        -- upper
        { sprite = "fixtures_sinks_01_17", x = 11580, y = 9288, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_9", x = 11615, y = 9292, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_9", x = 11617, y = 9292, z = 0, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        -- basement
        { sprite = "appliances_laundry_01_1", x = 11605, y = 9294, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_2", x = 11592, y = 9298, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_14", x = 11598, y = 9290, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_4", x = 11595, y = 9284, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_bathroom_01_30", x = 11597, y = 9284, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
        { sprite = "fixtures_sinks_01_29", x = 11597, y = 9286, z = -1, sourceType="tank", source = {x = wtc.x, y = wtc.y, z = wtc.z} },
    },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = generator.x, y = generator.y, z = generator.z, },
            chunks = {
                {1448, 1160},
                {1448, 1161},
                {1448, 1162},
                {1449, 1160},
                {1449, 1161},
                {1449, 1162},
                {1450, 1160},
                {1450, 1161},
                {1450, 1162},
                {1451, 1160},
                {1451, 1161},
                {1451, 1162},
                {1452, 1160},
                {1452, 1161},
                {1452, 1162},
                {1453, 1160},
                {1453, 1161},
                {1453, 1162},
                {1447, 1161},
            },
        },
    },
    doorKeys = {
        name = "Drug Lab Key",
        doors = {
            { sprite = "fixtures_doors_01_17", x = 11617, y = 9295, z = 0, },
            { sprite = "fixtures_doors_01_8", x = 11585, y = 9287, z = 0, },
        },
    },
    map = { name = "DWAPStashMap35", },
    objectSpawns = {
        { sprite = "fixtures_railings_01_48", x = 11615, y = 9295, z = 0, },
        { sprite = "fixtures_railings_01_49", x = 11614, y = 9295, z = 0, },
        { sprite = "fixtures_railings_01_49", x = 11613, y = 9295, z = 0, },
        { sprite = "fixtures_railings_01_58", x = 11613, y = 9295, z = 0, },
        { sprite = "fixtures_railings_01_56", x = 11612, y = 9295, z = 0, },

        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_48", x = 11611, y = 9294, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_49", x = 11611, y = 9293, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_50", x = 11615, y = 9296, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_51", x = 11616, y = 9296, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_windows_01_57", x = 11621, y = 9296, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_windows_01_48", x = 11624, y = 9294, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_windows_01_49", x = 11624, y = 9293, z = 0, },
        { barricade = "metalbar", enabled = "Barricade", target="fixtures_windows_01_57", x = 11618, y = 9292, z = 0, },
    },
    loot = {
        -- lab room under trailer lab
        {
            type = 'container',
            coords = {x=11619,y=9292,z=-1},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11620,y=9292,z=-1},
            dist = {"CatfishKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11623,y=9292,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=11624,y=9292,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- warehouse room
        {
            type = 'container',
            coords = {x=11623,y=9296,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools", "CrateTools", "GarageTools", "GigamartTools", "JanitorTools", "LoggingFactoryTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=11624,y=9296,z=-1},
            dist = {"GigamartLightbulb", "LivingRoomShelfClassy", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=11623,y=9298,z=-1},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=11624,y=9298,z=-1},
            dist = {"GunStoreGuns", "GunStoreMagsAmmo", "GunStoreAmmunition", "GunStoreAccessories", "DrugShackWeapons" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=11623,y=9300,z=-1},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=11624,y=9300,z=-1},
            dist = {"DerelictHouseDrugs", "FridgeSoda", "CrateSodaBottles", "CandyStoreSnacks", "CrateTortillaChips"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11619,y=9298,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=11620,y=9298,z=-1},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=11621,y=9298,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=11619,y=9300,z=-1},
            dist = {"CarSupplyTools","GasStorageMechanics", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=11620,y=9300,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11621,y=9300,z=-1},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },

        {
            type = 'container',
            coords = {x=11617,y=9300,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=11616,y=9300,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=11615,y=9300,z=-1},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "DerelictHouseDrugs","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=11615,y=9299,z=-1},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=11616,y=9299,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=11617,y=9298,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11616,y=9298,z=-1},
            dist = {"CrateTailoring", "CrateFabric_Cotton", "CrateFabric_DenimBlack", "CrateLeather","SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=11615,y=9298,z=-1},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

        {
            type = 'container',
            coords = {x=11610,y=9301,z=-1},
            items = {
                { name = 'Base.NailsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=11609,y=9301,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=11610,y=9300,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=11609,y=9300,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },

        {
            type = 'container',
            coords = {x=11608,y=9296,z=-1},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {30,30} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=11608,y=9295,z=-1},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {30,30} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- medical room
        {
            type = 'container',
            coords = {x=11591,y=9298,z=-1},
            dist = {"SafehouseFreezer_Mid", "SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            frozen = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=11591,y=9298,z=-0.5},
            dist = {"ArmyStorageMedical", "DrugLabSupplies"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=11592,y=9298,z=-1},
            dist = {"TestingLab","MedicalCabinet","DrugShackDrugs", "DrugLabSupplies"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=11592,y=9298,z=-0.5},
            dist = {"MedicalClinicDrugs","MedicalCabinet","ArmyStorageMedical", "DerelictHouseDrugs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- "bedroom"
        {
            type = 'container',
            coords = {x=11587,y=9295,z=-1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        -- living area
        {
            type = 'container',
            coords = {x=11595,y=9298,z=-1},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        {
            type = 'container',
            coords = {x=11596,y=9298,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=11597,y=9298,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=11598,y=9298,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=11599,y=9298,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=11604,y=9296,z=-1},
            dist = {"BathroomCounter", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=11604,y=9293,z=-1},
            dist = {"CrateToiletPaper"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=11599,y=9297,z=-1},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11598,y=9297,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11597,y=9297,z=-1},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11596,y=9297,z=-1},
            dist = {"SafehouseFireplace", "StoreKitchenPots", "StoreKitchenDishes", "StoreKitchenCutlery", "JanitorCleaning" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9296,z=-1},
            dist = {"GroceryBagGourmet","CrateFlour","CrateOilVegetable",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9295,z=-1},
            dist = {"StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9294,z=-1},
            dist = {"StoreKitchenBaking", "WesternKitchenBaking"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9292,z=-1},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9291,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11595,y=9290,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=11596,y=9290,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
    },
}

-- if getActivatedMods():contains("\\Ladders") then
--     table.insert(DrugShack.objectSpawns, { x = 8712, y = 15311, z = -1, removeWall = "west" })
--     table.insert(DrugShack.objectSpawns, { sprite = "walls_exterior_wooden_01_26", x = 8716, y = 15314, z = 0, removeFloor = true, clearExisting = true, })
--     table.insert(DrugShack.objectSpawns, { sprite = "location_sewer_01_33", x = 8716, y = 15314, z = 0, })
--     table.insert(DrugShack.objectSpawns, { x = 8716, y = 15314, z = 1, removeFloor = true, clearExisting = true, })
-- else
--     -- table.insert(DrugShack.objectSpawns, { sprite = "industry_trucks_01_4", x = 2607, y = 14453, z = -1, replaceWall = true, })
-- end
return DrugShack