-- @TODO (2026-08-07 audit) unresolved - delete lines as they are fixed
--   * 2 skeleton entries carry coords but no loot yet - entries 26-27
--   * systems: generator controls declare industry_02_67 but no such object
--     is on the square. 11 configs name that sprite and ALL 11 fail, while 32
--     configs use dwap_tiles_01_22 - the maps look to have moved on and these
--     configs did not. Confirm what is actually there before editing
--   * systems: 1 component at 1659,5747 z=0 names a sprite that is not on the
--     square, though the square itself loads - config drifted from the map
local wtc1 = {x = 1662, y = 5746, z = -2,}
local pb1 = { x = 1666, y = 5746, z = -4 }
local GasCorner = {
    group = "Brandenburg",
    baseBuildings = {
        { x = 1664, y = 5746, z = 1 }, -- gas station
        { x = 1664, y = 5746, z = -1 }, -- basement 1
        { x = 1664, y = 5746, z = -4 }, -- basement 2
    },
    spawn = { x = 1664, y = 5746, z = 1 },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = pb1.x-1, y = pb1.y, z = pb1.z },
            fakeGenerators = {
                { x = 1659, y = 5749, z = -1, createTile = true },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc1.x, y = wtc1.y, z = wtc1.z, sourceType="generator", source = {x = 1666, y = 5746, z = -4} },
    },
    waterFixtures = {
        { sprite = "fixtures_bathroom_01_1", x = 1661, y = 5749, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_9", x = 1663, y = 5749, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_30", x = 1658, y = 5750, z = -4, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_32", x = 1665, y = 5749, z = -3, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "appliances_laundry_01_7", x = 1659, y = 5746, z = -2, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_bathroom_01_4", x = 1658, y = 5747, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_9", x = 1659, y = 5747, z = 0, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },

        { sprite = "fixtures_sinks_01_9", x = 1661, y = 5744, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_33", x = 1657, y = 5748, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_bathroom_01_2", x = 1659, y = 5748, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
        { sprite = "fixtures_sinks_01_23", x = 1659, y = 5747, z = 1, sourceType="tank", source = {x = wtc1.x, y = wtc1.y, z = wtc1.z} },
    },
    doorKeys = {
        name = "Brandenburg Gas Corner",
        doors = {
            { sprite = "fixtures_doors_02_5", x = 1661, y = 5752, z = 0, },
            { sprite = "fixtures_doors_02_5", x = 1657, y = 5748, z = 0, },
            { sprite = "fixtures_doors_02_5", x = 1657, y = 5749, z = -1, },
        },
    },
    map = { name = "DWAPStashMap37", },
    objectSpawns = {
        -- { sprite = "camping_01_16", x = 1652, y = 5746, z = 0, enabled = "EnableWaterSystem", }, -- well
        { sprite = "industry_02_175", x = pb1.x, y = pb1.y, z = pb1.z, disabled = "EnableGenSystemSolar", clearExisting = true, },

        -- { x = 1657, y = 5744, z = -1, clearExisting = true, },
        -- { x = 1657, y = 5745, z = -1, removeWall = "north", },

        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_113", x = 1663, y = 5753, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="walls_commercial_01_113", x = 1664, y = 5753, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_02_5", x = 1661, y = 5753, z = 0, },
        { barricade = "metal", enabled = "Barricade", target="fixtures_windows_01_56", x = 1673, y = 5747, z = 0, },

    },
    loot = {
        -- lowest level
        { -- E1
            note = "counter @ bunker",
            coords = {x=1664,y=5749,z=-4},
            dist = { "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E2
            note = "overhead @ bunker",
            coords = {x=1664,y=5749,z=-4},
            slot = "upper",
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E3
            note = "counter @ bunker",
            coords = {x=1663,y=5749,z=-4},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E4
            note = "overhead @ bunker",
            coords = {x=1663,y=5749,z=-4},
            slot = "upper",
            dist = {"GigamartCrisps","ControlRoomCounter" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E5
            note = "medicine @ bunker",
            coords = {x=1661,y=5749,z=-4},
            slot = "upper",
            dist = {"BathroomCounter", "GasStoreToiletries",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E6
            note = "shelves @ bunker",
            coords = {x=1660,y=5750,z=-4},
            slot = "upper",
            items = {
                { name = 'Base.Hat_GasMask', },
                { name = 'Base.GasmaskFilter', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E7
            note = "medicine @ bunker",
            coords = {x=1659,y=5750,z=-4},
            slot = "upper",
            dist = {"SafehouseMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E8
            note = "locker @ gunstore",
            coords = {x=1658,y=5749,z=-4},
            dist = {"MeleeWeapons", "MeleeWeapons_Mid", "CampingStoreBackpacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        { -- E9
            note = "militarycrate @ gunstore",
            coords = {x=1660,y=5745,z=-4},
            dist = { "SafehouseTraps", "SafehouseArmor", "SafehouseArmor_Late", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E10
            note = "militarylocker @ gunstore",
            coords = {x=1661,y=5745,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E11
            note = "militarylocker @ gunstore",
            coords = {x=1662,y=5745,z=-4},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E12
            note = "cardboardbox @ gunstore",
            coords = {x=1667,y=5745,z=-4},
            dist = {"CrateOilVegetable","GunStoreMagsAmmo", "GunStoreAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        -- -3, books and crafting room
        { -- E13
            note = "shelves @ lobby",
            coords = {x=1659,y=5744,z=-3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- E14
            note = "shelves @ lobby",
            coords = {x=1659,y=5745,z=-3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- E15
            note = "shelves @ lobby",
            coords = {x=1659,y=5746,z=-3},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- E16
            note = "shelves @ lobby",
            coords = {x=1659,y=5747,z=-3},
            dist = {"BookstoreBiography", "BookstoreBusiness", "MusicStoreCDs", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- small back room
        { -- E17
            note = "metal_shelves @ warehouse",
            coords = {x=1665,y=5750,z=-3},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- E18
            note = "metal_shelves @ warehouse",
            coords = {x=1665,y=5748,z=-3},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E19
            note = "crate @ warehouse",
            coords = {x=1667,y=5750,z=-3},
            special = "essentials",
        },
        -- main work room
        { -- E20
            note = "metal_shelves @ farmstorage",
            coords = {x=1661,y=5750,z=-3},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E21
            note = "metal_shelves @ farmstorage",
            coords = {x=1661,y=5749,z=-3},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E22
            note = "counter @ farmstorage",
            coords = {x=1661,y=5747,z=-3},
            dist = {"GasStoreEmergency","CarSupplyTools","GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E23
            note = "counter @ farmstorage",
            coords = {x=1661,y=5746,z=-3},
            dist = {"ToolStoreMetalwork","CrateBlacksmithing", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E24
            note = "counter @ farmstorage",
            coords = {x=1661,y=5745,z=-3},
            dist = {"CrateTools", "GarageTools", "BarnTools",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E25
            note = "counter @ farmstorage",
            coords = {x=1663,y=5745,z=-3},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E26
            note = "metal_shelves @ farmstorage",
            coords = {x=1665,y=5745,z=-3},
        },
        { -- E27
            note = "metal_shelves @ farmstorage",
            coords = {x=1665,y=5746,z=-3},
        },
        { -- E28
            note = "metal_shelves @ farmstorage",
            coords = {x=1667,y=5745,z=-3},
            dist = {"CrateTailoring", "CrateFabric_Cotton", "CrateFabric_DenimBlack", "CrateLeather","SewingStoreFabric"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- E29
            note = "metal_shelves @ farmstorage",
            coords = {x=1667,y=5746,z=-3},
            dist = {"ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- -2 level, laundry, main storage
        { -- E30
            note = "clothingdryerbasic @ lobby",
            coords = {x=1659,y=5744,z=-2},
            dist = {"LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "CrateBootsArmy"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E31
            note = "shelves @ lobby",
            coords = {x=1659,y=5744,z=-2},
            slot = "upper",
            dist = {"LaundryCleaning", "JanitorCleaning"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E32
            note = "freezer @ warehouse",
            coords = {x=1661,y=5750,z=-2},
            dist = {"FreezerIceCream", "WesternKitchenFreezer", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E33
            note = "freezer @ warehouse",
            coords = {x=1661,y=5749,z=-2},
            dist = {"FridgeFarmStorage", "FreezerIceCream"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E34
            note = "woodstove @ warehouse",
            coords = {x=1662,y=5750,z=-2},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E35
            note = "metal_shelves @ warehouse",
            coords = {x=1663,y=5750,z=-2},
            dist = {"SafehouseFireplace", "SafehouseLighting", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- E36
            note = "shelves @ warehouse",
            coords = {x=1664,y=5750,z=-2},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E37
            note = "shelves @ warehouse",
            coords = {x=1665,y=5750,z=-2},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E38
            note = "shelves @ warehouse",
            coords = {x=1666,y=5750,z=-2},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E39
            note = "shelves @ warehouse",
            coords = {x=1667,y=5750,z=-2},
            dist = {"CrateFlour", "CrateOilVegetable"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E40
            note = "crate @ warehouse",
            coords = {x=1663,y=5747,z=-2},
            dist = {"SafehouseMedical_Late", "StoreShelfMedical", "ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E41
            note = "crate @ warehouse",
            coords = {x=1663,y=5746,z=-2},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E42
            note = "crate @ warehouse",
            coords = {x=1663,y=5745,z=-2},
            dist = {"LiquorStoreBeer", "JanitorCleaning", "DrugLabGuns", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E43
            note = "smallbox @ warehouse",
            coords = {x=1665,y=5748,z=-2},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.Sheet', },
                { name = 'Base.WoodAxe', },
                { name = 'Base.Machete', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E44
            note = "clothingrack @ warehouse",
            coords = {x=1665,y=5747,z=-2},
            dist = {"ClothingStorageWinter",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E45
            note = "clothingrack @ warehouse",
            coords = {x=1665,y=5746,z=-2},
            dist = {"HuntingLockers", "RangerTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E46
            note = "clothingrack @ warehouse",
            coords = {x=1665,y=5745,z=-2},
            dist = {"TheatrePopcorn", "FridgeSoda",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E47
            note = "cardboardbox @ warehouse",
            coords = {x=1667,y=5748,z=-2},
            dist = {"CrateFishing",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- E48
            note = "crate @ warehouse",
            coords = {x=1667,y=5747,z=-2},
            dist = {"CrateLumber", "CrateSheetMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E49
            note = "crate @ warehouse",
            coords = {x=1667,y=5746,z=-2},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        { -- E50
            note = "crate @ warehouse",
            coords = {x=1667,y=5745,z=-2},
            dist = {"CrateGravelBags", "CrateSandBags", "CrateClayBags"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- store basement
        { -- E51
            note = "metal_shelves @ hall",
            coords = {x=1658,y=5747,z=-1},
            slot = "upper",
            dist = {"CrateToiletPaper", "CrateLinens"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E52
            note = "metal_shelves @ janitor",
            coords = {x=1658,y=5746,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E53
            note = "metal_shelves @ janitor",
            coords = {x=1658,y=5745,z=-1},
            dist = {"CrateBlacksmithing" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        { -- E54
            note = "metal_shelves @ storageunit",
            coords = {x=1664,y=5744,z=-1},
            slot = "upper",
            dist = {"ArmyStorageOutfit",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E55
            note = "metal_shelves @ storageunit",
            coords = {x=1665,y=5744,z=-1},
            slot = "upper",
            dist = {"DrugLabOutfit",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E56
            note = "crate @ storageunit",
            coords = {x=1662,y=5746,z=-1},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E57
            note = "crate @ storageunit",
            coords = {x=1663,y=5746,z=-1},
            dist = {"CrateFlour", "CrateOilVegetable", "CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E58
            note = "crate @ storageunit",
            coords = {x=1664,y=5746,z=-1},
            dist = {"SafehouseMedical", "LiquorStoreWhiskey" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E59
            note = "crate @ storageunit",
            coords = {x=1663,y=5747,z=-1},
            dist = {"LiquorStoreBeer","LiquorStoreBeerFancy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E60
            note = "crate @ storageunit",
            coords = {x=1664,y=5747,z=-1},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E61
            note = "locker @ storageunit",
            coords = {x=1664,y=5748,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- E62
            note = "crate @ storageunit",
            coords = {x=1663,y=5751,z=-1},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- store area
        { -- E63
            note = "shelves @ gasstore",
            coords = {x=1661,y=5746,z=0},
            dist = {"CrateToiletPaper", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E64
            note = "shelves @ gasstore",
            coords = {x=1662,y=5746,z=0},
            dist = {"CrateBootsArmy",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E65
            note = "shelves @ gasstore",
            coords = {x=1663,y=5746,z=0},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E66
            note = "shelves @ gasstore",
            coords = {x=1664,y=5746,z=0},
            dist = {"SafehouseTraps","GunStoreKnives","CrateLiquor", "CarSupplyTools",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E67
            note = "shelvesmag @ gasstore",
            coords = {x=1660,y=5751,z=0},
            dist = {"LivingRoomShelfClassy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E68
            note = "shelvesmag @ gasstore",
            coords = {x=1660,y=5752,z=0},
            dist = {"MusicStoreCDs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- E69
            note = "counter @ gasstore",
            coords = {x=1664,y=5750,z=0},
            dist = { "GasStoreEmergency", "StoreCounterTobacco" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- upper house level
        { -- E70
            note = "fridge @ kitchen",
            coords = {x=1659,y=5744,z=1},
            dist = {"SushiKitchenFreezer", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E71
            note = "counter @ kitchen",
            coords = {x=1660,y=5744,z=1},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- E72
            note = "counter @ kitchen",
            coords = {x=1661,y=5744,z=1},
            dist = {"LaundryCleaning", "JanitorCleaning", "MedicalStorageDrugs"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E73
            note = "counter @ kitchen",
            coords = {x=1662,y=5744,z=1},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- E74
            note = "sidetable @ bedroom",
            coords = {x=1664,y=5744,z=1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- E75
            note = "dresser @ bedroom",
            coords = {x=1665,y=5747,z=1},
            dist = {"LaundryLoad1", "ArmySurplusOutfit", "ToolStoreOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        { -- E76
            note = "counter @ bathroom",
            coords = {x=1659,y=5747,z=1},
            dist = {"MedicalClinicDrugs", "MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- E77
            note = "sidetable @ livingroom",
            coords = {x=1665,y=5749,z=1},
            items = {
                { name = 'Base.Sledgehammer', chance = 1, count = {1,1}, },
                { name = 'Base.Machete', chance = 1, count = {1,1}, },
            },
        },
    },
}

if getActivatedMods():contains("\\Ladders") then
    table.insert(GasCorner.objectSpawns, { enabled = "EnableLadders", sprite = "fencing_01_27", x = 1628, y = 5760, z = 0, removeFloor = true, clearExisting = true, })
end

return GasCorner