local bunkerTopLeft = {x = 12828, y = 1604, z = -1}
local wtc = {x = 12835, y = 1614, z = 1}
local pb1 = { x = 12836, y = 1611, z = 1 }
local LouisvilleTownhouse = {
    spawn = { x = 12832, y = 1619, z = 0 },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = wtc.x, y = wtc.y, z = wtc.z, sourceType="generator", source = 1 },
    },
    waterFixtures = {
        { sprite = "fixtures_bathroom_01_6", x = 12830, y = 1612, z = -1, sourceType="tank", source = 1 },
        { sprite = "fixtures_sinks_01_16", x = 12828, y = 1608, z = -1, sourceType="tank", source = 1 },

        { sprite = "fixtures_bathroom_01_0", x = 12831, y = 1614, z = 0, sourceType="tank", source = 1 },
        { sprite = "fixtures_sinks_01_2", x = 12832, y = 1614, z = 0, sourceType="tank", source = 1 },
        { sprite = "fixtures_sinks_01_9", x = 12835, y = 1610, z = 0, sourceType="tank", source = 1 },
    },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = pb1.x-1, y = pb1.y, z = pb1.z },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = pb1.x, y = pb1.y, z = pb1.z },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12834,
                        y = 1613,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12835,
                        y = 1613,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12836,
                        y = 1613,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12837,
                        y = 1613,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12838,
                        y = 1613,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12834,
                        y = 1615,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12835,
                        y = 1615,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12836,
                        y = 1615,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12837,
                        y = 1615,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 12838,
                        y = 1615,
                        z = 2,
                        pb = 1,
                        spawn = true,
                    },
                }
            },
            fakeGenerators = {
                { x = 12835, y = 1615, z = -1, },
            },
            chunks = {
                {1603, 201},
                {1603, 202},
                {1604, 201},
                {1604, 202},
                {1605, 201},
                {1605, 202},
                {1606, 201},
                {1606, 202},
                {1607, 201},
                {1607, 202},
            },
        },
    },
    doorKeys = {
        name = "Louisville Townhouse",
        doors = {
            { sprite = "fixtures_doors_01_53", x = 12830, y = 1612, z = 0, },
            { sprite = "fixtures_doors_01_53", x = 12831, y = 1612, z = 2, },
        },
    },
    map = { name = "DWAPStashMap42", },
    objectSpawns = {
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_16", x = 12830, y = 1617, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_16", x = 12830, y = 1611, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_windows_01_17", x = 12835, y = 1610, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="fixtures_doors_01_5", x = 12835, y = 1620, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_17", x = 12832, y = 1621, z = 0, },
        { barricade = "wood", enabled = "Barricade", target="fixtures_windows_01_17", x = 12831, y = 1621, z = 0, },

    },
    loot = {
        { -- cabinet next to bunk beds (9365)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+2,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        { -- upper
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (66)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+3,z=bunkerTopLeft.z},
            special = "kitchentools",
            level = "Loot_FoodLevel",
        },
        { -- upper
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z+0.5},
            dist = {"CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { -- lower (67)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+4,z=bunkerTopLeft.z},
            dist = {"TestingLab","MedicalCabinet","ArmyStorageMedical", "ArmyBunkerMedical"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        { -- upper
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z+0.5},
            dist = {"CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        { -- lower (68)
            type = 'container',
            sprite = 'location_trailer_02_19',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"SewingStoreTools"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        { -- metal shelves (70)
            type = 'container',
            sprite = 'location_trailer_02_23',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "CrateLinens", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        { -- metal shelves (71)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+8,z=bunkerTopLeft.z},
            sandboxEnable = 'SeedLibrary',
            special = 'SeedLibrary',
        },
        { -- next to inner door (9372)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+9,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        { -- (73)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+10,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        { -- (9374)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+11,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        { -- far end next to stairs (9375)
            type = 'container',
            coords = {x=bunkerTopLeft.x,y=bunkerTopLeft.y+12,z=bunkerTopLeft.z},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+5,z=bunkerTopLeft.z},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", "CrateVHSTapes", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+6,z=bunkerTopLeft.z},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        { -- metal wall shelves
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+7,z=bunkerTopLeft.z},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },

        -- extra spawns
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y,z=bunkerTopLeft.z},
            dist = {"GasStoreEmergency","StoreCounterTobacco", "BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=bunkerTopLeft.x+2,y=bunkerTopLeft.y+1,z=bunkerTopLeft.z},
            dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor", "CarSupplyTools","DrugLabOutfit"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },

        -- addon room
        -- {
        --     type = 'container',
        --     coords = {x = 5578, y = 9373, z = -1},
        --     special = "gunlocker",
        --     level = "Loot_GunLevel",
        -- },
        -- { -- [20]
        --     type = 'container',
        --     coords = {x = 5581, y = 9376, z = -1},
        --     dist = {"HuntingLockers", "RangerTools"},
        --     distIncludeJunk = false,
        --     randUntilFull = true,
        --     level = "Loot_FishLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5582, y = 9376, z = -1},
        --     dist = {"BurglarTools", "CarpenterTools", "BarnTools","SafehouseArmor", "SafehouseLighting"},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_LockersLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5583, y = 9376, z = -1},
        --     dist = {"CarSupplyTools", "GasStorageMechanics", "CampingLockers"},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_GunLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5584, y = 9376, z = -1},
        --     dist = {"SafehouseTraps","GunStoreKnives","CampingStoreBackpacks","CrateLiquor",},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_GunLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5584, y = 9375, z = -1},
        --     dist = {"GasStoreEmergency","StoreCounterTobacco"},
        --     distIncludeJunk = true,
        --     randUntilFull = true,
        --     level = "Loot_ToolsLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5584, y = 9374, z = -1},
        --     dist = {"CrateCannedFood", "KitchenCannedFood"},
        --     distIncludeJunk = false,
        --     randUntilFull = true,
        --     level = "Loot_FoodLevel",
        -- },
        -- {
        --     type = 'container',
        --     coords = {x = 5584, y = 9371, z = -1},
        --     items = {
        --         { name = 'Base.NailsBox', },
        --         { name = 'Base.Sheet', },
        --         { name = 'Base.WoodAxe', },
        --         { name = 'Base.Machete', },
        --         { name = 'Base.Plank', },
        --         { name = 'Base.SteelBar', },
        --         { name = 'Base.PropaneTank', },
        --     },
        --     randUntilFull = true,
        --     level = "Loot_BuildMatsLevel",
        -- },
    },
}

return LouisvilleTownhouse
