--- Reusable "big bunker" loot preset (the 100 loot entries shared by every
--- large military-bunker safehouse: configs 04, 10 and 12).
---
--- These three sites are the same underground template stamped at different
--- origins, so 100 of their loot squares are identical once expressed relative
--- to a shared origin. This module is the single source of truth for that
--- shared core. Each site's handful of site-specific squares (a different
--- books/media arrangement, a relocated tailoring bin, an essentials shelf in
--- a different spot) stays INLINE in the config, appended after this call.
---
--- The origin is the generator-CONTROLS square (config 04 {9947,12616,-4},
--- config 10 {13636,1262,-4}, config 12 {751,9812,-5}); every emitted entry's
--- coords = origin + (dx,dy,dz). z offsets are 0 here - the whole layout is on
--- the origin's floor.
---
--- Usage:
---   local BigBunkerShell = require("DWAP/configs/presets/BigBunkerShell")
---   local loot = BigBunkerShell({ x = 9947, y = 12616, z = -4 })
---   loot[#loot + 1] = { ... }  -- site-specific entries, origin-relative

local specs = {
    {
        id = "B1",
        dx = -3,
        dy = -7,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B2",
        dx = -3,
        dy = -6,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B3",
        dx = -3,
        dy = -5,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B4",
        dx = -3,
        dy = -4,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B5",
        dx = -3,
        dy = -3,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B6",
        dx = -3,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B7",
        dx = -3,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        dist = { "StoreCounterTobacco" },
        distIncludeJunk = true,
        level = 1,
    },
    {
        id = "B8",
        dx = -3,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B9",
        dx = -3,
        dy = 21,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B10",
        dx = -3,
        dy = 22,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B11",
        dx = -3,
        dy = 23,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B12",
        dx = -3,
        dy = 24,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B13",
        dx = -3,
        dy = 25,
        dz = 0,
        note = "locker @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPLockers",
    },
    {
        id = "B14",
        dx = -2,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B15",
        dx = -2,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B16",
        dx = -2,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B17",
        dx = -1,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        dist = { "CrateLumber" },
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B18",
        dx = -1,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        items = {
            { name = 'Base.NailsBox', },
            { name = 'Base.ScrewsBox', },
        },
        level = "Loot_BuildMatsLevel",
    },
    {
        id = "B19",
        dx = -1,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B20",
        dx = 0,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B21",
        dx = 0,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        items = {
            { name = 'Base.NailsCarton', },
        },
        level = "Loot_BuildMatsLevel",
    },
    {
        id = "B22",
        dx = 0,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B23",
        dx = 1,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B24",
        dx = 1,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B25",
        dx = 2,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPBuildMats",
    },
    {
        id = "B26",
        dx = 2,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        dist = { "GasStoreEmergency" },
        distIncludeJunk = true,
        level = 2,
    },
    {
        id = "B27",
        dx = 3,
        dy = 11,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CampingLockers" },
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B28",
        dx = 3,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CampingStoreBackpacks" },
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B29",
        dx = 3,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B30",
        dx = 3,
        dy = 14,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "SafehouseTraps", },
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B31",
        dx = 3,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        special = "essentials",
    },
    {
        id = "B32",
        dx = 3,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B33",
        dx = 6,
        dy = 14,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B34",
        dx = 6,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B35",
        dx = 6,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B36",
        dx = 6,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B37",
        dx = 6,
        dy = 18,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B38",
        dx = 6,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "LoggingFactoryTools" },
        distIncludeJunk = true,
        tag = "DWAPTools",
    },
    {
        id = "B39",
        dx = 9,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CrateRandomJunk", "RandomFiller", "ArmySurplusMisc" },
        distIncludeJunk = true,
        level = 3,
    },
    {
        id = "B40",
        dx = 9,
        dy = 13,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B41",
        dx = 9,
        dy = 14,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CrateRandomJunk", "RandomFiller" },
        distIncludeJunk = true,
        level = 3,
    },
    {
        id = "B42",
        dx = 9,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B43",
        dx = 9,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPBuildMats",
    },
    {
        id = "B44",
        dx = 9,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "ToolFactoryHandles" },
        distIncludeJunk = false,
        tag = "DWAPBuildMats",
    },
    {
        id = "B45",
        dx = 9,
        dy = 18,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CrateSheetMetal" },
        distIncludeJunk = false,
        tag = "DWAPBuildMats",
    },
    {
        id = "B46",
        dx = 9,
        dy = 19,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "ToolFactoryIngots" },
        distIncludeJunk = false,
        tag = "DWAPBuildMats",
    },
    {
        id = "B47",
        dx = 12,
        dy = -9,
        dz = 0,
        note = "metal_shelves @ empty",
        slot = "upper",
        dist = { "LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8" },
        distIncludeJunk = true,
        level = 1,
    },
    {
        id = "B48",
        dx = 12,
        dy = 11,
        dz = 0,
        -- filingcabinet next to spawn in operations room
        note = "filingcabinet @ empty",
        items = {
            { name = 'Base.Pencil',                          chance = 1, count = { 2, 5 } },
            { name = 'Base.Notebook',                        chance = 1, count = { 1, 1 } },
            { name = 'Base.Notebook',                        chance = 1, count = { 1, 1 } },
            { name = 'Base.WristWatch_Left_DigitalBlack',    chance = 1, count = { 1, 1 } },
            { name = 'Base.WristWatch_Left_ClassicMilitary', chance = 1, count = { 1, 1 } },
        },
    },
    {
        id = "B49",
        dx = 12,
        dy = 12,
        dz = 0,
        -- 2nd filingcabinet next to spawn in operations room
        note = "filingcabinet @ empty",
        sandboxEnable = 'Loot_EnableMaps',
        special = "maps",
    },
    {
        id = "B50",
        dx = 12,
        dy = 27,
        dz = 0,
        note = "metal_shelves @ empty",
        slot = "upper",
        dist = { "LaundryLoad1", "LaundryLoad2", "LaundryLoad3", "LaundryLoad4", "LaundryLoad5", "LaundryLoad6", "LaundryLoad7", "LaundryLoad8" },
        distIncludeJunk = true,
        level = 1,
    },
    {
        id = "B51",
        dx = 15,
        dy = -6,
        dz = 0,
        note = "counter @ oldarmy",
        dist = { "CrateCannedFood", },
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B52",
        dx = 16,
        dy = -6,
        dz = 0,
        note = "counter @ oldarmy",
        dist = { "CrateCannedFood", },
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B53",
        dx = 16,
        dy = -4,
        dz = 0,
        note = "counter @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B54",
        dx = 17,
        dy = -4,
        dz = 0,
        note = "counter @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B55",
        dx = 18,
        dy = -4,
        dz = 0,
        note = "counter @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B56",
        dx = 18,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "DishCabinetLiquor" },
        distIncludeJunk = true,
        tag = "DWAPBooze",
    },
    {
        id = "B57",
        dx = 19,
        dy = -6,
        dz = 0,
        note = "counter @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B58",
        dx = 19,
        dy = -4,
        dz = 0,
        note = "counter @ oldarmy",
        dist = { "StoreKitchenBaking", },
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B59",
        dx = 19,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPBooze",
    },
    {
        id = "B60",
        dx = 19,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        sandboxEnable = 'SeedLibrary',
        items = {
            { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
        },
        level = "Loot_FarmLevel",
    },
    {
        id = "B61",
        dx = 19,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        sandboxEnable = 'SeedLibrary',
        items = {
            { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
        },
        level = "Loot_FarmLevel",
    },
    {
        id = "B62",
        dx = 19,
        dy = 21,
        dz = 0,
        note = "metal_shelves @ empty",
        dist = { "CrateToiletPaper" },
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B63",
        dx = 19,
        dy = 22,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = true,
        tag = "DWAPFood",
    },
    {
        id = "B64",
        dx = 20,
        dy = -6,
        dz = 0,
        note = "counter @ oldarmy",
        special = "kitchentools",
        level = "Loot_FoodLevel",
    },
    {
        id = "B65",
        dx = 20,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CrateLiquor" },
        distIncludeJunk = false,
        tag = "DWAPBooze",
    },
    {
        id = "B66",
        dx = 21,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        dist = { "CrateInstruments" },
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B67",
        dx = 21,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFarm",
    },
    {
        id = "B68",
        dx = 21,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFarm",
    },
    {
        id = "B69",
        dx = 22,
        dy = 9,
        dz = 0,
        note = "medicine @ oldmedical",
        slot = "upper",
        dist = { "MedicalCabinet" },
        distIncludeJunk = false,
        tag = "DWAPMed",
    },
    {
        id = "B70",
        dx = 22,
        dy = 10,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPMed",
    },
    {
        id = "B71",
        dx = 22,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFish",
    },
    {
        id = "B72",
        dx = 22,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B73",
        dx = 22,
        dy = 21,
        dz = 0,
        note = "counter @ empty",
        dist = { "SewingStoreTools" },
        distIncludeJunk = true,
        tag = "DWAPTailor",
    },
    {
        id = "B74",
        dx = 23,
        dy = 10,
        dz = 0,
        note = "metal_shelves @ oldmedical",
        distIncludeJunk = true,
        tag = "DWAPMed",
    },
    {
        id = "B75",
        dx = 23,
        dy = 12,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFish",
    },
    {
        id = "B76",
        dx = 23,
        dy = 15,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        sandboxEnable = 'SeedLibrary',
        special = 'SeedLibrary',
    },
    {
        id = "B77",
        dx = 23,
        dy = 16,
        dz = 0,
        note = "metal_shelves @ oldarmy",
        distIncludeJunk = false,
        tag = "DWAPFarm",
    },
    {
        id = "B78",
        dx = 23,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPFood",
    },
    {
        id = "B79",
        dx = 23,
        dy = 21,
        dz = 0,
        note = "counter @ empty",
        dist = { "SewingStoreFabric" },
        distIncludeJunk = true,
        tag = "DWAPTailor",
    },
    {
        id = "B80",
        dx = 23,
        dy = 22,
        dz = 0,
        note = "counter @ empty",
        dist = { "CrateLeather" },
        distIncludeJunk = true,
        tag = "DWAPTailor",
    },
    {
        id = "B81",
        dx = 23,
        dy = 24,
        dz = 0,
        note = "bin @ empty",
        distIncludeJunk = true,
        tag = "DWAPTailor",
    },
    {
        id = "B82",
        dx = 26,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        sandboxEnable = 'Loot_EnableBooks',
        special = 'skillbooks1',
    },
    {
        id = "B83",
        dx = 27,
        dy = -2,
        dz = 0,
        note = "locker @ empty",
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        id = "B84",
        dx = 27,
        dy = 1,
        dz = 0,
        note = "locker @ empty",
        dist = { "FirearmWeapons_Late", },
        distIncludeJunk = false,
        tag = "DWAPGun",
    },
    {
        id = "B85",
        dx = 27,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        sandboxEnable = 'Loot_EnableBooks',
        special = 'skillbooks2',
    },
    {
        id = "B86",
        dx = 28,
        dy = -2,
        dz = 0,
        note = "locker @ empty",
        distIncludeJunk = false,
        tag = "DWAPGun",
    },
    {
        id = "B87",
        dx = 28,
        dy = 1,
        dz = 0,
        note = "locker @ empty",
        dist = { "DrugLabGuns" },
        distIncludeJunk = false,
        tag = "DWAPGun",
    },
    {
        id = "B88",
        dx = 28,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        sandboxEnable = 'Loot_EnableBooks',
        special = 'skillmags',
    },
    {
        id = "B89",
        dx = 28,
        dy = 20,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B90",
        dx = 29,
        dy = -2,
        dz = 0,
        note = "locker @ empty",
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        id = "B91",
        dx = 29,
        dy = 1,
        dz = 0,
        note = "locker @ empty",
        distIncludeJunk = false,
        tag = "DWAPGun",
    },
    {
        id = "B92",
        dx = 29,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B93",
        dx = 29,
        dy = 20,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B94",
        dx = 30,
        dy = -2,
        dz = 0,
        note = "locker @ empty",
        special = "gunlocker",
        level = "Loot_GunLevel",
    },
    {
        id = "B95",
        dx = 30,
        dy = 1,
        dz = 0,
        note = "locker @ empty",
        distIncludeJunk = true,
        tag = "DWAPGun",
    },
    {
        id = "B96",
        dx = 30,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        dist = { "CrateVHSTapes" },
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B97",
        dx = 30,
        dy = 20,
        dz = 0,
        note = "metal_shelves @ empty",
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B98",
        dx = 31,
        dy = 17,
        dz = 0,
        note = "metal_shelves @ empty",
        dist = { "MovieRentalShelves" },
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B99",
        dx = 31,
        dy = 20,
        dz = 0,
        note = "metal_shelves @ empty",
        dist = { "MusicStoreCDs" },
        distIncludeJunk = false,
        tag = "DWAPMedia",
    },
    {
        id = "B100",
        dx = 33,
        dy = 16,
        dz = 0,
        note = "shelves @ empty",
        dist = { "BookstoreNonFiction", "BookstoreMilitaryHistory" },
        distIncludeJunk = false,
        level = 1,
    },
}

-- Deep copy so the require-cached spec tables are never aliased into (or
-- mutated through) an emitted entry - dist and items are nested tables.
local function deepcopy(v)
    if type(v) ~= "table" then return v end
    local out = {}
    for k, val in pairs(v) do out[k] = deepcopy(val) end
    return out
end

--- @param origin table {x=,y=,z=} the generator-controls square.
--- @param overrides table|nil optional map keyed by spec id ("B1".."B100").
---        Each value is a PARTIAL field table shallow-merged onto that entry
---        after the defaults are applied. None of the current three sites need
---        one (their differences are inline extras, not tweaks to the shared
---        core), but the hook matches BunkerShell_17 for future sites.
--- @return table entries a fresh array of loot entries (new tables every call).
return function(origin, overrides)
    local out = {}
    for i = 1, #specs do
        local entry = deepcopy(specs[i])
        entry.coords = { x = origin.x + entry.dx, y = origin.y + entry.dy, z = origin.z + entry.dz }
        entry.dx, entry.dy, entry.dz = nil, nil, nil

        local ov = overrides and overrides[entry.id]
        if ov then
            for k, val in pairs(ov) do entry[k] = deepcopy(val) end
        end
        entry.id = nil

        out[i] = entry
    end
    return out
end
